boto/botocore

- CONTRIBUTING.rst
This also brings it more in sync with the contributing
guidelines for other SDKs.
For reference:
https://github.com/aws/aws-sdk-core-ruby/blob/master/CONTRIBUTING.md
https://github.com/aws/aws-sdk-php/blob/master/CONTRIBUTING.md
cc @kyleknap
> Update CONTRIBUTING guide with latest guidelines

- botocore/parsers.py
- tests/unit/protocols/output/rest-xml.json
- tests/unit/response_parsing/xml/responses/s3-list-multipart-uploads#2.json
- tests/unit/response_parsing/xml/responses/s3-list-multipart-uploads.json
- tests/unit/response_parsing/xml/responses/s3-list-object-versions.json
- tests/unit/response_parsing/xml/responses/s3-list-objects.json
- tests/unit/test_response.py
This allows `get_*` operations to better round trip with the
corresponding `put_*` operations.
We can get the code reviewed, but I'm not sure this is change we want.
It has the potential to break users so we'll need to evaluate if we can take
this change.
cc @kyleknap @danielgtaylor 
Fixes https://github.com/aws/aws-cli/issues/1076
> Parse empty xml nodes that are strings are an empty string

- botocore/compat.py
- botocore/data/aws/glacier/2012-06-01.normal.json
- botocore/handlers.py
- botocore/parsers.py
- botocore/utils.py
- tests/__init__.py
- tests/integration/test_glacier.py
- tests/integration/test_smoke.py
- tests/unit/test_handlers.py
- tests/unit/test_parsers.py
- tests/unit/test_utils.py
In addition to including the JSON model for the service,
there were also three customizations needed:
* Add the x-amz-glacier-version header to all glacier requests
* Add a default value of '-' for the accountId param if it's not
provided
* Add (and compute) the x-amz-content-sha256 and the
x-amz-sha256-tree-hash header (also the "checksum" param)
automatically for the user.
I verified I got the same tree hash values from boto2 and I
also added some integration tests to double check this.  The
tree hash is somewhat similar to boto's version, with some
slight performance improvements (about ~33% faster tree hashes).
We'll need to make a corresponding change to the the CLI to
make the --account-id param optional since botocore will
fill that value in.
cc @kyleknap
> Initial commit of glacier support in botocore

- botocore/endpoint.py
- botocore/service.py
- tests/unit/test_endpoint.py
- tests/unit/test_service.py
Add option to pass ``signature_version`` to EndpointCreator's ``create_endpoint`` method.
When ``get_endpoint`` is called from Service objects, it will pass in its signature version to ``create_endpoint``. That is required for the CLI's ``--no-sign-request`` flag to work because the handler changes the service object's signature version.
I will be sending a PR out real soon for the CLI, that will add a test to catch that --no-sign-request is adhered to.
> Add option to specify endpoint's signature version

- botocore/auth.py
- tests/unit/auth/test_signers.py
We were previously sorting by first creating a list of strings
of `'%s=%s' % (key, value)`.  But really we should be:
1. Sorting by key names
2. In the case of repeated keys, sort then by values.
Fixes aws/aws-cli#976
Added unit tests.  Also verified the previously failing CLI command now works:
```
$ aws cloudsearchdomain search --endpoint-url myendpoint --search-query 'George Lucas' --query-options '{"defaultOperator": "and", "fields":["directors^10"]}' --query hits.hit[].fields.[title[0],rating[0]] --output table
---------------------------------------------------------
|                        Search                         |
+------------------------------------------------+------+
|  Star Wars                                     |  8.7 |
|  Star Wars: Episode III - Revenge of the …
```
> Fix canonical query string sorting for Signature Version 4

- botocore/serialize.py
- tests/unit/protocols/input/rest-json.json
- tests/unit/protocols/input/rest-xml.json
This changes our date serialization to
use an IMF-fixdate timestamp in headers for the rest serializers.
RFC 7231 describes the preferred date-time format in HTTP messages as an
IMF-fixdate timestamp. This timestamp format is a subset of the format
described in RFC 5322 except the format always used a fixed timezone offset of
"GMT". S3 also uses this timestamp format in their documentation and in the
response headers they return.
> Use GMT for timestamp format

- botocore/waiter.py
- tests/unit/test_waiters.py
While pulling in https://github.com/boto/botocore/pull/437,
I noticed that we aren't handling the 'error' matcher properly
because of a CLI customization that will raise an error on
non 200 responses.  This handles that case so, for example, the
command
`aws rds wait db-instance-deleted --db-instance-identifier foo`
will work as expected.  Previously, the error was being propogated
and the CLI command would exit with a non-zero RC and a client error
message.
> Add compat for legacy operation methods on waiters

- botocore/awsrequest.py
- tests/unit/test_awsrequest.py
Most servers (including S3) will just return the CLRF after the 100
continue response.  However, some servers (I've specifically seen this
for squid when used as a straight HTTP proxy) will also inject a
Connection: keep-alive header.  To account for this we'll read until we
read '\r\n', and ignore any headers that come immediately after the 100
continue response.
Fixes aws/aws-cli#1116
I've also added an additional commit, https://github.com/jamesls/botocore/commit/7ca5d35c1b3af2872d16800eb7a3fceefcf1e863, that cleans up the pep8 formatting.
> Account for squid proxy adding unexpected headers

- botocore/data/aws/elasticache/2014-09-30.waiters.json
This adds 4 new waiters i've needed recently. I've used the same delays/attempts as RDS, which works for me quite well so far.
> Add waiters for elasticache

- botocore/parsers.py
- tests/unit/test_parsers.py
For rest-json, we should handle the case where
the keys can come back as either code/Code and
message/Message.
> Handle capitalized keys in error responses

- botocore/compat.py
- botocore/endpoint.py
- tests/integration/test_smoke.py
We need to ignore warnings about missing SAN's in SSL certs
in py26.  This is due to a python bug and we have to validate
using the CN.
These actually were caught by AWS CLI integ tests.  Given they're
warnings, they don't actually cause anything in botocore to hard
fail, whereas the CLI is very sensitive to what shows up in stdout
and stderr which explains why the CLI tests are more likely to
catch this.
I've also updated our integ smoke tests in botocore.  We now will
also verify that the smoke tests generate no warnings.  This will
catch any regressions against this issue.
> Fix failing integ tests due to requests/urllib3 upgrade

- botocore/endpoint.py
- tests/unit/test_endpoint.py
This prevents a value of None from ever being returned
from make_request.  Previously, exceptions were caught and
after the retry logic would just return a value of None.
Now, if things like `ConnectionError`s, `socket.error`s, etc.
are raised, then this will propogate.  This also fixed the
client interface that expected that a tuple was always returned
from `make_request`.  This is now the case.
Noticed this while working on another bug fix.  Now instead
of:
```
File "t.py", line 10, in <module>
ContentDisposition="attachment; filename=5小時接力起跑.jpg;")
File "botocore/botocore/client.py", line 292, in _api_call
operation_model, request_dict)
TypeError: 'NoneType' object is not iterable
```
you'll get:
```
File "t.py", line 10, in <module> …
```
> Let exceptions propogate from make_request

- botocore/awsrequest.py
- botocore/endpoint.py
- tests/integration/test_s3.py
- tests/unit/test_awsrequest.py
> Correctly handle non-ascii header values

- tests/integration/test_ec2.py
- tests/integration/test_kinesis.py
- tests/integration/test_s3.py
- tests/integration/test_waiters.py
This tags the slowest integ tests we have
(via --with-timer --timer-top-n 50) so that you can quickly
run a subset of integration tests.
If I now run "nosetests -a '!slow' tests/integration", the run
takes only 3 minutes or so, which cuts the runtime in half.
Here's the list of the slowest tests:
```
tests.integration.test_ec2.TestCopySnapshotCustomization.test_can_copy_encrypted_snapshot: 198.5485s
tests.integration.test_ec2.TestCopySnapshotCustomization.test_can_copy_snapshot: 114.1209s
tests.integration.test_waiters.TestWaiterForDynamoDB.test_create_table_and_wait: 20.6681s
tests.integration.test_waiters.TestWaiterLegacy.test_create_table_and_wait: 20.2473s
tests.integration.test_kinesis.TestKinesisListStreams.test_can_put_stream_blob: 11.4781s …
```
> Add slow tags to ~ top 15 slowest tests

- botocore/operation.py
The `with threading.Lock()` statement does not actually lock
anything because we're creating a new lock each time.  The
fix here is to use an instance level lock.  We need to ensure that
the signer is not called in multiple threads as it is _not_ thread
safe.
This bug surfaces via S3 signature version 4 multithreaded uploads.
If you run "aws s3 cp/sync" in eu-central-1 or cn-north-1, you'll
see signature errors because the timestamp will be off be one or more
seconds.  Given this is a race condition, you'll need a fairly large
file (1GB to be safe) to see this issue.
Introduced in v0.86.0 of botocore (v1.7.5 of the AWS CLI).
cc @danielgtaylor @kyleknap
> Use class instance to lock signing

- botocore/handlers.py
- tests/unit/test_handlers.py
We were making an assumption that the member names were always
in the response, but in the case of ListPolicyVersions the
'Document' key is _not_ in the response.
Before you'd just get:
```
$ aws iam list-policy-versions --policy-arn 'arn:aws:iam::asdf:policy/AdministratorAccess-asdf'
u'Document'
```
> Fix error with parsing iam policies response

- botocore/client.py
- botocore/endpoint.py
- botocore/operation.py
- tests/integration/test_sts.py
- tests/unit/test_endpoint.py
This ensures that user's region is not overwritten by the credentialScope if the user supplies an endpoint url. This is needed to be able to make signed calls to STS regionalized endpoints, without getting auth errors due to incorrect region . So for example, in the CLI, to make a GetSessionToken call to us-west-2 you would do:
```
$ aws sts get-session-token --region us-west-2 --endpoint-url https://sts.us-west-2.amazonaws.com
```
Before, this would cause a signing error if signed with sigv4 because the credentialScope was set to ``us-east-1`` and that overrode the region that you provided.
> Prevent override of region when using endpoint_url

- botocore/endpoint.py
- tests/unit/test_endpoint.py
Fixes #420
Also fixes aws/aws-cli#961
Closes #460
This fixes the issue by extracting out the logic for converting
a request_dict that we get from a serializer to an AWSRequest object
that's used by requests.  This also lets have have more
specific tests for this functionality.
> Support URL paths in an endpoint_url

- botocore/auth.py
- botocore/awsrequest.py
- botocore/operation.py
- tests/unit/auth/test_signers.py
- tests/unit/auth/test_sigv4.py
This includes making it thread safe for clients and operation objects. Also removed the locking for signing in operation objects since it is not needed anymore.
To do this, I removed the shared utcnow() state and added a ``context`` attribute to ``AWSRequest`` where a timestamp can be assigned when doing the signing. The timestamp attached to the request is set every time at the beginning of ``add_auth`` and other sigv4 signing helper functions then rely on the request's timestamp, that was set at the very beginning of the signing process.
I ran the integration tests for botocore and the CLI to make sure nothing is affected. I also uploaded/downloaded a couple of gigabytes to my ``eu-central-1`` s3 bucket using the s3 commands to further ensure nothing was affected.
Fixes …
> Make the sigv4 signer thread safe

- botocore/awsrequest.py
- tests/unit/test_awsrequest.py
As per the HTTP RFC, the reason phrase is intended for the
human user and the "client is not required to examine or
display the Reason-Phrase...they MAY be replaced by local
equivalents without affecting the protocol."
This isn't an issue for S3, but allows for better interop
for other services.
> Don't check for reason phrase in 100 continue response

- botocore/parsers.py
- tests/unit/test_parsers.py
Right now you'll get a vague message about invalid
syntax if we can't parse the XML for whatever reason.
Now, we catch this error and raise a specific exception that
also includes the XML body so a user can see why we couldn't parse
the exception.
BTW, this happens when:
* You provide an invalid endpoint-url.  Sometimes you might get some
boiler plate HTML from a site which will trigger this exception.
* There are some cases are XML parser can't handle when we get
invalid XML.  While the end goal is to handle these cases, we
should at least be providing a better error message when this
isn't the case.
> Show XML body when unable to parse XML

- botocore/endpoint.py
- botocore/utils.py
- tests/integration/test_client.py
- tests/unit/test_endpoint.py
- tests/unit/test_s3_addressing.py
- tests/unit/test_utils.py
Otherwise, we'll try to make a request with an invalid hostname
which will either fail at the http layer, or even worse, may
generate invalid signatures if the endpoint_url mistakenly has
an endpoint url.
This can also happen sometimes because of misconfigured region
values in the config file.
> Validate that endpoint url has a valid hostname

- botocore/paginate.py
- tests/unit/test_paginate.py
Fixes ``build_full_result()`` for clients.
Before this would happen:
```
>>> import botocore.session
>>> session = botocore.session.get_session()
>>> client = session.create_client('s3')
>>> paginator = client.get_paginator('list_objects')
>>> pages = paginator.paginate(Bucket='mybucketfoo')
>>> pages.build_full_result()
File "<stdin>", line 1, in <module>
File "botocore/paginate.py", line 215, in build_full_result
for _, page in self:
ValueError: too many values to unpack
```
Now this lists all of my objects.
Note that I only included that one unit test for clients to have a smoke test even though operation objects have much more tests. I was considering switching all of the operation object pagination test to clients, but I was hesitant to do that …
> Fix build_full_result for clients

- botocore/model.py
- tests/unit/test_model.py
This makes it so that given a reference to an operation model, you can access its parent object.  Otherwise, existing code needs to track the service model when needed, despite the fact that it's accessible via an internal attribute on the operation model.
This is also needed as part of the client switchover work in the CLI.
> Add service_model property to operation_model

- botocore/session.py
- tests/integration/test_session.py
- tests/unit/test_session.py
Clients did this, but not session.get_service_model.
Need this in the the CLI refactor, otherwise the model doesn't know the "service name" to use to create the client when endpoint_prefix != service_name.
> Add service_name when using get_service_model

- botocore/paginate.py
- botocore/session.py
- tests/unit/test_paginate.py
- tests/unit/test_session.py
This pretty much provides a parallel to the ``WaiterModel`` in waiters.py and ``session.get_waiter_model()`` for paginators. It is pretty light-weight right now. We can add to this as we see needed.
> Added a PaginatorModel

- botocore/endpoint.py
- botocore/exceptions.py
- botocore/operation.py
- botocore/regions.py
- botocore/signers.py
- tests/unit/test_regions.py
- tests/unit/test_service.py
Currently, if no region is configured, you get a vague error message that isn't very clear:
```
In [1]: s.create_client('ec2')
UnknownEndpointError: Unable to construct an endpoint for ec2 in region None
```
Now, if the endpoint heuristics fail and there's no region name you'll get a `NoRegionError`:
```
In [1]: s.create_client('ec2')
NoRegionError: You must specify a region.
```
This also translates to better error messages in the CLI:
BEFORE:
```
$ aws ec2 describe-instances
Unable to construct an endpoint for ec2 in region None
```
AFTER:
```
$ aws ec2 describe-instances
You must specify a region. You can also configure your region by running "aws configure".
```
One of the other changes I made was to remove the `env_var` value from the NoRegionError.  From the commit message:
> First, …
> Raise more specific exception when no region is configured

- botocore/credentials.py
- tests/integration/test-credentials
- tests/integration/test_credentials.py
- tests/unit/test_credentials.py
This changes the behavior of environment variable credential loading to
function as described in aws/aws-cli#113. Here is what this looks like
for both the CLI and Botocore/Boto 3:
CLI:
```bash
$ AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar aws s3 ls
$ AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar aws --profile dev s3 ls
```
Python:
```python
$ AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar python
>>> import boto3
>>> boto3.setup_default_session(profile_name='dev')
>>> # The following will use the profile, not the env vars!
>>> s3dev = boto3.resource('s3')
```
Added a test and a new log message to ensure it's obvious what is happening.
> Explicit profile overrides environment variables

- botocore/operation.py
- botocore/service.py
- botocore/session.py
- tests/unit/test_deprecations.py
I only added them to the most common methods used in botocore
with the old interface.
Later we'll change these to deprecation warnings, but for now,
we'll use PendingDeprecationWarning so you have to opt in.
```
$ python
>>> import botocore.session
>>> s = botocore.session.get_session()
>>> s.get_service('ec2')
Service(ec2)
$ python -Wd
>>> import botocore.session
>>> s = botocore.session.get_session()
>>> ec2 = s.get_service('ec2')
session.py:559: PendingDeprecationWarning: get_service is deprecated and will be removed.  Use create_client instead.
"Use create_client instead.", PendingDeprecationWarning)
service.py:230: PendingDeprecationWarning: get_service is deprecated and will be removed.  Use Session.create_client instead.
PendingDeprecationWarning)
>>> endpoint = …
```
> Add pending deprecations to old style interface

- botocore/serialize.py
- tests/unit/protocols/input/rest-xml.json
If a parameter was a payload and that was something empty like an empty dictionary, it would get serialized to an empty body but really needs to get serialized to an empty xml structure. This caused issues when trying to turn off logging or notification for s3. Here is an example of what happens:
```
>>> import botocore.session
>>> session = botocore.session.get_session()
>>> s3 = session.create_client('s3')
>>> s3.put_bucket_logging(Bucket='mybucket', BucketLoggingStatus={})
File "<stdin>", line 1, in <module>
File "botocore/client.py", line 187, in _api_call
return self._make_api_call(operation_name, kwargs)
File "botocore/client.py", line 242, in _make_api_call
raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An …
```
> Fix issue with rest-xml serialization

- botocore/client.py
- botocore/handlers.py
- tests/integration/test_ec2.py
- tests/unit/test_handlers.py
This handler still relied on operation objects, which no
longer works with the client switchover.
As part of this change, I switched over the test_ec2 integ
tests over to clients.
> Fix copy_snapshot handler to work with clients

- botocore/model.py
- tests/unit/test_model.py
This change will make it much easier to test documentation, e.g. given
this structure expect this output. Order matters for this use case.
cc @jamesls, @kyleknap
> Allow using OrderedDict for structure builder.

- botocore/serialize.py
- tests/unit/protocols/input/rest-json.json
We were not serializing blobs for rest-json. We just dumped the entire json body into the body with no serialization. Now it follows the serialization code path for the JSON serializer.
> Serialize blobs as base64 strings for rest-json

- botocore/data/aws/rds/2014-10-31.waiters.json
`aws ec2 wait` has `snapshot-completed` command, but `rds wait` didn't have its counterpart.
http://docs.aws.amazon.com/cli/latest/reference/ec2/wait/snapshot-completed.html
```
$ aws rds create-db-snapshot --db-instance-identifier db-id --db-snapshot-identifier foo
$ aws rds wait db-snapshot-completed --db-snapshot-identifier bar # For 404:DBSnapshotNotFound snapshot-id, wait command exits.
$ aws rds wait db-snapshot-completed --db-snapshot-identifier foo
... wait till db-snapshot completes.
```
This is an API change, so creating new API files(including dates) may be required, but release management is  out of my control.
This PR just tries to demonstrate if this feature is put into production, how changes should be made.
> support `aws rds wait db-snapshot-completed`

- botocore/parsers.py
- tests/unit/protocols/output/ec2.json
- tests/unit/protocols/output/query.json
- tests/unit/protocols/output/rest-xml.json
- tests/unit/response_parsing/xml/responses/ec2-create-network-interface.json
- tests/unit/response_parsing/xml/responses/ec2-create-volume.json
- tests/unit/response_parsing/xml/responses/ec2-describe-addresses.json
- tests/unit/response_parsing/xml/responses/ec2-describe-instances.json
- tests/unit/response_parsing/xml/responses/ec2-describe-network-interfaces.json
- tests/unit/response_parsing/xml/responses/ec2-describe-snapshots.json
- tests/unit/response_parsing/xml/responses/ec2-describe-tags.json
- tests/unit/response_parsing/xml/responses/ec2-import-instance.json
- tests/unit/response_parsing/xml/responses/ec2-import-volume.json
- tests/unit/response_parsing/xml/responses/ec2-request-spot-instances.json
- tests/unit/response_parsing/xml/responses/ec2-run-instances.json
- tests/unit/response_parsing/xml/responses/elasticbeanstalk-create-configuration-template.json
- tests/unit/response_parsing/xml/responses/elasticbeanstalk-describe-configuration-options.json
This changes the output of the XML-based parsers and adds protocol tests for
each of `query`, `ec2`, and `rest-xml`. This is required to support new
waiters as in aws/aws-cli#1252.
cc @jamesls @kyleknap do either of you know why the code had a custom string
handler? Everything seems to work fine without it and removing it fixes the CLI
bug linked above.
> Parse empty XML string nodes as an empty Python string

- README.rst
- botocore/exceptions.py
- botocore/operation.py
- botocore/service.py
- botocore/session.py
- docs/source/client_upgrades.rst
- docs/source/index.rst
- tests/unit/test_deprecations.py
I noticed when I was trying out the old interface that the `DeprecationWarning` does *not* print to stderr.  We really should be at the point out where the error is front and center whenever you try to do anything with the old interface.  This change does that.
In order to help with migration I also sketched out a migration guide for going from the old interface to the new client interface so we have something we can point customer to when they run into issues.
I also manually verified the errors are on stderr now:
```
>>> import botocore.session
>>> s = botocore.session.get_session()
>>> s.get_service('ec2')
botocore/session.py:560: ImminentRemovalWarning: get_service is deprecated and will be removed.  Use create_client instead.
"Use create_client instead.", ImminentRemovalWarning) …
```
> Old style interface should warn to stderr by default

- botocore/session.py
- tests/unit/test_base.py
- tests/unit/test_session.py
This standards the environment variables used in botocore.session to be consistent with other SDKs.  This includes two things:
1. Support `AWS_PROFILE` and `AWS_REGION` (the former is from aws/aws-cli#1281)
2. Change the default `BOTO_` env vars to use `AWS_` instead.
This is a backwards incompatible change, but there is a mitigation path is customers do in fact want the old mapping.  They can provide the old env var mapping to the `__init__` when creating a session.
> Standardize env vars to use AWS_ prefix

- tests/integration/test_smoke.py
This adds basic smoke tests for the services added in the last
6 months or so.
cc @kyleknap
> Add integration tests for new services

- botocore/data/aws/_retry.json
This changes two things:
* Move the ``throttling_exception`` rule up to the default errors to retry
* Move the ``throttling`` rule up to the default errors to retry
This came about because the ``workspaces`` service would receive
400/ThrottlingException errors that were not being retried.
The simple fix would be to add this missing condition to a new
``workspaces`` entry.
However, the error can occur for any json or rest-json service and
we'd need to keep this up to date every time we added support for a new
json/rest-json service.  Same thing with the 400/Throttling exception.
This will happen for any query service.  Moving this up to the default
set of errors to retry means we won't have to keep updating this as new
errors are added.
It also has the benefit that the remaining …
> Simplify retry configuration

- botocore/paginate.py
- tests/unit/test_paginate.py
The issue is we need to stop paginating if we recieve an empty string for
a next token marker. Before, if we did not have a check to see that the next
token was not the same as the previous token and throw an error, we would have
hit an infinite loop.
> Fix pagination issue

- botocore/model.py
- botocore/parsers.py
- botocore/utils.py
- tests/unit/test_utils.py
Speeds up botocore quite a bit when making repeated calls
to the same operation, e.g. dynamodb.get_item().
The main area of improvement was due to the fact that the operation models were not being cached so repeated calls to `get_item` would result in the op model being recreated each call.  This meant that even though the operation model itself would cache things like the input/output shape, that had no effect because we were throwing away the operation model afterwards.
The other thing that profiling showed was that the pformat() call was slowing things down.  This is still useful information so rather than `pformat()` we're just logging the header dict directly.
This gives performance that's on par with boto2.
cc @kyleknap
> Improve repeated method calls in botocore

- botocore/paginate.py
- tests/integration/test_ec2.py
- tests/integration/test_route53.py
- tests/integration/test_s3.py
- tests/unit/test_paginate.py
Took all pagination related parameters and camel cased them and wrapped them into an overlying structure, PaginationConfig. Before, a pagination call looked something like this:
```
paginator.paginate(max_items=1)
```
Now it looks like this:
```
paginator.paginate(PaginationConfig={'MaxItems': 1})
```
Other parameters that are included in PaginationConfig are MaxItems, PageSize, and
StartingToken. Their snake cased versions are no longer used.
I will have subsequent pull requests that will update the CLI and boto3 as well.
> Update paginate parameters

- botocore/validate.py
- tests/unit/test_validate.py
Fixes aws/aws-cli#1366
Before you'd get:
```
$ aws ec2 describe-spot-price-history --cli-input-json file:///tmp/json
'NoneType' object has no attribute 'read'
```
Now you'll get:
```
$ aws ec2 describe-spot-price-history --cli-input-json file:///tmp/json
Parameter validation failed:
Invalid type for parameter StartTime, value: None, type: <type 'NoneType'>, valid types: <type 'datetime.datetime'>, timestamp-string
Invalid type for parameter EndTime, value: None, type: <type 'NoneType'>, valid types: <type 'datetime.datetime'>, timestamp-string
```
> Provide better error message when timestamps are None

- botocore/paginate.py
- tests/unit/test_paginate.py
This commit adds the `search()` method to PageIterator (implementing a flatmap on top of a paginator).
Each page of results is searched using the provided JMESPath expression. If the result is not a list, it is yielded directly. If the result is a list, each element in the result is yielded individually (essentially implementing a flatmap in which the JMESPath search is the mapping function).
```python
import botocore.session
session = botocore.session.get_session()
client = session.create_client('s3', region_name='us-east-1')
paginator = client.get_paginator('list_objects')
it = paginator.paginate(Bucket='my-bucket')
for element in it.search('Contents[*].[Key, Size]'):
print(element)
```
Running the above example will create a generator that yields lists containing the keys and sizes of …
> Adding search method to `PageIterator`

- setup.py
Verify with:
```
<mkvirtualenv with python2.6>
pip install pip==1.4.1
<create botocore and awscli sdists>
pip install botocore/dist/<sdist>.tar.gz
pip install awscli/dist/<sdist>.tar.gz
aws --version
```
> Fix regression in older versions of pip with cond deps

- botocore/handlers.py
- tests/functional/test_machinelearning.py
- tests/unit/test_handlers.py
Fixes the issue brought up in the forums:
https://forums.aws.amazon.com/thread.jspa?threadID=182689&tstart=0 
We have tests for machinelearning in the CLI but that mocks out the ``make_request`` method of the endpoint so the handler for machine learning was never called.
> Fix issue with machinelearning predict

- botocore/docs/utils.py
- botocore/handlers.py
- tests/functional/docs/__init__.py
- tests/functional/docs/test_autoscaling.py
- tests/functional/docs/test_ec2.py
- tests/functional/docs/test_s3.py
- tests/unit/docs/test_utils.py
This commit adds two new customization classes:
1. HideParamFromOperations - hides a parameter from one or more
operations.
2. AppendParamDocumentation - appends documentation to a parameter.
Documentation customizations have been added for each customization
listed in handlers.py.
@kyleknap @jamesls
> Adding documentation customizations.

- tests/__init__.py
- tests/integration/test_client.py
- tests/integration/test_cloudformation.py
- tests/integration/test_cognito_identity.py
- tests/integration/test_elastictranscoder.py
- tests/integration/test_glacier.py
- tests/integration/test_kinesis.py
- tests/integration/test_s3.py
- tests/integration/test_utils.py
- tests/integration/test_waiters.py
Fixes occasional integ test failures.
Removed all calls to `random.random` in integ tests.
> Use more random random names

- botocore/exceptions.py
- botocore/session.py
- docs/source/index.rst
- tests/unit/test_handlers.py
- tests/unit/test_session.py
This is primarily to address #395, where the `metadata_*` variables need to be converted to integers.
To fix this, the session var mappings now have an additional field, which is a conversion function, which if provided, will be called before returning the value in `get_config_variable`.
The main change is provided in https://github.com/boto/botocore/commit/b0ea7bc62550665488a69ca0beeb9a240f249c50.  I've also included a number of commits for code cleanup to the session module.
Additionally, I've made one change to the signature of `get_config_variable` which is to remove the `default` argument.  This simplifies the code logic, and nothing in botocore, the cli, nor boto3 used this functionality.  I'd prefer to remove this until there's a strong case for adding this back.  It also …
> Allow config variables to provide conversion functions

- botocore/docs/bcdoc/style.py
- tests/unit/docs/bcdoc/test_style.py
There was an issue where if text was written directly after a paragraph
it would be misaligned. This specifically fixes issues with the
route53 and route53domains docs.
Here is an example of this misalignment currently:
Here is how it looks like with this pr:
Notice that the period is still there but it is aligned properly.
> Fix paragraph indentation

- botocore/docs/bcdoc/restdoc.py
- botocore/docs/example.py
- tests/unit/docs/bcdoc/test_document.py
- tests/unit/docs/test_example.py
This fixed the formatting issues where an empty method call/structure had
the starting and ending parenthesis/bracket on separate lines.
It currently looks like this:
The PR changes it to be like this:
> Add functionality for shapes with no members

- botocore/docs/client.py
- botocore/docs/method.py
- botocore/signers.py
- tests/unit/docs/test_method.py
Also, extracted logic to new method and fixed a doc string in the presigner methods.
The old documentation looked like this:
The new documentation looks like this:
The main difference being the docstring is fixed on the returns and there is no more paragraph block surrounding the summary of the doc string.
> Fix custom method documentation

- botocore/parsers.py
- tests/unit/test_parsers.py
Fixes #532.
The error message will now look like:
```
ClientError: An error occurred (InvalidInput) when calling the ListResourceRecordSets operation:
```
> Always populate a 'Message' key in the errors dict

- botocore/docs/method.py
- tests/unit/docs/test_client.py
- tests/unit/docs/test_method.py
- tests/unit/docs/test_paginator.py
- tests/unit/docs/test_service.py
- tests/unit/docs/test_waiter.py
Ensures if a model driven parameter requires parameters, it is represented as ``**kwargs`` in the method signature. The purpose of doing this is to make the method signatures less cluttered. Note that non-data driven methods still use their method signature.
Here is what it looked before:
Here is what it looks after:
> Use **kwargs for method signatures

- botocore/auth.py
- botocore/handlers.py
- botocore/serialize.py
- tests/integration/test_s3.py
- tests/unit/auth/test_signers.py
- tests/unit/auth/test_sigv4.py
- tests/unit/test_handlers.py
- tests/unit/test_protocols.py
- tests/unit/test_serialize.py
- tests/unit/test_signers.py
This is more general change to handle how we handle blob types in general.
There's 4 possible types that a user could give us for a blob type that would pass validation:
* text type (str/unicode)
* bytes type (bytes())
* binary file obj
* text file obj
This PR updates botocore such that the first three cases are handled.  The fourth case could be something we support down the road, but it's easy enough for now to just open the file as binary.
It's also a somewhat difficult because we can't reliably tell if a file like object is opened as text.
To accomplish this, I picked up the work down a few months ago to standardize on the input types for serialization such that the *request dict body is always `bytes()`*.
> Fix put_object when body is a bytes

- botocore/session.py
This param isn't actually used anymore.
This will require an update to the CLI tests, as there are a few
places where it's still passing a loader to the session.
> Remove loader param from session

- botocore/docs/bcdoc/restdoc.py
- botocore/docs/bcdoc/style.py
- botocore/docs/client.py
- botocore/docs/example.py
- botocore/docs/params.py
- tests/unit/docs/bcdoc/test_document.py
- tests/unit/docs/bcdoc/test_style.py
- tests/unit/docs/test_example.py
This pull request is needed for the impending boto3 pull request. It pretty much involves adding a few more methods/attributes to the ``DocumentStructure`` class. The functionality added includes:
* a ``remove_all_sections()`` method that removes all subsections
* a ``clear_text()`` method that clears all of the text for a section, but does not erase the text in subsections.
* a ``meta`` attribute that allows you to store extra data about a section.
* a way to document python attributes in bcdoc.
There is also some logic in recording the shape that represents a section via the new ``meta`` attribute. This is useful for documenting the dynamodb customizations in boto3.
I tried to extract out the commits the best I can to give you a better sense of every change that is made. Might be better …
> Boto3 doc update

- botocore/session.py
- tests/unit/test_session.py
So we can continue to keep boto3 code simple such as: https://github.com/boto/boto3/blob/develop/boto3/session.py#L84-L89
> Fall back to get_config_variable() in profile property

- docs/source/tutorial/index.rst
- setup.py
There's a few additional things we need to change:
* Change trove classifiers to stable
* Remove dev preview warning from tutorial.
The tutorial/getting started guide could use some sprucing up, but we can address that in a separate PR.
> Remove all beta/dev preview warnings

- botocore/data/route53/2013-04-01/waiters-2.json
This will wait until JMESPath query ChangeInfo.Status returns INSYNC when polling with get-change.
Solves feature request aws/aws-cli#1106
http://docs.aws.amazon.com/Route53/latest/APIReference/API_GetChange.html
For valid change id, `ChangeInfo.Status` can return  `PENDING` or `INSYNC`.
For invalid change id, code `NoSuchChange` is returned.
```
<?xml version="1.0"?>
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>NoSuchChange</Code><Message>Could not find resource with ID: C15RYMEZ8RZJFM</Message></Error><RequestId>a721689b-007b-11e5-9fb7-cfa489e06a9c</RequestId></ErrorResponse>
```
I handled this case as success just like other waiters.
```
$ cat mx.json
{
"Comment": "Adding a new MX record for the zone.",
"Changes": [
{
"Action": …
```
> `aws route53 wait` now supports ResourceRecordSetsChanged.

- botocore/data/machinelearning/2014-12-12/waiters-2.json
machinelearnig's create operations are basically asynchronous but there's no wait commands, so I've added following wait commands.
* DataSourceAvailable:
Wait until JMESPath query Results[].Status returns COMPLETED for all elements when polling with describe-data-sources.
Useful for `aws machinelearning create-data-source-from-s3` operation.
* MLModelAvailable:
Wait until JMESPath query Results[].Status returns COMPLETED for all elements when polling with describe-ml-models.
Useful for `aws machinelearning create-ml-model` operation.
* EvaluationAvailable:
Wait until JMESPath query Results[].Status returns COMPLETED for all elements when polling with describe-evaluations.
Useful for `aws machinelearning create-evaluation` operation.
* BatchPredictionAvailable:
Wait until JMESPath query …
> Add machinelearning wait commands

- botocore/docs/utils.py
- botocore/handlers.py
- tests/functional/docs/test_autoscaling.py
- tests/functional/docs/test_ec2.py
This commit updates the UserData docs to be more clear that you should not base64 encode the value when providing the parameter. The text is now bold to make it more pronounced.
Also added a minor typo fix for the default AutoPopulatedParam description.
Closes #585 
@jamesls @kyleknap
> Making UserData docs more clear about base64

- docs/source/conf.py
- requirements-docs.txt
Also adding logo-text.html to left nav.
The latest version of the theme has a ton of style fixes, including:
- Breadcrumbs are no longer hidden on a small device.
- Left nav elements are smaller.
- Left nav headers are smaller.
- text logo is now styled to better call it out.
- reduced padding in the main content section.
- admonitions are more subtle.
- p tags no longer have a top margin of 1.2 em (making them act like normal p tags you see everywhere else)
- h1's are more subtle
And most importantly, parameters inside of field-lists are now rendered in html as dt and dl tags. This makes long nested documentation no longer overflow due to table styling issues, and reduces the time render large pages significantly because the dom size is not having to be recalculated for ever table. …
> Updating to latest version of theme.

- botocore/utils.py
- tests/unit/test_translate.py
- tests/unit/test_utils.py
Allows user to append to lists as opposed to replace lists completely when
merging dictionaries.
This is needed for a subsequent PR to boto3 that fixes an issue in collections.
> Add append_lists option to merge_dicts()

- requirements-docs.txt
This commit updates to the latest version of the Guzzle sphinx theme.
Theme changes:
1. Removed some kerning rules that were not noticeable but caused a significant rendering penalty. This change reduces the time to finish rendering the EC2 page from about 4.6 seconds to about 1.7 seconds.
2. Lightened the left nav border.
3. Added a border between each method and class to better visually distinguish them.
This commit is only really necessary to get readthedocs to update their local package cache.
@kyleknap
> Updating theme version

- docs/source/tutorial/index.rst
The current wording of getting started with botocore makes it seem like there are other ways that developers could use when interacting with botocore. While it's possible to use botocore by creating clients manually without a session, I think we should update the documentation to be more clear that using a session is needed for almost every use case, and using a session is the public API of botocore.
> Making the use of session sound less optional

- botocore/model.py
- tests/unit/test_model.py
This commit updates the shape builders to utilize a new concrete shape
type, StringShape. StringShape exposes a property that makes it easier
to inspect the enum attribute of a string shape. StringShape is the only
concrete shape type to expose this property because, at present, the only
shapes that have the `enum` property are string shapes.
In addition to this feature, the unused `SHAPE_CLASSES` constant has been
deleted from ServiceModel. If removing this constant is not acceptable, I can
put it back and rebase.
> Adding a StringShape and enum attribute

- botocore/parsers.py
- tests/unit/response_parsing/json/expected/elastictranscoder-delete-pipeline.json
- tests/unit/test_parsers.py
According to issue boto/boto3#186, this happens in cloudsearchdomain service and some other services too. This fix is generic for all RestJSON responses.
> RestJSONParser now parses "code" from "__type" field

- botocore/serialize.py
- tests/unit/protocols/input/rest-json.json
- tests/unit/protocols/input/rest-xml.json
There was an issue where if the operation had no input shape, we would not use the modeled URI and just use ``'/'`` because that is the default.
cc @jamesls @mtdowling @rayluo
> Serialize Uri for no input shape

- botocore/session.py
- tests/integration/test_credentials.py
This pulls in https://github.com/boto/botocore/pull/600, and renames the env var to `AWS_SHARED_CREDENTIALS_FILE`.  It also adds an integration test to verify behavior.
Note that there's no actual new code.  It's just changing a config value from None to `AWS_SHARED_CREDENTIALS_FILE`, and that mechanism for the env var->config file->default lookup is already tested.  So it seems reasonable to add an integration test to verify that this specific value was being picked up.
> Support AWS_SHARED_CREDENTIALS_FILE

- MANIFEST.in
When packaging for distributions we sometimes want to include
documentation in the installation (especially on Gentoo).  This adds the
documentation to the sdist so we can use the PyPi distribution and build
the documentation for our users.
> add docs to sdist

- botocore/session.py
I think there's no reason to limit the users from setting `metadata_service_timeout` and `metadata_service_num_attempts` config from  environment variables.
> Use env vars to set metadata service config

- botocore/data/logs/2014-03-28/paginators-1.json
This adds some paginators requested in https://github.com/boto/botocore/issues/613. I've verified them to the best of my ability with the services we use, but we don't have any subscription filters.
GetLogEvents is also strange because, it seems, that on the "last" page the `nextForwardToken` is intentially a self reference which causes botocore to raise `botocore.exceptions.PaginationError: Error during pagination: The same next token was received twice: [u'f/...']` exception.
Let me know what you think!
> Add paginators for CloudWatch Logs

- botocore/serialize.py
- tests/unit/test_serialize.py
I took a crack at fixing #625, adding test cases for the failing case as well as the cases that were working before.
> BaseRestSerializer should handle timestamp headers consistently. fixes #625

- botocore/awsrequest.py
- tests/integration/test_s3.py
- tests/unit/test_awsrequest.py
For some cases like an extracted file from a tar file were not able to
be uploaded because requests did not calculate the content-length despite
the fact that it was seekable. Added logic to calculate and add the content
length header for these types of files.
cc @jamesls @mtdowling @rayluo
> Add content length for seekable files

- botocore/auth.py
- tests/integration/test_s3.py
- tests/unit/auth/test_signers.py
- tests/unit/test_signers.py
This pulls in https://github.com/boto/botocore/pull/597 and adds a few unit tests and an integration test.
> (Updated) Append signature to HmacV1Query querystring instead of replace

- MANIFEST.in
When packaging botocore it's nice to be able to run the tests from the
source distribution to ensure that the packaging has been done
correctly.  This includes the tests directoy in the sdist without
installing it to the system.  Piggy-backed is a change to the docs
inclusion that uses graft rather than recursive-include.
> add tests to MANIFEST.in

- botocore/data/logs/2014-03-28/paginators-1.json
This paginator returns the same token twice to indicate pagination is
done. Botocore treats this as an error, but really we should stop paginating.
So remove this paginator for now until support is added in botocore.
cc @jamesls @mtdowling @rayluo
> Remove GetLogEvents paginator

- botocore/handlers.py
- tests/functional/test_s3.py
- tests/unit/test_handlers.py
Fixes boto/boto3#181
Based on:
http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html#non-dns-compliant-bucketname-challenges
> Add bucket name validation to S3 calls

- botocore/data/cloudfront/2015-04-17/paginators-1.json
- botocore/data/cloudfront/2015-04-17/waiters-2.json
- tests/functional/test_model_completeness.py
These 2 files are now copied from previous version, the 2014-11-06 directory.
Also add a couple test cases to prevent this from happening in future.
> Add back paginator-1.json and waiters-2.json for cloudfront

- tests/__init__.py
- tests/cmd-runner
- tests/functional/leak/__init__.py
- tests/functional/leak/test_resource_leaks.py
This adds several functional and integration tests for verifying that we don't leak memory when performing various botocore operations.  This includes:
* Creating multiple clients.  Verify creating/deleting multiple clients does not cause undesired memory growth.
* Performing various AWS operation does not have undesired memory growth.
* Performing streaming S3 uploads/downloads has constant memory utilization during (and after) the transfers.
The best description of how this works is in the tests/cmd-runner module docstring.
> Add resource leak tests

- botocore/client.py
- botocore/docs/method.py
- botocore/utils.py
- tests/unit/test_utils.py
Includes extracting out the logic that creates the client classes into a public function. This is needed because resource factories in boto3 do not have access to the client's class, and thus its name, when creating the resource class.
There was also some moving around some of the internals of the docstring class to make it easier to inherit from for example:
```py
class ActionDocstring(LazyLoadedDocstring):
def __init__(self, *args, **kwargs):
super(ActionDocstring, self).__init__(*args, **kwargs)
self._docstring_writer = document_action
```
cc @jamesls @mtdowling @rayluo
> Some moderate refactoring for boto3 docstrings

- botocore/response.py
- tests/unit/test_response.py
This will solve pypa/warehouse#676 which is essentially caused by trying to treat the StreamingBody like a file-like object.
> Make the StreamingBody wrapper more file-like with a close() method

- botocore/exceptions.py
- tests/unit/test_exceptions.py
Since we don't have control to field names in upstream services, let's play safe by not assuming any field's existence.
PS: This is a successor of the closed PR https://github.com/boto/botocore/pull/610.
That one was originally developed to address another issue with similar symptom, but then we used another approach to solve the root cause for that one.
Now this one seems still useful as part of the fix for boto/boto3#249. (Similar fix can be found here too. borrows the concept in https://github.com/boto/botocore/pull/647)
> Tolerate missing code or message in error response

- botocore/handlers.py
- tests/integration/test_ec2.py
- tests/unit/test_handlers.py
This can happen in the case of an error.
Fixes boto/boto3#262.
> Account for Output not in response

- botocore/session.py
- tests/unit/test_session.py
Only delete the component from the deferred dict after
successfully creating the object from the factory as well as
injecting the instantiated value into the _components dict.
The bug is that is the factory object raises an exception,
we've already removed it from the deferred list (via the
.pop() call), but we haven't added anything to the _components
dict.
Because of this, the next time you try to make a call you'll
get an error message about an unknown component.
It also looks like there were no unit tests for this class.
It was only tested transitively before.  I've added a set
of unit tests covering this behavior.
This was found while looking into https://github.com/aws/aws-cli/pull/1515
> Don't remove lazy component from deferred until success

- tests/integration/test_smoke.py
If you only want to smoke test a specific service, you can
set an env var to control what services are run:
```
AWS_SMOKE_TEST_SERVICES=autoscaling nosetests tests/integration/test_smoke.py
```
Multiple services can be provided as a csv list.  I picked csv
over space separated so you don't have to quote the env var
value:
```
AWS_SMOKE_TEST_SERVICES=autoscaling,ec2 nosetests tests/integration/test_smoke.py -svx
test_can_make_request_with_client(<AutoScaling>, u'describe_account_limits', {}) ... ok
test_can_make_request_with_client(<AutoScaling>, u'describe_adjustment_types', {}) ... ok
test_can_make_request_with_client(<EC2>, u'describe_instances', {}) ... ok
test_can_make_request_with_client(<EC2>, u'describe_regions', {}) ... ok …
```
> Allow users to specify specific services to smoke test

- botocore/data/_endpoints.json
As a general principle, anything that has a startsWith
constraint should not have a hard coded region name.
Note that there's already existing tests for this: https://github.com/boto/botocore/blob/develop/tests/unit/test_regions.py#L27
> Remove hardcoded uris in endpoint heuristics

- tests/integration/leak/__init__.py
- tests/integration/leak/test_client_leaks.py
Verifies:
* s3 uploads use O(1) memory
* making repeated AWS calls does not leak memory
This was suppose to be included with #638.
> Add integration leak tests

- botocore/waiter.py
- tests/unit/test_waiters.py
Fixes boto/boto3#233
In that specific case, the result now looks like:
WaiterError: Waiter InstanceStopped failed: Request would have succeeded, but DryRun flag is set.
> Added error code and message to unexpected WaiterError

- tests/integration/test_smoke.py
This fixes a bug where we'd default to a set of an empty
string if the AWS_SMOKE_TEST_SERVICES was not provided.
Verified all smoke tests are run and AWS_SMOKE_TEST_SERVICES
still works.
> Run all services if AWS_SMOKE_TEST_SERVICES not provided

- botocore/docs/__init__.py
- botocore/docs/service.py
- docs/source/conf.py
- tests/functional/docs/__init__.py
- tests/functional/docs/test_s3.py
- tests/unit/docs/test_docs.py
- tests/unit/docs/test_service.py
Removed dependency of session from docs package
For example, you no longer get a circular reference from doing this:
```py
from botocore.client import Config
```
> Fix circular reference in docs

- botocore/data/ec2/2015-10-01/waiters-2.json
The "aws ec2 get-console-output" does not immediately
return the console output when you launch a new
EC2 instance.  This adds a waiter so you can block
until this data is available.
This is similar to the PasswordDataAvailable, with the
exception that in this API call, the "Output" element
isn't in the response when there is no output.  So
the JMESPath expression needed to be "Output || ''" to avoid
type errors when calling length().
> Add console-output-available waiter

- botocore/parsers.py
- botocore/serialize.py
- botocore/utils.py
- tests/unit/protocols/input/json.json
- tests/unit/protocols/input/query.json
- tests/unit/protocols/input/rest-json.json
- tests/unit/protocols/input/rest-xml.json
- tests/unit/protocols/output/json.json
- tests/unit/protocols/output/query.json
- tests/unit/protocols/output/rest-json.json
- tests/unit/protocols/output/rest-xml.json
- tests/unit/test_protocols.py
- tests/unit/test_utils.py
This fixed three issues with protocol serialization/parsing:
1. If a struct is returned as `null` across the wire in `json` we should parse that as `None`, not `{}`.
2. If we're serializing to a query string and the value is a map we need to ignore the top level key and pull the map keys up to top level query string params.
3. If a query string *value* is a sequence, we need to serialize it as: `{"a": ["b", "c"]}` -> `a=b&a=c`.
4. Honor locationName in query protocol for non flattened lists.
See commit messages for more details.
> Update serializers/parsers with latest protocol tests

- botocore/parsers.py
- tests/functional/test_s3.py
For the rest-xml error parser, the body of the response had headers of a
200 response even though the http status code was 500. This blew up
of the error parser because it was invalid xml. For these situations, we should
at least respect the error code.
> Make error parsing more robust

- botocore/loaders.py
- tests/unit/data/non_ascii.json
- tests/unit/test_loaders.py
We encountered a test case failure on one of the test machine, when running Python 3.x.
File "C:\Python33\Lib\unittest\case.py", line 385, in _executeTestPart
function()
File "C:\Jenkins\shiningpanda\jobs\263e0464\virtualenvs\d41d8cd9\lib\site-packages\nose\failure.py", line 38, in runTest
raise self.exc_val.with_traceback(self.tb)
File "C:\Jenkins\shiningpanda\jobs\263e0464\virtualenvs\d41d8cd9\lib\site-packages\nose\loader.py", line 254, in generate
for test in g():
File "C:\Jenkins\workspace\botocore-integ\PYTHON\CPython-3.3\tests\integration\test_utils.py", line 33, in test_can_generate_all_inputs
service_model = session.get_service_model(service_name)
File "C:\Jenkins\workspace\botocore-integ\PYTHON\CPython-3.3\botocore\session.py", line 469, in …
> Use utf8 encoding to open model file

- botocore/data/_retry.json
Fix #91 accroding to the document (http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html)
> Add the retry for Route53 when PriorRequestNotComplete happens

- botocore/endpoint.py
We log the traceback for the `except Exception` clause but not for `ConnectionError`s.  Even though the retry handler will reraise this exception, we miss the original stack trace so we can't see where in requests/urllib3 the ConnectionError originated from in python2.
> Log traceback on ConnectionErrors

- botocore/awsrequest.py
- tests/unit/test_awsrequest.py
A connection instance can be reused even if the server
has closed the associated socket.
When this happens, urllib3 will ".close()" the connection
which also closes and deletes the socket associated with
the connection.
However, the AWSHTTPConnection *object* is still reused
in the underlying connection pool.  The HTTP client will
notice that associated socket is None and will create
a new socket thereby establishing a new connection to the
AWS endpoint.
The bug on our end was that we were not properly resetting
our own instance state variables we use to keep track of
if we've sent the expect header, if we've seen a response,
etc.  We were assuming that a connection instance is removed
from the connection pool when the connection and underlying
socket is closed.
As a result, state from …
> Reset HTTP connection state when connection is closed

- botocore/data/cloudsearch/2011-02-01/service-2.json
This is adds an old api version of cloudsearch. You need this to use old cloudsearch domains. I pulled this file from the javascript SDK. It is also formatted as expected.
Fixes https://github.com/boto/boto3/issues/203
> Add back old cloudsearch version

- botocore/handlers.py
- tests/functional/test_cloudsearchdomain.py
This can enable sending a potentially large request to Cloudsearchdomain.
This fixes boto/boto3#211
> Use HTTP POST to send Cloudsearchdomain search operation

- botocore/credentials.py
- botocore/session.py
- tests/functional/test_session.py
- tests/unit/test_credentials.py
Profile should override env var creds
Unless the profile and creds are both specified
as env vars.
In order to fix this regression, I had to make a
small change to session.  This makes the 'profile'
config var less special cased than it was previously.
Now, we always check the _session_instance_vars for
a profile, and simple use _profile as a placeholder
for the cached lookup value of 'profile'.
The only place this gets weird is we need to scope
down our call to ".get_config_variable" in the
credential provider creation to only check the
session instance variables for a profile to determine
whether or not we need to add the EnvProvider to our
lookup chain.
One of the reasons this regressed is we didn't have
sufficient functional tests to cover this behavior.
I've added functional tests …
> Profile should override env var creds

- botocore/data/kinesis/2013-12-02/paginators-1.json
This PR updates the `DescribeStream` paginator for Kinesis to include `StreamDescription.RetentionPeriodHours` in the non aggregate keys. I've verified that this works with the CLI.
@kyleknap @jamesls @rayluo @JordonPhillips
> Adding RetentionPeriodHours to Kinesis non_aggregate_keys

- tests/__init__.py
- tests/functional/leak/test_resource_leaks.py
Avoids the instance metadata timeout during credential lookup.
> Add dummy credentials to functional leak tests

- botocore/paginate.py
- tests/unit/test_paginate.py
Paginator's result_key used to expect list value only.
Now, if a result_key's value is an integer (or a float),
paginator can aggregate them.
> Adds the count ability to paginator

- botocore/__init__.py
- tests/unit/test_utils.py
Given that this is in the critical path for making API calls,
I did some benchmarking to ensure that this doesn't cause any
serious performance issues.  Short answer is that this seems
acceptable.
I timed how long it took to xform every single operation and
top level member name against this branch and the develop
branch.
Given 3034 xform's, I'm seeing:
```
dev branch   - 0.0930128 seconds averaged over 10 runs of 3034
fix-arn-name - 0.0944845 seconds averaged over 10 runs of 3034
```
Or in terms of ops/sec:
```
before - 32619.2 ops/sec
after  - 32111.1 ops/sec
```
The reason I think this should be generalized is that some
services use this pattern for particular types of resources
(mostly ACLs and ARNs), and we'll need to possibly update
our special cases every time we pull in a service …
> Generalize special casing of pluralized acronyms

- botocore/serialize.py
- tests/integration/test_apigateway.py
- tests/integration/test_smoke.py
- tests/unit/protocols/input/rest-json.json
We were not respecting ``locationName`` for JSON protocols, which caused issues with API Gateway's ``PutIntegration`` operation's [integrationHttpMethod](https://github.com/boto/botocore/blob/develop/botocore/data/apigateway/2015-07-09/service-2.json#L4133) which uses ``locationName``.
Fixes https://github.com/aws/aws-cli/issues/1605
> Respect locationName for JSON Protocols

- botocore/handlers.py
- tests/functional/docs/test_s3.py
- tests/integration/test_s3.py
- tests/unit/test_handlers.py
This is implementing logic used for this PR: https://github.com/aws/aws-cli/pull/1487. We have it for SSECustomer members but not the copy source one which may be needed when calling CopyObject.
> Autopopulate CopySourceSSECustomerKeyMD5 for s3

- README.rst
1) It's reporting wrong coverage numbers
2) We've already removed it in boto3
For reference: https://github.com/boto/boto3/pull/284
> Remove coveralls.io badge

- botocore/paginate.py
- tests/unit/test_paginate.py
This is built on top of PR #689, and fixes issue aws/aws-cli#1365
I also manually test it with this command line to make sure it solves the issue.
aws rds download-db-log-file-portion --db-instance-identifier mydbinstance --log-file-name error/mysql-error-running.log --starting-token 1000
A couple previous test cases have also been adjusted a little bit. Their previous default value as list is no longer considered as proper anyway.
> Now can resume from an empty first page

- botocore/compat.py
- botocore/credentials.py
- tests/unit/test_credentials.py
Also provides better message to customer. This will resolve aws/aws-cli#708
Did not patch RefreshableCredentials, because it is less error-prone.
> Detect non-ascii in credential

- botocore/compat.py
- botocore/credentials.py
- tests/unit/test_credentials.py
It happens when the credential comes from iam-role.
> Skip convertion if the input is already unicode

- botocore/data/kinesis/2013-12-02/waiters-2.json
The `aws kinesis delete-stream` does not immediately
delete the stream. This adds a waiter so you can block
until the stream is unavailable(i.e.,
`aws kinesis describe-stream` returns `ResourceNotFoundException`).
First, create a Kinesis stream
```
$ aws kinesis create-stream --stream-name Foo --shard-count 1
$ aws kinesis wait stream-exists --stream-name Foo
$ aws kinesis describe-stream --stream-name Foo
{
"StreamDescription": {
"RetentionPeriodHours": 24,
"StreamStatus": "ACTIVE",
"StreamName": "Foo",
"StreamARN": "arn:aws:kinesis:ap-northeast-1:123456789012:stream/Foo",
..snip...
}
}
```
Then delete the Kinesis stream `foo`.
```
$ aws kinesis delete-stream  --stream-name Foo
$ aws kinesis describe-stream --stream-name Foo
{
"StreamDescription": {
"RetentionPeriodHours": 24, …
```
> Add Kinesis stream-not-found waiter

- tox.ini
It now matches boto3: https://github.com/boto/boto3/pull/353 where the ci scripts are used instead of some separate logic.
> Update tox to use the ci scripts

- botocore/signers.py
- tests/unit/test_signers.py
Do not cache signers that have an expires value. This commit supersedes #699
This commit updates the signer cache to not cache signers that have an
expires value because the cache hit ratio for these signers will be
virtually 0 as the key would have to be derived from a timestamp.
This change should address several existing issues:
- Closes #699
- Closes #698
- Probably fixes https://github.com/boto/boto3/issues/309
@jamesls @kyleknap @rayluo @JordonPhillips
> Signature cache fix

- tests/acceptance/features/environment.py
We have the same behavior in our integration smoke tests.
See: https://github.com/boto/botocore/blob/develop/tests/integration/test_smoke.py#L86-L90
> Skip sts/importexport acceptance tests

- docs/source/topics/events.rst
The arguments to the after-call event handler are ``http_response`` and ``parsed``, not ``response`` and ``parsed``.
> A small typo fix in the event docs

- botocore/docs/example.py
- botocore/docs/method.py
- botocore/docs/params.py
- botocore/docs/shape.py
- botocore/model.py
- botocore/response.py
- docs/source/reference/response.rst
- tests/functional/docs/test_streaming_body.py
- tests/unit/docs/test_method.py
Automatically document all operations with a streaming body. Previously they were incorrectly documented as bytes.
This fixes boto/boto3#330
> Document streaming body

- botocore/client.py
- botocore/handlers.py
- tests/integration/test_s3.py
- tests/unit/test_handlers.py
- tests/unit/test_s3_addressing.py
Some unicode values can break the XML parser, so we have s3 url encode the keys and decode them on our end.
> Automatically set EncodingType to url

- botocore/loaders.py
- tests/__init__.py
- tests/functional/test_loaders.py
- tests/unit/test_loaders.py
- tests/unit/test_waiters.py
This was a regression introduced in
1225dc7ed2246461166b27822323d61543ae0550.  This was
originally fixed in 0.68.0 of botocore.
At this point, I think a functional test in warranted,
as this did functionality did not surivive a refactoring,
so I've added a basic functional test to ensure we don't
regress on this in the future.
There were also a few tests that need to be updated with this change.
These tests were previously wrong but were not being caught
because of this bug.
> AWS_DATA_PATH should override customer/builtin data paths

- botocore/credentials.py
- botocore/exceptions.py
- tests/unit/test_credentials.py
This is a direct port with these exceptions:
* The JSONFileCache was kept in the CLI.  You can still
instantiate or attach a cache to the assume role provider
if you're writing short lived scripts and want to avoid
making unnecessary AssumeRole API calls, but you'll need
to provide your own cache implementation.
* A get_provider() convenience method was added to the
credential resolver.
This makes it straightforward to still use the JSONFileCache
in the CLI via:
```
c = session.get_component('credential_provider')
provider = c.get_provider('assume-role')
provide.cache = JSONFileCache()
```
Note: there will be a corresponding PR to CLI we'll need to sync up.
Supersedes and closes #721 
> Move assume role provider from CLI to botocore

- .travis.yml
- botocore/docs/bcdoc/restdoc.py
There's a regression on python35 where the final parts of the
document aren't parsed unless you call close.
Looks like there's a fix for this here:
https://bugs.python.org/issue23144 but this won't be available
until at least 3.5.1.
Either way, calling close() should work going forward even once
the original behavior is fixed.
I did verify that it's ok to re-use the parser after you call
close().
> Fix doc generation on python35

- botocore/exceptions.py
- botocore/loaders.py
- tests/unit/test_loaders.py
Fixes boto/boto3#418
Error message before:
```
ValidationError: Invalid value ('ecr') for param service_name of type str
```
Error message now:
```
UnknownServiceError: Unknown service: 'asdf'. Valid service names are: apigateway, ..., swf, waf, workspaces
```
> Improve error message when creating unknown service

- requirements.txt
- tests/unit/test_signers.py
This properly fails in mock 1.3.0.
Rather than use assert_called_once_with() I've just used
assertEqual(call_count, 1) which works with older versions
of Mock.
I've bumped the test dependency to mock=1.3.0, which catches
more error cases (such as the one here).
Fixes #738.
> Remove usage of nonexistent assert_called_once method

- botocore/data/_retry.json
Encountered this with API gateway:
http://docs.aws.amazon.com/apigateway/api-reference/handling-errors/
Given 429 Too Many Requests is a generic HTTP status code, I added
to the default set of status codes we retry instead of just for API
gateway.
cc @mtdowling @kyleknap @rayluo @JordonPhillips
> Add 429 as a status code to retry

- botocore/handlers.py
- tests/functional/docs/__init__.py
- tests/functional/docs/test_s3.py
- tests/integration/test_s3.py
- tests/unit/test_handlers.py
Follow up from https://github.com/boto/botocore/pull/757, this adds support for a dict value for `CopySource`.  This ensures we automatically handle all cases correctly for the customer because they're explicitly telling us the bucket, key, and optional version id.
```
s3.copy_object(CopySource={'Bucket': 'sourcebucket', 'Key': 'sourcekey'})
```
I've also handed a handler to update the documentation for this new format.
I'll add a handwritten example to boto3 shortly as well.
NOTE: I've branched this off of #757 because I had to modify the existing handler for the string value of `CopySource` so you'll see the diff of both in this PR.
> Add support for alternate form of CopySource

- botocore/handlers.py
- tests/unit/test_handlers.py
The previous commit to add automatic endcoding and decoding of S3 responses missed a few keys: https://github.com/boto/botocore/pull/726
Specifically, we were not decoding Marker, Delimiter, NextMarker, and CommonPrefixes[*].Prefix. The decode_list_object handler has been updated to decode each of these members in the parsed response if they are present.
This change will fix a CLI issue: https://github.com/boto/botocore/issues/762
For more information, see http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html
(supersedes and builds on https://github.com/boto/botocore/pull/752)
@jamesls @kyleknap @JordonPhillips @rayluo
> Adding missing url decoding from S3 responses.

- botocore/parsers.py
- tests/unit/protocols/output/rest-xml.json
- tests/unit/response_parsing/xml/responses/s3-get-bucket-acl.json
- tests/unit/response_parsing/xml/responses/s3-get-bucket-logging.json
This fixes an issue where the "Type" field was not being
populated from S3 responses such as ``get_object_acl``.
> Parse xml attributes in XML responses

- botocore/data/ssm/2014-11-06/paginators-1.json
We were missing paginators for ssm. Here are the API docs to double check: http://docs.aws.amazon.com/ssm/latest/APIReference/API_ListDocuments.html
> Add paginators for ssm

- botocore/validate.py
- tests/unit/test_validate.py
This commit updates Botocore to no longer validate the "max" constraint.
This allows customers to use older versions of Botocore/CLI even if the
service relaxes the "max" constraint in a subsequent release.
@jamesls @kyleknap @rayluo @JordonPhillips
> Removing "max" trait validation.

- botocore/endpoint.py
- botocore/exceptions.py
- botocore/stub.py
- tests/functional/test_stub.py
- tests/unit/test_stub.py
This will allow customers to stub out operations, providing their own responses so that they don't have to hit an endpoint to test their code. The interface for this is the `Stubber` class, which will manage the response queue and and handle validating the provided response stubs.
Usage example:
```python
import botocore.session
import botocore.stub
import datetime
s3_client = botocore.session.get_session().create_client('s3')
stubber = botocore.stub.Stubber(s3_client)
list_objects_response = {
'IsTruncated': False,
'EncodingType': 'url',
'Marker': '',
'Prefix': '',
'Name': 'test-bucket',
'Contents': [
{
'Size': 123,
'Owner': {
'DisplayName': 'display_name',
'ID': '123abc'
},
'Key': 'file.txt',
'StorageClass': 'STANDARD',
'ETag': '"abc123"',
'LastModified': datetime.datetime(2015, 12, 7, …
```
> Support stubbing out operations.

- botocore/stub.py
- tests/functional/test_stub.py
- tests/unit/test_stub.py
Allows you to specify what parameters that you are to expect for a response and if they do not match, throw an error.
I have been writing a fair amount of tests using this stubber. I have found this sort of response/expected_params matching as being pretty useful and was using it an awful lot.
The only behavior I am not sure about and would be up for opinions is what happens to the stubber's corresponding response when an ``expected_params`` does not match. Should it use up the response in the queue? Or should it keep the original response in the queue so that it can be called later? I decided to go with the later because in the current stubber logic if there is a parameter validation error with the client, we will not pop the response off of the queue. So I thought ``expected_params`` …
> Assert ``expected_params`` stubber

- botocore/signers.py
- tests/unit/test_signers.py
This simplifies the code and fixes potential edge cases from
caching.
This was a legacy artifact from having to support both the
service/operation objects and the client interfaces at the
same time.  This is now no longer needed.
The only concern would be if caching actually helps performance.
To verify this, I ran a test consisting of:
* Mocking out the _send_request in endpoints.py to return a precanned
response.
* Making a client call 1000 times (I chose ec2 DescribeInstances
arbitrarily).  This is essentially timing the time it takes from
a client method until it hits the http layer in botocore.
I ran the tests against botocore's develop branch and this PR.  There's
negligible difference::
```
(simple-auth %) $ repeat 10 python scripts/signerperf.py
Total time: 0.7235
Total time: …
```
> Remove caching in request signer

- botocore/paginate.py
- tests/unit/test_paginate.py
Previously, our custom pagination token came in the form: `serviceToken___5000` where serviceToken represented the service's pagination token(s) and the number at the end represented where in the array we should slice the response. The problem is that a token for dynamodb or s3 can include a triple underscore. So instead of seeing one token and an index, we see two tokens and an index. This causes the paginator to fall on its face.
The solution is to use a list as a token instead. So our token will now look like `"['serviceToken', '5000']"`. We then use ast to evaluate that back into a list that we can easily use. The service token won't cause any issues because python will see that it's a string and leave it at that. Additionally, if the service token is not a string (such as in the case …
> Refactored paginators to use a dict rather than a custom seperator.

- botocore/credentials.py
- botocore/signers.py
- tests/__init__.py
- tests/functional/test_credentials.py
- tests/unit/test_credentials.py
- tests/unit/test_signers.py
This builds on the pull request from https://github.com/boto/botocore/pull/764 and introduces a few additional enhancements for multithreaded credential refresh.  Includes:
* The original fix from #764.  Credentials must be accessed as a fixed set to ensure you don't get access_key from time t_1 and secret_key from time t_2.
* Introduce locking to ensure only one thread starts the refresh process.  The previous behavior was that every thread, once determining a refresh was needed, would all call the refresh function.  Additionally, double checked locking is used to avoid lock acquisition in the common case where a refresh isn't needed.
* Don't hard fail if refreshing initially fails.
To expand on the last point, there's now two time periods for refresh, the advisory period and the …
> Improve thread safety of temp cred refresh

- botocore/paginate.py
- tests/unit/test_paginate.py
On python 3, the output of base64 encoding is a `bytes` object, which does not play well with the JSON encoder / decoder.
cc @jamesls @kyleknap @rayluo
> NextToken should be a string, not bytes.

- requirements.txt
Same change was made in the AWS CLI, this PR keeps
botocore in sync with the AWS CLI.
Verified `tox` runs successfully for me.
cc @kyleknap @rayluo @JordonPhillips
> Lock tox to 2.x

- botocore/parsers.py
- tests/unit/test_parsers.py
This pulls in https://github.com/boto/botocore/pull/731 with a few changes:
* Move up common functionality into base class.  The logic for parsing a JSON body, handling encoding, and defaulting to an empty dict when no body is present is now consolidated to a single base class method.
* Group all error tests into a single class.  The eventual goal is to pull these into the shared protocol tests,.  Grouping them into a single test class makes this easier.
It's hard to see the new test because I've grouped all the error tests together, but the test case for this bug fix is here: https://github.com/boto/botocore/pull/799/files#diff-16d168f91b157ec88dcddaf854150629R503
Closes #731.
cc @kyleknap @rayluo @JordonPhillips
> Handle 504 error from cloudsearch

- botocore/compat.py
- botocore/handlers.py
- tests/integration/test_s3.py
- tests/unit/test_compat.py
- tests/unit/test_handlers.py
This is to avoid sending large initial requests to S3, which can result in S3 terminating the connection and a broken pipe on our end.
> Automatically wrap S3 string upload bodies with BytesIO.

- botocore/exceptions.py
- botocore/stub.py
The newly introduced StubAssertionError derives from AssertionError,
so that it will be (properly) classified as test failure rather than
test error when your test cases fail on that.
> Change one StubResponseError to StubAssertionError

- botocore/handlers.py
- tests/unit/test_handlers.py
We have a function which avoids md5 when in sigv4, but forgot to include s3v4 even though we attach the function to several s3 commands.
cc @jamesls @kyleknap @rayluo
> Don't use MD5 with s3v4

- botocore/signers.py
- tests/unit/test_signers.py
Regression on error condition from when the refresh credential bug fix merged.
You'll now get the original error message:
```
File "/tmp/t.py", line 5, in <module>
print ec2.describe_instances()
File "botocore/botocore/client.py", line 301, in _api_call
return self._make_api_call(operation_name, kwargs)
File "botocore/botocore/client.py", line 387, in _make_api_call
operation_model, request_dict)
File "botocore/botocore/endpoint.py", line 117, in make_request
return self._send_request(request_dict, operation_model)
File "botocore/botocore/endpoint.py", line 142, in _send_request
request = self.create_request(request_dict, operation_model)
File "botocore/botocore/endpoint.py", line 126, in create_request
operation_name=operation_model.name)
File …
```
> Fail gracefully when no credentials are found 

- botocore/compat.py
- botocore/exceptions.py
- botocore/handlers.py
- tests/unit/test_compat.py
- tests/unit/test_handlers.py
On some systems, such as a FIPS enabled system, MD5 hashing is unavailable. This commit will detect when that is the case, avoiding it where possible and raising a better error otherwise.
cc @jamesls @rayluo @kyleknap
> Verify MD5 is available

- botocore/docs/bcdoc/docstringparser.py
- botocore/docs/bcdoc/style.py
- tests/unit/docs/bcdoc/test_docstringparser.py
- tests/unit/docs/bcdoc/test_style.py
Fixes boto/boto3#310
There were three issues at play:
1. We were completely disabling newlines when going through lists
2. Nested lists need to be indented, but the top level list should not be.
3. The doc strings contain, in some cases, several spaces between the start of an `li` and the first instance of text. This causes all sorts of problems in rst.
To make things easier, I separated this PR into three commits, one for each of the items above. Item 3 is the trickiest customer, and required a significant change.
Basically, we need to have full context of the lists before we write them so that we can remove vestigial spaces. What I have done here is change the DocStringParser so that it writes to a tree, and then flushes it all out at close. This allows us to do inspections before …
> Nested docstring lists

- botocore/data/endpoints.json
> SDB should use signature version 2

- botocore/credentials.py
- tests/unit/test_credentials.py
This pulls in #751 and adds a testcase that demonstrates the issue.
Essentially, the `RoleSessionName` argument was only being provided in the first `assume_role` call, and not in subsequent `assume_role` refresh calls.
cc @kyleknap @JordonPhillips 
Closes #751.
> Add testcase for #751 (assume role provided bug)

- botocore/data/_retry.json
It is here in the docs: http://docs.aws.amazon.com/kinesis/latest/APIReference/API_DescribeStream.html
Also here is an error that may be returned:
```
DEBUG:botocore.parsers:Response body:
{"__type":"LimitExceededException","message":"Rate exceeded for stream request_counters_temp under account XXXXXXXX."}
DEBUG:botocore.hooks:Event needs-retry.kinesis.DescribeStream: calling handler <botocore.retryhandler.RetryHandler object at 0x7f824d7bc4d0> 
```
> Add retry for kinesis DescribeStream

- botocore/exceptions.py
- botocore/loaders.py
- tests/unit/test_loaders.py
This makes it general enough to use for boto3 resources.
In order to make this backwards compatible, the UnknownServiceError
subclasses from DataNotFoundError.
> Don't use hardcoded service-2 for type name

- botocore/client.py
- tests/unit/test_client.py
This fixes a bug where if you try to use
DynamoDB Local via `--region local`,
we'll try to connect over https:// despite
the fact that the `protocols` key for that
region indicates that only http is supported.
Also verified I could connect to dynamodb local
after these changes.
Fixes #819.
> Use 'protocols' key to influence scheme

- botocore/docs/example.py
- botocore/docs/method.py
- botocore/docs/params.py
- botocore/docs/shape.py
- botocore/model.py
- tests/unit/docs/test_method.py
- tests/unit/test_model.py
Fixes https://github.com/boto/boto3/issues/477
Here are samples of how it looks:
> Document streaming payload inputs

- botocore/session.py
- tests/unit/test_session.py
Also allows use to specify ``api_versions`` in the config file so the CLI can start picking these up as well. It would looks like this in the config file:
```
api_versions =
cloudsearch = 2011-02-01
ec2 = 2014-10-01
```
If you want to set the api versions on the session, you would have to use the session's ``get_config_variable()`` and ``set_config_variable()`` methods.
> Add api_versions to session variable

- botocore/data/cloudformation/2010-05-15/waiters-2.json
This merges #630 and the ruby SDK waiter changes.
Closes #630.
> Sync clouformation waiters

- botocore/utils.py
- tests/unit/test_utils.py
In the [RFC 3986, section 5.2.4](https://tools.ietf.org/html/rfc3986#section-5.2.4), 2A and 2B, it's indicated to remove `/.` or `/..` but only if `.` or `..` are complete path segments. The problem was that these were always removed, so an URL like `/.example/` would become `/example/`, then the signature would be rejected by the services.
Rewrote the function in a (I think) more pythonic way. Also, added two tests to cover those cases.
> Fix remove_dot_segments

- botocore/handlers.py
Lambda already updated their docs for `ZipFile` in `create_function` so we don't need that here.
Resolves boto/boto3#201
> Document automatic base64 encoding of lambda ZipFile

- botocore/exceptions.py
- botocore/handlers.py
- tests/functional/docs/test_alias.py
- tests/functional/test_alias.py
- tests/unit/test_handlers.py
Fixes parameters that shadow reserved keywords in python and inconsistent
parameter names in ec2.
Fixes https://github.com/boto/botocore/issues/772
As to implementation, I followed a similar format (just a tad different) as the CLI so if the alias needed to be in both the CLI and boto3, we could import the dictionary in botocore and modify the ``HIDDEN_ALIAS`` dictionary in the CLI or just copy and paste entities in that dictionary from botocore to the CLI. I went with this path because it required less work and less of a wider impact in the code base then the ``all_member`` route we discussed . Also it would not be difficult for the CLI to pick up these aliases as it already has this functionality.
> Add ability to alias parameters

- botocore/parsers.py
- tests/functional/test_s3.py
- tests/unit/test_parsers.py
> Handle the case where we receive a generic html error response

- botocore/serialize.py
- tests/functional/test_s3.py
- tests/unit/test_serialize.py
When serializing input to rest-* protocols, we need
to ensure that any value that's associated with a header value
is converted to a string.
Fixes #791.
> Always convert header values to str()

- botocore/data/_retry.json
Last part of the fix required for aws/aws-cli#1679.
First part was ensuring we can parse out the appropriate errors from proxy responses (https://github.com/boto/botocore/pull/850)
> Retry 502 responses

- botocore/paginate.py
- tests/functional/test_paginate.py
- tests/integration/test_ec2.py
- tests/unit/test_paginate.py
A recent change to paginators broke customers who were manually crafting pagination tokens in services where they did not make them opaque. This adds support for the old starting token format while still returning next tokens in the new format. If we are unable to parse the starting token in the new format, we'll attempt to parse it with the old format.
This addresses the root cause of aws/aws-cli#1835, but the docs should be updated to reflect the new tokens.
> Fall back to deprecated starting token parser

- botocore/parsers.py
- tests/unit/test_parsers.py
The generic error parsing code can now additionally be triggered by a 5xx response with an empty body in addition to an html response body.
This also required updating one test which was previously leaving the code/message blank in this scenario.
Fixes boto/boto3#574.
> Consistently parse error responses with no body

- botocore/exceptions.py
- botocore/handlers.py
- tests/functional/test_s3.py
- tests/unit/test_handlers.py
> Validate S3 metadata only contains ascii chars

- botocore/paginate.py
- tests/integration/test_route53.py
- tests/unit/test_paginate.py
This fixes a regression that wasn't handled with the recent fallback fix. Closes #862 
> Allow non-specified input tokens in old starting token format

- tests/integration/test_rds.py
- tests/integration/test_route53.py
A few tests were using base unittest rather than our compat version.
> Use compat unittest

- botocore/handlers.py
- tests/functional/test_apigateway.py
- tests/unit/test_handlers.py
APIGateway has at least one function, `get_export`, which relies on the use of the `Accept` header. We were over-writing that with `application/json`, so this checks to see if the header is already set before we put that in.
> Don't overwrite the Accept header if it is already set

- botocore/response.py
This little bit of code is called by nothing in botocore, boto3, or the CLI. Looks like it was renamed and moved into StreamingBody, but the original location didn't get removed.
> Remove dead code in response.py

- botocore/credentials.py
- tests/unit/test_credentials.py
> Add missing % in datetime format string

- botocore/auth.py
- tests/unit/auth/test_signers.py
The user agent may be changed somewhere along the line, so we should not
be signing it.
#846
> Do not sign user-agent

- .changes/next-release/bugfix-awskinesis.json
- botocore/data/kinesis/2013-12-02/paginators-1.json
> Update missing non aggregate key to pagination config 

- .changes/next-release/bugfix-Serializer.json
- botocore/serialize.py
- tests/unit/test_serialize.py
In the rest xml parser, we were converting the input we recieve into a
`str`, which was causing failures on python 2 when multibyte unicode
strings were passed in. The fix is to simply use `six.text_type`, which
is `unicode` on 2 and `str` on 3. The string will be encoded into the
default encoding later on in the serializer.
Fixes #868
> Don't preemptively convert unicode in rest-xml parser

- botocore/data/_retry.json
There was a bug with the 502 retries where it was added to
the definitions, but not to the default list of retry policies.
I've verified that 502 and 504 are in fact retried now.
> Retry 502 and 504 status codes

- botocore/data/ec2/2015-10-01/waiters-2.json
Users were seeing waiter timeouts with this.  So bumped up the delay time as it can take roughly 30 minutes for it to be available.
> Bump delay time for VpnConnection waiter

- botocore/stub.py
- tests/functional/test_stub.py
- tests/unit/test_stub.py
It can be useful to use a stubber as a context manager to make code a
bit more readable and to ensure you aren't leaking events.
I was responding to a question on StackOverflow about stubbing responses
in which they were attempting to use mock. While they didn't complain
about having to use `activate`, I realized my sample code didn't look
as clean as their (unsuccessful) attempt at mocking. Since it is such
a tiny change, I figured it would be useful if I just knocked it out.
```python
import datetime
import botocore.session
from botocore.stub import Stubber
s3 = botocore.session.get_session().create_client('s3')
response = {
"Owner": {
"ID": "foo",
"DisplayName": "bar"
},
"Buckets": [{
"CreationDate": datetime.datetime(2016, 1, 20, 22, 9),
"Name": "baz"
}]
}
with Stubber(s3) as stubber: …
```
> Implement context mangager functions for Stubber

- botocore/paginate.py
- tests/unit/test_paginate.py
Some paginate-able operations do not support page size. Before, we would
just blindly try to toss it in anyway, leading to a very confusing error.
This raises an error on a call to paginator.paginate if page size is
provided, but not supported.
Fixes #876
> Provide better error when page size is not supported

- botocore/loaders.py
- botocore/model.py
- tests/unit/test_model.py
This includes two things:
1. Add location of JSON file from loaders:
```
$ aws s3api list-buckets --debug
2016-05-12 15:00:56,727 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/foo/Source/botocore/botocore/data/s3/2006-03-01/waiters-2.json
```
2. Add operation name to the repr:
```
$ aws s3 cp foo s3://bucket/ --debug 2>&1 | grep OperationModel | awk '{print $13}'
OperationModel(name=CreateMultipartUpload)
OperationModel(name=UploadPart)
OperationModel(name=UploadPart)
OperationModel(name=UploadPart)
OperationModel(name=UploadPart)
OperationModel(name=UploadPart)
OperationModel(name=UploadPart)
OperationModel(name=UploadPart)
OperationModel(name=CompleteMultipartUpload)
```
> Include more info in debug logs

- .changes/next-release/bugfix-Waiters.json
- botocore/data/ec2/2015-10-01/waiters-2.json
- botocore/waiter.py
- tests/integration/test_ec2.py
- tests/integration/test_waiters.py
- tests/unit/test_waiters.py
Builds on #907 to fix #906.
Because of the normalized responses the waiter gets, we should only try jmespath searching if we receive a non error response.
> Fix patch matchers to only search non error responses

- botocore/stub.py
- tests/functional/test_stub.py
Makes the error messages a little easier to read::
```
StubAssertionError: Error getting response stub for operation PutIntegration: Expected parameters:
{'authorizationType': 'NONE',
'httpMethod': 'GET',
'resourceId': 'parent-id',
'restApiId': 'rest-api-id'},
but received:
{'httpMethod': 'GET',
'integrationHttpMethod': 'POST',
'requestTemplates': {'application/json': '{...}'},
'resourceId': 'parent-id',
'restApiId': 'rest-api-id',
'type': 'AWS',
'uri': 'arn:aws:apigateway:us-west-2:...'}
```
> Pretty print expected params

- .changes/next-release/feature-Stubber.json
- botocore/stub.py
- tests/unit/test_stub.py
Some services return additional error keys that may be relevant
in debugging, this adds the ability to add arbitrary keys to the
stubbed error response.
> Add additional keys to error response

- .changes/next-release/bugfix-s3.json
- botocore/handlers.py
- tests/unit/test_handlers.py
Right now you can't use the `Stubber` object with s3's `get_bucket_location` because it has an override that assumes a body of xml is available. This patch allows the override to be skipped where something (in this case the stubber) has already 'parsed' the response.
> Allow stubber to be used with GetBucketLocation

- .changes/next-release/feature-Stubber.json
- botocore/stub.py
- tests/functional/test_stub.py
This allows users to specify stub.ANY for expected parameters if
they don't care about a specific parameter's value.
Resolves #931
cc @kyleknap  @jamesls
> Allow paramters to be ignored in Stubber validation

- .changes/next-release/bugfix-Stubber-31703.json
- botocore/stub.py
- tests/functional/test_stub.py
Sometimes the list returned from dict.keys() will not be in the same order
which will cause the equality of keys check to fail:
```
>>> ['key1', 'key2'] == ['key2', 'key1']
False
```
To fix it, the keys need to be sorted.
Noticed it because of failing tests here: https://github.com/boto/s3transfer/pull/15
> Fix regression in stubber

- .changes/next-release/bugfix-EC2-81604.json
- botocore/handlers.py
- tests/unit/test_handlers.py
It's possible that the console output from EC2 contains
non string chars we can't utf-8 decode.  When that happens
we were previously just leaving the input untouched, i.e
base64 encoded.
This made for an awkward interface for customers.  We couldn't guarantee
whether or not the content was base64 decoded because it would depend
on the actual ec2 console output content.
This change attempts to make things more consistent by
replacing any chars we can't decode with the unicode
`\ufffd` char (the unicode replace char, i.e the question mark).
The one downside with this approach is that it is possible
to sometimes not get the unaltered contents of the console
output because chars have been replaced with `\ufffd`.
We'll need to weigh whether or not we think that's worth
the benefit.  Given …
> Replace chars we can't decode with placeholder char

- .changes/next-release/bugfix-AssumeRole-9717.json
- botocore/parsers.py
- tests/unit/test_parsers.py
This pulls in https://github.com/boto/botocore/pull/961 and adds tests for the change.
Right now you get an error:
```
$ aws ec2 describe-instances --profile some-role
Value cannot be cached, must be JSON serializable: {u'AssumedRole...
```
This was from a recent addition to botocore that added the HTTP headers into the response metadata returned from client calls.
I agree with the original change from @bashtoni to fix this in the parser.  We've had an implicit contract that you can JSON dump response metadata so while we could fix this in the assume role cacher, it's possible customer code could be relying on this property, in which case we would not be able to fix.
> Fix regression in assume role caching

- .changes/next-release/bugfix-RequestSigner-36076.json
- .changes/next-release/feature-RequestSigner-34181.json
- botocore/handlers.py
- botocore/signers.py
- botocore/utils.py
- tests/functional/test_s3.py
- tests/unit/test_handlers.py
- tests/unit/test_signers.py
This adds the choose-signer event to the presigers, allowing
for hot swapping the signature version when presigning.
Additionally, adds support for using botocore.UNSIGNED with the
presigners.
> Add choose-signer event to presigners

- .changes/next-release/bugfix-S3-4368.json
- botocore/utils.py
The S3RegionRedirector holds a reference to the client, which was
causing memory leaks on python 2.6. We didn't notice this previously
because our tests give us a certain tolerance and we were still
falling under that tolerance. If more events are added to the
event emitter by default, it can cause the amount of memory leaked
to go past our tolerance.
This fixes the issue by making the S3 redirector hold a weakref to
the client instead of a strong reference. We don't have to worry
about it being GC'd because customers will be holding a strong ref
to the client for us.
> Use weakref for client in S3 redirector

- tests/integration/test_client.py
When switching to sigv4 by default, I missed this S3 test in the client
integration tests. I did a search of the other integration tests to
look for create bucket, and only found one in test_elastictranscoder
which was configured for us-east-1 and thus does not need that value
to be set.
cc @jamesls @phjordon
> Populate location constraint in integration tests

- tests/integration/test_s3.py
The thread safe auth test depends on `auth_path`, which is only
set when using virtual host style addressing. Since sigv4 does
not use virtual host style by default, the test broke. This
configures the client to use virutal host style for that test.
> Force virtual host style for thread safe auth test

- botocore/data/codedeploy/2014-10-06/waiters-2.json
This PR implements waiters for CodeDeploy' s most basic deployment flows.
Deployment state as a whole can take Created/Queued/InProgress/Succeeded/Failed/Stopped.
http://docs.aws.amazon.com/codedeploy/latest/APIReference/API_DeploymentInfo.html#CodeDeploy-Type-DeploymentInfo-deploymentOverview
This waiter waits until deployments Succeeded/Failed/Stopped..
Closes boto/boto3#708
```
$ aws deploy create-deployment \
--application-name foo \
--deployment-config-name CodeDeployDefault.OneAtATime \
--deployment-group-name bar \
--description "baz" \
--s3-location bucket=YOUR-BUCKET,bundleType=zip,key=YOUR/KEY.zip
{
"deploymentId": "d-123456789"
}
$ aws deploy wait deployment-successful --deployment-id d-123456789
```
OpsWorks has wait/deployment-successful API, so I followed this naming …
> add CodeDeploy waiters for deployments

- .changes/next-release/bugfix-s3-36114.json
- botocore/utils.py
- tests/unit/test_utils.py
If the old URL was using http over https, we will no continue to
use http.
Fixes #976
Closes #984
> Honor old scheme when redirecting S3 requests

- botocore/handlers.py
- tests/unit/test_handlers.py
Passing `bytearray` to S3 multipart upload fails when calculating md5. Having the below code, it fails w/o the modification.
https://gist.github.com/foobarna/913a84136a4357bbdc4112c924c0c41e
https://docs.python.org/2/whatsnew/2.6.html#pep-3112-byte-literals
> allow bytearray in calculating md5 from bytes

- tests/integration/test_s3.py
Use bucket_client instead of self.client.
Also, use a waiter to ensure the bucket exists.  There are times
when this test can fail with a bucket does not exist.
> Make s3 integ test more resilient

- .changes/next-release/bugfix-Credentials-86559.json
- botocore/session.py
- tests/integration/test_credentials.py
- tests/unit/test_session.py
This builds on #987 to make this condition an error case.
A user providing just an access key or secret key is never
valid and should result in an error.
This is also consistent with other cred providers that raise
PartialCredentialsError for partial creds.
https://github.com/boto/boto3/issues/686
> Raise error on partial creds provided

- botocore/utils.py
- tests/unit/test_utils.py
Use 'response.text' for more flexible decoding on error; this uses errors='replace'
and tries to auto-detect encoding. Makes sense since an error may not be
generated by AWS and might not always be UTF-8.
This is a bug in how the ECS ContainerMetadataFetcher gets the credentials when running inside a task.
> ECS: use 'response.decode' to convert bytes -> string on python3

- botocore/exceptions.py
- tests/unit/test_exceptions.py
The operation name could be useful when working with exceptions raised by boto, currently you'll have to match on the error message which is far from optimal.
> Save operation_name on ClientError exception object

- botocore/data/ecr/2015-09-21/paginators-1.json
This API is paginated, but botocore lacks the paginator definition.
> add paginator for ECR ListImages

- botocore/waiter.py
- tests/unit/test_waiters.py
During a waiters wait() routine, if the botocore client throws a ClientError, and there is no Acceptor in the JSON configured to handle that specific ClientError response, then a less informative WaiterError is thrown.
In doing so, error response information is lost (such as the Error Code), making it impossible to accurately detect certain errors (namely, 5xx errors and ThrottlingException, per http://docs.aws.amazon.com/general/latest/gr/api-retries.html
This "WaiterError" is caused by a regular ClientError, and has no specific connection to Waiter logic, other than it happened during waiting (unlike other WaiterErrors, which are for waiter-specific failure conditions like "max retries exceeded")
If a ClientError occurs, and there is no Waiter logic ("acceptors") that handles it, then …
> Waiter throw ClientError for unexpected error response

- botocore/exceptions.py
- botocore/waiter.py
- tests/unit/test_waiters.py
The rationale behind just adding a last_response instead of exposing some sort
of error_code and error_message is that a WaiterError can also be thrown in
non-error states (transitioning to a failure state, hitting max-attempts), and
while we can always guarantee a last response, we can't necessarily guarantee
that response is a "error" response.
Closes https://github.com/boto/botocore/pull/957
> Add last_response attr to WaiterError

- .changes/next-release/feature-ResponseMetadata-68727.json
- botocore/endpoint.py
- botocore/exceptions.py
- botocore/retryhandler.py
- tests/unit/test_endpoint.py
- tests/unit/test_exceptions.py
- tests/unit/test_retryhandler.py
This pulls in https://github.com/boto/botocore/pull/965 with the following changes:
* Replace `Retries` list with the number of retry attempts.
* Update `ClientError` messages to include retry information when max attempts are reached.
More context [here](https://github.com/boto/botocore/pull/965#issuecomment-243618656).
A few examples:
Client error messages:
```
An error occurred (NotFound) when calling the DescribeInstances operation (max_retries=4 reached): The instance ID 'i-1234' does not exist
```
ResponseMetadata on error:
```
'ResponseMetadata': {'HTTPHeaders': {'connection': 'close',
'date': 'Wed, 31 Aug 2016 17:41:51 GMT',
'server': 'AmazonEC2',
'transfer-encoding': 'chunked'},
'HTTPStatusCode': 400,
'MaxAttemptsReached': True,
'RequestId': 'abcd',
'RetryAttempts': 4}}
``` …
> Add retry information to ResponseMetadata

- .changes/next-release/feature-Config-99817.json
- botocore/args.py
- botocore/config.py
- botocore/endpoint.py
- tests/unit/test_args.py
- tests/unit/test_endpoint.py
- tests/unit/test_s3_addressing.py
This config value allows you to control the size of the
connection pools used in urllib3.  We were previously using the
hardcoded value of 10 (from requests).
I ended up not touching the `pool_connections` based on the
discussion from #766.
There ends up being quite a noticeable difference whenever
`num_threads > max_pool_connection`, so I think this will
help people running requests with a large number of threads.
As an aside, the implementation for this was much more complicated
than necessary.  I'm thinking on sending a few follow up PRs that
start to clean up some of this technical debt.
Closes #773
Closes #766
> Add max_pool_connections to client config

- .changes/next-release/feature-Stubber-16169.json
- botocore/stub.py
- tests/functional/test_stub.py
This way you can still verify that your client method is being called as expected before raising a `ClientError`.
This pulls in https://github.com/boto/botocore/pull/1025 and adds tests for the change.
> Allow expected params to be passed to add_client_error

- botocore/data/ec2/2016-04-01/waiters-2.json
- botocore/utils.py
- tests/functional/test_waiter_config.py
- tests/unit/test_utils.py
This improves the waiter config validation to check a few additional cases, primarily related to JMESPath including:
* Verify the JMESPath expression matches something in the output
* Verify the JMESPath expression returns list types for `pathAll` and `pathAny`
* Verify the operation referenced actually produces output.
In order to do this, I made one change to the `ArgumentGenerator` utility class.  In order to rely on the "truth" value of the jmespath search result, I didn't want empty strings being generated.  To account for this, I added the ability for the placeholder strings to optionally use the member names for the values.
As part of this change, I had to update one of the waiter configs as it was now failing the tests:
```
AssertionError: Attempted to use 'pathAll' matcher in …
```
> Improve functional test for waiter config validation

- botocore/data/cloudformation/2010-05-15/waiters-2.json
This removes two types of failure states from the cloudformation
waiters:
* Transitional states, e.g. delete_in_progress->delete_completed
* Any state which can still be transitioned to a success state
The first point aids in fast fails, but is otherwise unnecessary.
The latter point is the most interesting one.  Consider two operations:
* cfn.DeleteStacks()
* cfn.WaitDeleteStackComplete()
With the current approach, you *have* to call DeleteStacks before
WaitDeleteStackComplete.  However, one should be able to call
WaitDeleteStackComplete() in one process/thread, and then subsequently
call DeleteStacks().  This latter behavior is possible in other waiters.
Consider:
* Calling ec2.WaitInstanceTerminated, then terminating an instance
* Calling dynamodb.WaitTableNotExists, then deleting the …
> Remove unnecessary terminal states from cloudformation waiters

- .changes/next-release/bugfix-Waiters-383.json
- botocore/data/cloudformation/2010-05-15/waiters-2.json
Add back ROLLBACK_COMPLETE as a terminal failure state
StackCreateComplete can transition to a ROLLBACK_COMPLETE
when waiting for stack creation to complete.  The only action
upon reaching this state is to delete the stack.
Add back UPDATE_ROLLBACK_COMPLETE as fast fail case in waiter
For the update stack complete waiter, a failed update can result in
an UPDATE_ROLLEBACK_COMPLETE.  The unfortunate part here you
cannot use this waiter until you call UpdateStack, which is the
only cfn waiter that has this restriction.  This means a previous
UpateStack failed, calling the StackUpdateComplete waiter
before calling UpdateStack will immediately trigger the fast
fail case.
> Add back missing fast fail states to create/update cfn waiters

- tox.ini
I only have Pythons 2.7 and 3.5 installed on my system, so the tox file wasn't good for me to run with 2 and 3.
> Test with Python 3.5 in tox

- .gitignore
These files are generated by running `make html` for the docs or `tox` for tests.
> Add generated files to git ignore

- botocore/handlers.py
- tests/functional/test_cloudformation.py
Updated cloud formation documentation, changes get_template return type from string to dict.
Fixes #1058 
cc @kyleknap @jamesls @JordonPhillips
> Cloudformation documentation update

- .changes/next-release/feature-Stub-87309.json
- botocore/stub.py
- tests/functional/test_stub.py
Use the same compare-all class that `unittest.mock.ANY` uses to enable deep comparisons to 'just work'.
> Stubber: made ANY usable for nested parameters

- .changes/next-release/bugfix-Parsers-15252.json
- botocore/parsers.py
- tests/unit/test_parsers.py
This makes sure that, so long as the response was able to be parsed
into a dict, the ResponseMetadata key is always provided. This is
important because we use that for more than just what the service
directly returns.
> Always populate ResponseMetadata

- tests/integration/test_s3.py
This is the same way we do it in the CLI. Some tests still needed to make their own buckets, but the number has been greatly reduced. There's also a lot of room for removing tests entirely.
> Reduce the number of buckets created in tests

- botocore/utils.py
- tests/unit/test_utils.py
In the UK the time switches from GMT to BST and back as part of
their daylight savings time. time.tzname will therefore report
both time zones. dateutil sees that the time zone is a local time
zone and so parses it as local time, but it ends up being BST
instead of GMT. To remedy this issue we can provide a time zone
context which will enforce GMT == UTC.
Fixes #1070
> Enforce GMT == UTC

- .changes/next-release/feature-Loader-97471.json
- botocore/loaders.py
- botocore/utils.py
- tests/unit/test_loaders.py
- tests/unit/test_utils.py
These files will define extra data to be added into the service model
upon loading. These will be used to make additive changes to the
model which reflect sdk-specific information that is not sent over
the wire.
The deep merge is, of course, quite expensive. In a worst case scenario
(a very large service model and an equally sized extras file) client creation
takes ~4x as long on python 2 and ~2x as long on python 3. However, these extra
files will never be more than adding a few parameters. The impact given a
small extra file is negligible.
> Support loading json extra files

- tests/integration/test_apigateway.py
Consensus seemed to be that the retry handlers shouldn't be updated
for apigateway, but we have been having issues with our integration
tests hitting the throttling limits. This will continue trying to
delete the api for much longer.
> Make sure the apigateway api is deleted

- .changes/next-release/bugfix-Presigner-33378.json
- botocore/auth.py
- tests/unit/auth/test_signers.py
This attempts to json load request data that isn't already a dict
during presigning. As a result, rest-json services can now be
presigned.
> JSON load request data when presigning

- .changes/next-release/bugfix-s3-27146.json
- botocore/auth.py
- tests/unit/auth/test_signers.py
A unit test and fix for #1059, which is a sigv4 bug related to presigned urls where the base url contains a query parameter without a value, such as '/bucket/key?uploads' for an s3 create_multipart_upload url.
The first commit contains a unit test that fails, and the second commit updates SigV4QueryAuth._modify_request_before_signing to use the keep_blank_values param of parse_qs in order to preserve parameters with no value.
> sigv4 presigned urls should preserve blank params

- botocore/configloader.py
- tests/unit/cfg/aws_config_nested
- tests/unit/test_configloader.py
This useful for retrieving the literal value of an option instead of possibly treating it as its own subsection.
cc @jamesls @JordonPhillips @stealthycoin
> Add support disabling subsection parsing

- botocore/utils.py
- tests/unit/test_utils.py
Uses epoch time as a ``datetime`` for its default value. Right now it defaults to ``None`` which is in appropriate representation of the ``timestamp`` type in our models.
This is needed for this PR: https://github.com/aws/aws-cli/pull/2293
cc @jamesls @JordonPhillips @stealthycoin
> Add support for timestamp in ArgumentGenerator

- botocore/utils.py
- tests/unit/test_utils.py
Use the member name for strings in lists. Catches and edge case pointed out by @jamesls in this PR: https://github.com/aws/aws-cli/pull/2293
cc @jamesls @JordonPhillips @stealthycoin
> Use member names in lists for ArgumentGenerator

- .changes/next-release/bugfix-Exceptions-99181.json
- botocore/parsers.py
- tests/unit/test_parsers.py
Fixes Issue #908
By catching ValueErrors on json.loads when parsing the error's message body,
the raw message can be included as a string. This is not the common case,
but errors in an invalid format have been seen in Api Gateway, SWF and Dynamo
> Allow parsing of json error responses with non-json bodies.

- tests/functional/test_endpoints.py
This protects us from cases where we mis-name the artifacts that we
base our service names on. Generally these should be named based on
the endpoint prefix, except in a handful of special cases.
cc @jamesls @stealthycoin @kyleknap
> Verify endpoint prefix matches service name

- .changes/next-release/bugfix-sigv4-897.json
- botocore/auth.py
- tests/unit/auth/test_signers.py
The trace header can be mutated along the way, so it should be blacklisted.
> Do not sign trace header

- botocore/docs/bcdoc/style.py
- tests/unit/docs/bcdoc/test_style.py
This generates an inlink external link.  This is modeled off of the [sphinx_reference_label](https://github.com/boto/botocore/blob/develop/botocore/docs/bcdoc/style.py#L206)
> Add an external_link method

- botocore/docs/docstring.py
- botocore/docs/method.py
- botocore/docs/service.py
- tests/unit/docs/__init__.py
- tests/unit/docs/test_method.py
You'll see that part of the diff is changing the target to `html`.  botocore/boto3 never set the target so it was defaulting to man page.  This meant that for certain style calls in bcdoc, the proper refs/links weren't being generated.
In order to use the new `external_link` method, the target needed to be html.
One option was to only turn on target html when generating html docs, but the `man` target doesn't make much sense for boto3/botocore.
> Add cross links to service API

- botocore/paginate.py
- tests/unit/test_paginate.py
This bug causes the route53 list_resource_record_sets paginator to skip over records in certain cases.
list_resource_record_sets uses a 3-tuple of pagination tokens, but one of them will be absent on some records. If the second page starts with a 3-token item and the third page starts with a 2-token item, the previous third token will get left in the request parameters, causing the backend to advance past the targeted item.
> Fix a paginator bug involving optional tokens.

- tests/functional/__init__.py
- tests/functional/test_rds.py
Our travis tests are failing due to a recent RDS functional test that was added.  I added two things:
1. Fix the test (tests that need credentials should subclass BaseSessionTest)
2. Add package setup/teardown that more closely resembles the travis environment.  This likely went unnoticed because if you have credentials configured locally the test will pass.  With this change, the original test would have failed on a dev laptop.
> Fix failing rds test

- botocore/credentials.py
When logger is defined anywhere in the program Botocore is mostly silent with its logging statements except for this single logger. This commit changes it to be more in-line with other logging statement levels.
> Change credential log statement to INFO from DEBUG

- botocore/data/logs/2014-03-28/paginators-1.json
Caught by downstream CLI tests: https://github.com/aws/aws-cli/blob/develop/tests/functional/logs/test_get_log_events.py. I also ran the test for the CLI and that passed locally.
We will probably will have to stop paginating on repeated next tokens.
> Remove unsupported paginator

- botocore/configloader.py
- tests/unit/cfg/aws_config_unicode✓
- tests/unit/test_configloader.py
This decodes the path in config parser before throwing errors.
Fixes aws/aws-cli#2395
cc @kyleknap @jamesls @stealthycoin @dstufft
> Decode file paths in config loader

- botocore/configloader.py
- tests/unit/cfg/aws_config_unicode✓
- tests/unit/test_configloader.py
Reverts boto/botocore#1144
The tests were failing on our Windows test boxes. Reverting until we can get it fixed.
> Revert "Decode file paths in config loader"

- .changes/next-release/bugfix-config-8651.json
- botocore/configloader.py
- tests/unit/test_configloader.py
Fixes aws/aws-cli#2395
This was originally committed in #1144 but the tests failed on Windows due to some file system issues. This was resolved by creating the file on the fly and cleaning it up after.
I've run the tests (including integration) on several python versions on OSX, Linux, and Windows.
cc @kyleknap @jamesls @dstufft @stealthycoin
> Decode config file paths

- tests/unit/test_validate.py
3.6 json error no longer reports __repr__ of the failed object, instead it just shows the type.
cc @jamesls @kyleknap @JordonPhillips @dstufft
> Fixed test to not rely on getting the __repr__ in the error

- botocore/utils.py
- tests/unit/test_utils.py
`percent_encode` fails when handed a string that's already been encoded into bytes. Have it just URL-quote that instead.
This fixes an error I'm running into when using S3 via the "django storages" package. I have a few keys with non-ASCII characters. Django storages handles this by encoding them as UTF-8 and handing the bytes off to boto. On Python 2 this fails with a UnicodeDecodeError, and on Python 3 I don't think it will raise an exception, but will return a url-encoded repr of the string passed in (which is probably not what you would want).
> utils.percent_encode fix (with test)

- .changes/next-release/bugfix-Auth-55416.json
- botocore/auth.py
- tests/integration/test_s3.py
- tests/unit/auth/test_signers.py
See: http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html
Added integration test that fails without this change.
I verified that this affected glacier vault descriptions as well as s3
object metadata.
> Fix bug with sigv4 signer with consecutive spaces

- tests/unit/test_signers.py
This injects a scheme into some compared urls as urlsplit will fail
to properly split if the scheme is absent in some versions.
> Fix RDS Test for 2.6

- .changes/next-release/bugfix-Paginator-39515.json
- botocore/paginate.py
- tests/functional/test_paginate.py
- tests/unit/test_paginate.py
Some services (such as dynamodb) may use bytes in their pagination tokens, so this adds fallback support for that.
The solution in this PR is to attempt to encode as before, but if it fails to traverse the token dict encoding any bytes found and noting the path to those values.
Another option considered was using pickle, but the concern there was that we couldn't easily limit it to json+bytes and therefore we'd be exposing ourselves to code execution issues.
> Support paginating with tokens that contain bytes

- .changes/next-release/enhancement-Credentials-25943.json
- botocore/credentials.py
- tests/unit/test_credentials.py
This adds support for environment credential expiration via the `AWS_CREDENTIAL_EXPIRATION` environment variable.
> Support env var credential expiry

- botocore/data/_retry.json
Tested successfully against [ResourceGroupsTaggingAPI GetTagKeys()](http://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_GetTagKeys.html)
cc @jamesls @kyleknap @JordonPhillips @dstufft
> Add retry support for retryable ThrottledException

- botocore/compat.py
- tests/integration/test_client.py
- tests/unit/auth/test_sigv4.py
- tests/unit/test_utils.py
As botocore does not include six as a dependency, it should never
reference the globally installed six. Always use the vendored version
instead.
Helps ensure there is not an ImportError at runtime.
> Move all uses of six to the vendored version

- .changes/next-release/bugfix-Config-76988.json
- botocore/__init__.py
- tests/unit/test_utils.py
botocore.UNSIGNED is meant as a sentinal value like None, so copying
it should always return the same instance. This implements that
behavior.
Fixes boto/boto3#1144
cc @kyleknap @jamesls @dstufft @stealthycoin
> Make copying UNSIGNED return the same instance

- botocore/args.py
- botocore/config.py
- botocore/endpoint.py
- tests/unit/test_args.py
- tests/unit/test_endpoint.py
Allows setting the proxy servers to be used through the Config object
when creating the client.
Refs: boto/boto3#338
> Allow proxies to be set through the Config object.

- botocore/compat.py
- botocore/docs/sharedexample.py
- botocore/handlers.py
- botocore/utils.py
- tests/unit/test_regions.py
Fixes warning of the form:
```
DeprecationWarning: invalid escape sequence \...
```
See:
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior
> Fix all invalid escape sequences discovered running tests

- botocore/handlers.py
openssl_version_tuple[2] is 0 on OpenSSL 1.1.0, which fails the condition, but should be accepted. Simply comparing tuples should work.
> Don't fail OpenSSL version check on 1.1.0

- botocore/auth.py
- tests/unit/auth/test_signers.py
The add_auth() method references request.param rather than
request.params which causes it to thow an AttributeError when invoked on
a GET request.
This fix is required to access the Alexa Top Sites API using botocore.
```python
from botocore.auth import SigV2Auth
from botocore.awsrequest import AWSRequest
from botocore.endpoint import BotocoreHTTPSession
from botocore.session import get_session
request = AWSRequest()
request.method = 'GET'
request.url = 'https://ats.amazonaws.com'
request.params['Action'] = 'TopSites'
request.params['ResponseGroup'] = 'Country'
credentials = get_session().get_credentials()
auth = SigV2Auth(credentials)
auth.add_auth(request)
session = BotocoreHTTPSession()
session.send(request.prepare())
```
> Fix SigV2Auth for GET requests

- botocore/data/kinesis/2013-12-02/paginators-1.json
Kinesis Streams recently introduced server-side encryption:
https://aws.amazon.com/blogs/big-data/under-the-hood-of-server-side-encryption-for-amazon-kinesis-streams/
but its new fields are not displayed from `describe-stream` output.
1. Go to AWS Console
2. Create a stream `foo`
3. From stream's detail page, enable server-side encryption(select "(Default)aws/kinesis" for master key)
4. From CLI, run `$ aws kinesis describe-stream --stream-name foo  --debug`
Response body contains newely added 
- EncryptionType
- KeyId
```
{"StreamDescription":{"EncryptionType":"KMS","EnhancedMonitoring":[{"ShardLevelMetrics":[]}],"HasMoreShards":false,"KeyId":"arn:aws:kms:eu-west-1:...
```
but it's not displayed from CLI output.
Once this PR merged, the output should contain them
```
$ aws kinesis …
```
> Adding SSE related fields to Kinesis non_aggregate_keys

- botocore/utils.py
- tests/unit/test_utils.py
This causes generated skeletons to populate an example value for
enums that matches known possible values.
cc @stealthycoin @dstufft
> Generate example enum

- .changes/next-release/bugfix-Paginator-57048.json
- botocore/paginate.py
- tests/unit/test_paginate.py
This fixes a bug where we were not discarding the starting truncation
value in the paginator after the first request was made and truncated.
This resulted in having an inflated `boto_truncate_amount` value in
the pagination token. Successive calls would begin to drop results
starting at the third call.
cc @stealthycoin @dstufft
> Discard starting_truncation after first request

- botocore/docs/bcdoc/style.py
- tests/unit/docs/bcdoc/test_document.py
- tests/unit/docs/bcdoc/test_style.py
rst typically has links offloaded to another part of the document to
improve readability, but also allows directly embedded URIs. This
changes our doc behavior to always use embedded URIs because there
are several cases where the same string will have different targets
throughout a page. Since these rst files are immediately converted
to html or some other format, it isn't important to make them super
pretty.
Fixes #863
cc @stealthycoin @dstufft @joguSD
> Always use embedded URIs

- .changes/next-release/bugfix-Paginator-68981.json
- botocore/client.py
- botocore/paginate.py
- tests/functional/test_route53.py
- tests/unit/test_paginate.py
Route 53 has defined their `MaxItems` pagination field as a string which leads to issues when passing the `page-size` flag to the cli as it will convert the value to an integer. This PR adds a hook to automatically convert the `MaxItems` field back into a string in the case that the operation expects it to be a string.
Fixes: https://github.com/boto/botocore/issues/1063
@JordonPhillips @stealthycoin @kyleknap @jamesls @dstufft
> Fix Route 53 pagination when string MaxItems is expected

- botocore/docs/sharedexample.py
- botocore/docs/utils.py
- tests/unit/docs/test_sharedexample.py
- tests/unit/docs/test_utils.py
Some shared examples have escape characters in them that get interpolated and rendered into the generated documentation which causes issues when we hand it off to sphinx.
Before:
After:
> Fix escaped characters in shared example doc generation

- .changes/next-release/bugfix-Paginator-865.json
- botocore/data/athena/2017-05-18/paginators-1.json
The paginator for Athena's GetQueryResults was pointing to the top level structure `ResultSet` rather than the aggregate key `ResultSet.Rows`. In fixing this I added a functional test that verifies all `result_key`s defined in a paginator config point to a type that we can support aggregation for. There are currently 3 paginators that have a `result_key` that point to a type that we do not support aggregation for, hence why the travis build fails. 
1) Apigateway's [GetUsage](https://github.com/boto/botocore/blob/8e809c053dcccb03b0a563392f2e4fcc6d992071/botocore/data/apigateway/2015-07-09/paginators-1.json#L51) `items`. [Return structure](http://botocore.readthedocs.io/en/latest/reference/services/apigateway.html#APIGateway.Client.get_usage)
2) Devicefarm's …
> Athena GetQueryResults pagination fix

- botocore/docs/bcdoc/style.py
- tests/unit/docs/bcdoc/test_style.py
Sphinx will throw warnings if you have two uri's with the same name
but different targets because it helpfully assumes your intent was
to make an embedded uri global. This add an additional underscore to
the end of those links to make Sphinx treat them as 'anonymous'.
The links do still work properly without this change, but the CLI
will spit out warnings without it, which is not a great customer
experience.
Fixes #1268
Fixes aws/aws-cli#2786
> Make links anonymous

- .changes/next-release/feature-Waiter-54293.json
- botocore/docs/waiter.py
- botocore/waiter.py
- tests/unit/docs/test_waiter.py
- tests/unit/test_waiters.py
Adding so we can properly address https://github.com/aws/aws-cli/pull/2761
This will allow `WaiterConfig` to be passed to `waiter.wait()` calls allowing customers to adjust waiter's `maxAttempts` and `delay` settings. This is based on how `PaginationConfig` works. The current keys are formatted to match the waiter models.
```
waiter.wait(WaiterConfig={
'delay': 5,
'maxAttempts': 5,
})
```
> Expose waiter configuration

- tests/integration/test_smoke.py
CloudHSM v1 is slowly being phased out, so our smoke tests will begin
to error out since we don't persist the necessary setup to continue
uninterrupted.
> Remove CloudHSM v1 smoke tests

- botocore/session.py
This makes it easier to diagnose where configuration values come from when a user is getting a value they did not expect.
> Log the configuration values and where they came from

- .changes/next-release/bugfix-serializer-59361.json
- botocore/serialize.py
- tests/unit/protocols/input/ec2.json
- tests/unit/protocols/input/query.json
Query requests should have a header of
application/x-www-form-urlencoded; charset=utf-8. The vendored version
of requests adds the header
application/x-www-form-urlencoded after our serialization step
but does not add the charset which causes some requests with unicode
content to fail with a signature error.
closes #1244 
cc @jamesls @kyleknap @JordonPhillips @dstufft @joguSD
> Add explicit Content-Type header for Query requests

- .changes/next-release/bugfix-Paginator-68040.json
- botocore/paginate.py
- tests/functional/test_paginate.py
This initializes `next_token` with the value that is in the starting
token when a page iterator is created. This allows it to properly
pass on any previous service pagination token.
> Hydrate pagination parameters with StartingToken

- botocore/docs/bcdoc/style.py
- botocore/docs/method.py
- botocore/model.py
- tests/unit/docs/bcdoc/test_style.py
- tests/unit/docs/test_method.py
- tests/unit/test_model.py
This adds a warning message to the documentation that hopefully makes it easier to notice deprecated operations and discourage their use.
> Add warning to documentation for deprecated operations

- botocore/client.py
Example log:
```
2017-10-13 16:54:49,583 botocore.client [DEBUG] Warning: s3.GetBucketLifecycle() is deprecated
```
> Log a warning when calling a deprecated operation

- .changes/next-release/bugfix-sigv4-42389.json
- botocore/auth.py
- tests/unit/auth/test_signers.py
This strips out the port on the host header if using the default port
80. It also strips out the http username and password. That was being
included because urlsplit returns it as part of the netloc.
Fixes aws/aws-cli#2883
> Sanitize sigv4 canonical host header

- botocore/data/ec2/2016-11-15/paginators-1.json
This PR adds the paginator for DescribeSecurityGroups. Right now it looks like a couple tests in boto3 are failing because this paginator is missing.
> adding missing SecurityGroups paginator

- botocore/credentials.py
- tests/unit/test_credentials.py
This moves the cached credential fetcher to enforcing iso format
rather than relying on a hand-rolled format string. This is important
on Windows, where our format string can produce strings that we
can't parse.
> Enforce ISO8601 format in cached refresher

- .changes/next-release/feature-credentials-59288.json
- botocore/credentials.py
- tests/functional/test_credentials.py
- tests/functional/utils/__init__.py
- tests/functional/utils/credentialprocess.py
- tests/unit/test_credentials.py
This allows users to configure an external process to provide
credentials using the `credential_process` config variable.
Note that this is built on top of the assume role provider since
there is rebasing necessary.
> Add support for process-based credential providers

- .changes/next-release/enhancement-Response-34923.json
- botocore/response.py
- tests/unit/test_response.py
Fixes #1309 
We currently throw an exception if you attempt to read zero bytes from the StreamingBody wrapper. This fixes the validation conditional to only validate the content length if we received an empty chunk and the amount requested was greater than zero.
> Allow reads of zero in StreamingBody

- .changes/next-release/bugfix-Credentials-62433.json
- botocore/credentials.py
- tests/unit/test_credentials.py
Previously we had just been stripping colon and path sep, but forward
slash will also break on Windows.
Fixes aws/aws-cli#2978
cc @kyleknap
> Always strip / from cache file names

- .changes/next-release/bugfix-Credentials-48253.json
- botocore/credentials.py
- tests/unit/test_credentials.py
This reduces the cache key size by switching the hashing algorithm
to sha1 and removing the arn.
Closes aws/aws-cli#2983
> Reduce cache key size

- .changes/next-release/bugfix-Credentials-49467.json
- botocore/compat.py
- botocore/credentials.py
- tests/unit/test_compat.py
This implements splitting on Windows properly, as shelex.split only
works correctly for posix systems.
> Split properly on Windows

- botocore/data/_retry.json
According to http://docs.aws.amazon.com/amazonglacier/latest/dev/api-error-responses.html, Glacier replies with a RequestTimeoutException when the upload takes too long. Since this could be due to network conditions, it makes sense to retry in this case.
> Add retry for Glacier RequestTimeoutException

- tests/integration/test_credentials.py
This adds 'AccessDenied' to the list of expected assumerole exceptions.
The api will *usually* return 'InvalidClientTokenId', but not always.
> Expand expected assumerole exceptions

- .changes/next-release/bugfix-Stubber-65181.json
- botocore/exceptions.py
- botocore/stub.py
- tests/functional/test_stub.py
- tests/unit/test_stub.py
This PR introduces an `UnStubbedResponseError` class which is raised when an instance of the Stubber class's  stub queue is exhausted.  This came about as a result of writing tests, and receiving an unhelpful message informing me that there was an unexpected API call.  
I found this unhelpful because it masked the fact that the `stubber` instance had no additional requests it was expecting.  This change gives a more specific error message as to why the request failed.
> Finer grained stub error handling

- .changes/next-release/enhancement-credentials-15604.json
- botocore/credentials.py
- tests/__init__.py
- tests/unit/test_credentials.py
This moves the file cache to botocore and allows users to set their
own cache via `create_credential_resolver`.
Future work: allow setting this via the config file and/or some other
easy method of configuration.
Closes #1157
> Move JSONFileCache to botocore

- .changes/next-release/bugfix-presignedurl-90814.json
- botocore/auth.py
- botocore/signers.py
- tests/__init__.py
- tests/functional/test_sts.py
- tests/unit/auth/test_signers.py
- tests/unit/test_signers.py
This deletes the content-type header from query requests which are
being presigned. Specifically it removes the auto-set value
"application/x-www-form-urlencoded; charset=utf-8" because that
value is not valid for presigned urls.
> Remove content-type from presigned query requests

- .changes/next-release/enhancement-cloudformationgettemplatetemplatebodyordering-86054.json
- botocore/handlers.py
- tests/unit/test_handlers.py
The TemplateBody is loaded from a string into a JSON dictionary which
did not preserve order. Instead use an OrderedDict to prserve the
template ordering.
cc @jamesls @kyleknap @dstufft @JordonPhillips @joguSD
> Enforce ordering on CloudFormation get_template TemplateBody

- botocore/docs/bcdoc/style.py
- tests/unit/docs/bcdoc/test_style.py
This adds support for linking to internal pages using the doc
directive for html, with a text fallback for other formats such
as manpages where that isn't supported.
> Add internal link support to doc generator

- .changes/next-release/enhancement-Credentials-29882.json
- botocore/credentials.py
- tests/functional/test_credentials.py
We attempt to blindly treat a profile as an assume role if the profile doesn't have static credentials. This adds extra validation to ensure that a source profile has either static credentials or a role.
> Improve error message when source profile is misconfigured

- .changes/next-release/enhancment-Paginator-15272.json
- botocore/data/alexaforbusiness/2017-11-09/paginators-1.json
- botocore/data/cloud9/2017-09-23/paginators-1.json
- botocore/data/clouddirectory/2016-05-10/paginators-1.json
- botocore/data/cloudhsmv2/2017-04-28/paginators-1.json
- botocore/data/codecommit/2015-04-13/paginators-1.json
- botocore/data/comprehend/2017-11-27/paginators-1.json
- botocore/data/dms/2016-01-01/paginators-1.json
- botocore/data/ds/2015-04-16/paginators-1.json
- botocore/data/es/2015-01-01/paginators-1.json
- botocore/data/glue/2017-03-31/paginators-1.json
- botocore/data/inspector/2016-02-16/paginators-1.json
- botocore/data/lex-models/2017-04-19/paginators-1.json
- botocore/data/logs/2014-03-28/paginators-1.json
- botocore/data/mobile/2017-07-01/paginators-1.json
- botocore/data/mturk/2017-01-17/paginators-1.json
- botocore/data/organizations/2016-11-28/paginators-1.json
- botocore/data/rekognition/2016-06-27/paginators-1.json
- botocore/data/resource-groups/2017-11-27/paginators-1.json
- botocore/data/sagemaker/2017-07-24/paginators-1.json
- botocore/data/servicecatalog/2015-12-10/paginators-1.json
- botocore/data/servicediscovery/2017-03-14/paginators-1.json
- botocore/data/ses/2010-12-01/paginators-1.json
- botocore/data/ssm/2014-11-06/paginators-1.json
- botocore/data/workmail/2017-10-01/paginators-1.json
This adds paginators for a number of services where it was possible
to conclusively determine what the result key was. This only covers
cases where the result key was the only list in the operation
response and there were no structures or maps in the response.
> Add paginators for several services

- .changes/next-release/bugfix-Presign-62691.json
- botocore/client.py
- botocore/signers.py
- botocore/stub.py
- tests/functional/test_s3.py
- tests/functional/test_sts.py
- tests/functional/test_stub.py
- tests/unit/test_signers.py
Specifically ensure the following:
* The emission of `provide-client-params` event to hook in injection of parameters
* The emission of `before-parameter-build` event event to hook in internal customizations related to parameters such as SSE-C MD5 injection.
* Registering s3 accelerate handler to `before-sign` so s3 accelerate presigned url's can be created. It is important to note that I decided not to move the `request-created` event to the presigner because the signers are already hooked up to that event so re-emitting that event will cause the signers to get triggered again. Furthermore, putting it at `before-sign` is consistent with the handlers we use to change addressing style.
Fixes https://github.com/boto/botocore/issues/978
> Hook more events into presign functionality

- tests/integration/test_kinesis.py
There are two things I fixed:
* Poll up to 1 minute before data becomes available.
* Use unique data for payloads data.
The integ tests were technically wrong because they were checking
the first record's data, but given the test all share the same stream
and shard that data will depend on whatever test ran first.  In only
worked for now because the tests were all using the same first data
payload of "foobar".
> Improve reliability of kinesis integ tests

- .changes/next-release/enhancement-Stubber-50459.json
- botocore/stub.py
- tests/unit/test_stub.py
Extends stub's add_client_metadata method per https://github.com/boto/botocore/issues/1375
> support setting response metadata when adding client error to stub

- botocore/docs/bcdoc/style.py
- tests/unit/docs/bcdoc/test_style.py
This ignores empty markup tags like `<b/>` because writing them out may
lead to issues where rst thinks that markup is something else, such as a
heading.
Fixes aws/aws-cli#3152
> Ignore empty text markup tags

- requirements.txt
- setup.cfg
- setup.py
Version 2.7.0 of `python-dateutil` [dropped support for Python 2.6](https://github.com/dateutil/dateutil/pull/362).
> Tighten upper bound on python-dateutil version requirement

- .changes/next-release/enhancement-Credentials-75846.json
- botocore/utils.py
- tests/unit/test_utils.py
This allows customers to disable fetching credentials from IMDS by
setting `AWS_EC2_METADATA_DISABLED` to `true`.
> Allow disabling IMDS via env vars

- .changes/next-release/bugfix-Credentials-23327.json
- botocore/credentials.py
- tests/functional/test_credentials.py
Related to: https://github.com/aws/aws-cli/issues/3194
The issue occurred for the following scenario:
1) One thread secures the lock and goes through the initial refresh process
2) The thread with the lock sets the `self._access_key` and `self._secret_key`, but not yet `self._frozen_credentials`
3) The other threads call `refresh_needed()` and notice that since `self._access_key` and `self._secret_key` are set and the credential are not expired. As a result, they just return `self._frozen_credentials`.
4) However since `self._frozen_credentials` starts off as None and since `self._frozen_credentials` have not been set by the thread with the lock, the `DeferredRefreshableCredentials` returns None which causes the threads in this to raise a `NoCredentialsError` for those threads.
To fix …
> Fix race condition bug with deferred credentials

- .changes/next-release/bugfix-s3-16370.json
- botocore/utils.py
- tests/unit/test_utils.py
Attempting to redirect 400s when performing a head bucket or object is too generic and can cause infinite retries in some circumstances (bad credentials, incorrect SSE-C parameters). This updates the logic to only retry a 400 in the case that the request was previously redirected by `requests` upon receiving a `307` from the global s3 endpoint.
Closes #1400, boto/boto3#1482
> Make redirects for S3 head bucket and object more strict

- .changes/next-release/bugfix-s3-85294.json
- botocore/utils.py
- tests/functional/test_s3.py
- tests/integration/test_s3.py
- tests/unit/test_utils.py
This adds an alternate fix for https://github.com/boto/botocore/pull/1409 .  I've pulled in @joguSD's patch and added additional unit/integration tests.
The fix is to set a flag when we redirect the first time and verify we haven't previously redirected on subsequent requests.  I also added an integration test for the specific case mentioned in https://github.com/boto/botocore/issues/1400.
As for the regression caused from #1409, we need buckets with DNS propagated in order to actually test this, but I did write a one off integration test to verify this works as expected.  I don't think it makes sense to include in our main integration test suite, I think the unit/functional tests suffice.  If you're curious though, here's the test: …
> Prevent infinite loops when handling S3 region redirects

- requirements.txt
- setup.cfg
- setup.py
This updates dateutil to use version specific requirements and also updates nose to a version that fixes the stack limit bug on Python 3.6 (see [this issue](https://github.com/nose-devs/nose/issues/749)).
This also requires that we make changes to the CLI: https://github.com/aws/aws-cli/pull/3197
These must be merged at the same time.
Closes #1429, #1432, #1430
> Allow newer versions of dateutil

- botocore/history.py
Thread safety should be the responsibility of the handler as not all handlers may require a lock. I will be sending an additional PR to place a lock for the history record writer in the CLI.
> Remove the lock from the history recorder

- botocore/data/opsworks/2013-02-18/waiters-2.json
Removes an incorrect acceptor and syncs with what other SDKs use.  For example, see the waiters used in the javascript SDK: https://github.com/aws/aws-sdk-js/blob/master/apis/opsworks-2013-02-18.waiters2.json#L178
> Sync opsworks waiter from upstream

- .changes/next-release/enhancement-Credentials-28708.json
- botocore/utils.py
- tests/unit/test_utils.py
This ensures we do not look at proxy config even if
the HTTP(S)_PROXY env var is set.
This happens if we create the requests.Session for the user.
If a user provides a requests.Session (which isn't the default
behavior) then we do not mutate the provided session.
See: http://docs.python-requests.org/en/master/api/?highlight=trust_env#request-sessions
> Disable proxy config when fetching container credentials

- botocore/model.py
- tests/unit/test_model.py
It just maps to the `'ServiceId'` value in the service model metadata
> Expose service_id on service model

- botocore/data/appsync/2017-07-25/service-2.json
- botocore/data/clouddirectory/2017-01-11/service-2.json
- botocore/data/greengrass/2017-06-07/service-2.json
- botocore/data/iot-jobs-data/2017-09-29/service-2.json
- botocore/data/pinpoint/2016-12-01/service-2.json
- botocore/data/transcribe/2017-10-26/service-2.json
- tests/functional/test_endpoints.py
This changes the two tests to more closely map to what
we wanted to test when we originally wrote these tests.
These tests were written before serviceId existed, which
is really want we want to use for testing.  These tests check
two things:
* Ensure that the directory names (i.e the client names) match
the computed name based on the serviceId.  Existing services
still need overrides but new services shouldn't as many overrides.
* Update the endpoints tests to be more direct about endpoint prefix
matching.  We really just care that everything in the endpoints.json
maps to something we can create a client for.  We now build the
list of acceptable keys by looking up the endpoint prefix.
> Update endpoint test to use service ids

- botocore/response.py
- tests/unit/test_response.py
This way, we can readlines from a streaming body (without having to load
all bytes into memory!)
This will allow us to use StreamingBody in places where a Python
file-like object is expected.
(E.g. csv.reader!)
> Add line iterator to StreamingBody

- .changes/next-release/enhancement-StreamingResponses-49160.json
- botocore/response.py
- tests/unit/test_response.py
This pulls in https://github.com/boto/botocore/pull/1195 and incorporates review feedback [here](https://github.com/boto/botocore/pull/1195#discussion_r197903058).  The suggested changes make it similar to what requests exposes for its streaming responses.
I also added a few additional test cases.
> Add iter_chunks()/iter_lines() to StreamingBody

- botocore/data/_retry.json
Organizations uses status code 400 for TooManyRequestsException instead
of code 429.
fixes https://github.com/boto/boto3/issues/1588
> Add retry case for organizations

- botocore/session.py
- tests/functional/test_regions.py
- tests/unit/test_session.py
This allows for the addition of components to the session that should not be accessed outside of the botocore code. Marked `endpoint_resolver` and `exceptions_factory` as internal components. If accessed with `get_component()` a DeprecationWarning is raised.
> Add notion of internal components to session

- .travis.yml
- setup.py
- tests/unit/test_paginate.py
This updates the travis configuration to start running tests on python 3.7
as well as updating the tests to fix some issues related to PEP 479.
> Test on Python 3.7

- tests/functional/test_h2_required.py
The `assert_is` and `assert_in` methods aren't available on 2.6.
> Fix functional test on 2.6

- docs/source/_static/404.html
This is put in the static directory so that it is copied over, as
otherwise sphinx does not bring over anything but folders and rst
files.
> Add 404 page to doc source

- botocore/httpsession.py
- botocore/response.py
- tests/unit/test_http_session.py
The current version range we have doesn't support the `request_url` kwarg in all versions (only the latest 1.23 supports it). urllib3 v1.23 doesn't support Python 3.3 which means we can't rely on this for now. The downside is we get poor exceptions messages but I can fix this upstream in urllib3.
> Remove request_url kwarg as it's not support in all urllib3 versions

- tests/integration/test_client_http.py
These integration tests will fail if there isn't a region in the default profile or env vars. This adds an explicit `region_name` to ensure that they pass (in nearly all of these tests the region is irrelevant anyways).
> Add an explicit region_name to the http client integ tests

- botocore/auth.py
- tests/integration/test_client.py
- tests/integration/test_smoke.py
- tests/unit/test_auth_sigv4.py
Succeeds: https://github.com/boto/botocore/pull/1538
Basically, if the endpoint has mixed casing we sign using the mixed case but it's actually sent across the wire as all lowercase (this if the `Host` header is not explicitly set).
> Ensure the SigV4 signer signs the host as all lowercase

- .changes/next-release/enhancement-s3-12341.json
- botocore/handlers.py
- tests/integration/test_s3.py
- tests/unit/test_handlers.py
This is to support https://github.com/aws/aws-cli/pull/3549 which has the AWSCLI use ListObjectsV2 for operations that list buckets.
> Adding s3_list_objects_encoding_type_url handler to ListObjectsV2

- botocore/handlers.py
- botocore/model.py
- tests/unit/test_handlers.py
- tests/unit/test_model.py
Originally introduced in ba514720588c520fdf5ed0c77ddc76e4455246d0,
one of the tests was modified to have different behavior than intended.
The test is suppose to verify that without any of the needed
metadata properties we don't register a retry handler.
Right now, if a serviceId is missing you'll get an error message of
"NoneType" has no attribute "lower()".
With this change, you'll get the missing metadata error message
from models.py.
To help clarify this, I've changed the name of the test.  I also
added a repr to the Service class.  You now get:
```
$ aws s3 ls
"serviceId" not defined in the metadata of the model: ServiceModel(s3)
```
> Improve error message with missing service id

- botocore/handlers.py
- tests/unit/test_handlers.py
I was playing around with setting the EncodingType for ListObjectsV2, and I realized the S3 does not url encode the `ContinuationToken` in the response (even though the documentation says it does) and we should not url decode the `ContinuationToken` provided in the response.
Here is an example of what we are doing in the develop branch now with the CLI...
Just doing the initial `ListObjectsV2` call:
```
$ aws s3api list-objects-v2 --bucket mybucketfoo --max-keys 1
{
"Name": "mybucketfoo", 
"MaxKeys": 1, 
"Prefix": "", 
"KeyCount": 1, 
"EncodingType": "url", 
"NextContinuationToken": "1o1fF7/sfdyhcF61mG/KUupibYD3RDvBhH3TM9QHKloJ+oCr87Y19Ag==", 
"IsTruncated": true, 
"Contents": [
{
"LastModified": "2015-12-08T18:26:43.000Z", 
"ETag": "\"7f13278c420daa7ec3607db2c0962673\"", 
"StorageClass": …
```
> Do not url decode ContinuationToken

- .changes/next-release/enhancement-Event-36456.json
- botocore/awsrequest.py
- botocore/endpoint.py
- docs/source/reference/awsrequest.rst
- docs/source/topics/events.rst
- tests/__init__.py
- tests/functional/test_apigateway.py
- tests/functional/test_cloudsearchdomain.py
- tests/functional/test_cognito_idp.py
- tests/functional/test_history.py
- tests/functional/test_lex.py
- tests/functional/test_machinelearning.py
- tests/functional/test_neptune.py
- tests/functional/test_public_apis.py
- tests/functional/test_rds.py
- tests/functional/test_retry.py
- tests/functional/test_s3.py
- tests/integration/test_s3.py
- tests/integration/test_smoke.py
- tests/unit/test_awsrequest.py
- tests/unit/test_endpoint.py
- tests/unit/test_s3_addressing.py
This adds a `send-request` event which will allow an event handler to return a response and short circuit botocore's default HTTP stack.
This also adds a test utility to stub the HTTP layer and replaces quite a few places where we were patching out internal methods.
> Add the send-request event

- .changes/next-release/enhancement-HTTPSession-32204.json
- botocore/args.py
- botocore/endpoint.py
- botocore/httpsession.py
- tests/unit/test_args.py
- tests/unit/test_endpoint.py
- tests/unit/test_http_session.py
Adds an option to the shared config file to enable TCP Keep-Alive:
```
[default]
tcp_keepalive = true
```
> Add support for TCP Keep-Alive

- .changes/next-release/bugfix-InstanceMetadataFetcher-92647.json
- botocore/utils.py
- tests/unit/test_utils.py
Fixes: https://github.com/boto/botocore/issues/1403
Fixes: https://github.com/boto/botocore/issues/1049
Specifically with this we add the ability to retry on empty and invalid json credential responses. I also did quite a bit of refactoring on the `InstanceMetadataFetcher` to simplify it down. The behavior (except for the additional retry cases) should be identical in terms of how it currently got used in botocore. To help with the review, here are the places where I changed a code path:
* Eliminated [branch](https://github.com/boto/botocore/blob/17aa8d5674ab2fa429d9783983f6774118921717/botocore/utils.py#L295-L297) for if the first IMDS response returns something ending in a `\`. This was essentially dead code. If it were hit, it would have been a runtime error because it did not match …
> Update IMDS to fix some issues

- .changes/next-release/enhancement-TLS-71632.json
- botocore/args.py
- botocore/config.py
- botocore/endpoint.py
- botocore/httpsession.py
- tests/unit/test_args.py
- tests/unit/test_endpoint.py
- tests/unit/test_http_session.py
This allows the `cert_file` and `key_file` parameters to be passed through to the SSL context used when making HTTPS connections. This can be useful in `botocore` if a proxy requires a client certificate to authenticate. This is exposed on the client config as the `client_cert` kwarg.
```python
config = botocore.config.Config(client_cert='/path/to/cert')
config = botocore.config.Config(client_cert=('/path/to/cert', '/path/to/key'))
```
> Add client cert support to client config

- tests/__init__.py
- tests/integration/test_smoke.py
When porting this test over to the HTTP stubber I made an incorrect assumption.
The test previously would stub out the *first* request with an exception and then all subsequent requests would behave as normal. The way it's currently implemented the HTTP stubber will only allow two requests to be made, meaning if the second request fails for legitimate reasons the third retry attempt fails when it hits the stubber. Rather than throw a bunch of `None`s into the responses I've added a `strict` flag to the stubber which will allow only stubbing a subset of the requests to be made as is required by this test. 
Alternatively, I could implement a special handler for this test case specifically and not use the HTTP stubber.
> Add the strict flag to the test http stubber

- botocore/parsers.py
- tests/unit/test_parsers.py
When a HTTP response contain no body or the body field is None, botocore crashes with this error :
```
'NoneType' object has no attribute 'strip'
[ ...]
File "/[...]/dist-packages/botocore/parsers.py", line 237, in parse
if self._is_generic_error_response(response):
File "/[...]/dist-packages/botocore/parsers.py", line 270, in _is_generic_error_response
body = response['body'].strip()
```
The typical trigger for this error is a timeout that generate an internal http 599
> Properly handle error responses with null or not present body

- botocore/auth.py
When performing a SigV4 calculation we access the `AWSRequest.body` property many times which can potentially be expensive depending on the type of body being sent. This removes multiple calls to the body property to avoid calculating it many times, as the value doesn't change within the signer. 
This also removes an additional call to `prepare_body` that is no longer needed after some refactoring to how the body property works. The request is prepared in the `AWSPreparedRequest` constructor now meaning that calculating the `prepare_body` again is no longer needed.
Combined this reduces the number of times we prepare the body from 9 to 2, once when we calculate the signature and once when we actually send it. There's more profiling information in the linked issues.
Closes: #1478 
Fixes: …
> Improve prepare_body performance

- botocore/parsers.py
Starting with Python3.7, botocore issues the following warning:
```
/parsers.py:434: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
if value.getchildren():
```
Which is super annoying when working with CloudFormation as it pops up a lot.
Addresses: https://github.com/boto/botocore/issues/1537
> Fix annoying DeprecationWarning in parsers.py

- requirements.txt
- setup.cfg
- setup.py
This updates the accepted ranges of urllib3 to match what requests supports.
This also adds version specifiers so the bundled installer can determine which version of urllib3 to install.
I've created a bundled installer locally and tested that 2.6, 2.7, 3.3+ work with it.
Related CLI PR: https://github.com/aws/aws-cli/pull/3664
Closes #1583
> Update urllib3 version range

- botocore/credentials.py
- tests/unit/test_credentials.py
This will raise a somewhat more helpful error when refreshable credentials receive empty or partial credentials while attempting to refresh.
This doesn't solve boto/boto3#1751 per se, but it does make it a lot more obvious what happened.
> Raise better error when refresh fails

- botocore/session.py
- tests/unit/test_session.py
Before any config variables added using the old style with tuples
after a session had been initialized would support the methods
arugment on get_config_variable. However; the default botocore
config variables did not since they were loaded using the new method.
The assumption that if you were using the old method to set them then
you could use the old method to fetch them is not true since the CLI
depends on the methods argument when fetching botocore config
variables.
> Add property methods support for get_config_variable in session

- .changes/next-release/bugfix-sessionconfig-62324.json
- botocore/configprovider.py
- botocore/session.py
- tests/unit/test_session_legacy.py
The session.session_vars_map was a publicly accessible map that used to
have tuples that configured how variables were loaded, this map was
removed in favor of a new system. The new system is still in place but
the tuples have been put back so that they can be read from the session.
> Add the SESSION_VARIABLES back to the session object

- tests/unit/test_credentials.py
Without this patch, at least 2 tests failed in 2020 because their
'refreshed' credentials were still expired.
This PR was done while working on reproducible builds for openSUSE.
For that, we test that our packages can still give identical build results in the future, which is impossible if the build fails.
See https://reproducible-builds.org/ for why this matters.
> Make tests pass after 2020

- botocore/credentials.py
- tests/unit/test_credentials.py
Currently assume role support in profiles does not support setting the token duration. This means you cannot use this convenient feature if you need a token with a lifetime of something other than the default 3600 seconds. This PR addresses this by adding a duration_seconds option for the profile.
> Add support for duration_seconds in the profile for AssumeRole.

- botocore/data/route53/2013-04-01/paginators-1.json
Adding paginator support for list_vpc_association_authorizations in #1416 
```
>>> import boto3
>>> import botocore
>>>
>>> client = boto3.client('route53')
>>>
>>> client.can_paginate('list_vpc_association_authorizations')
True
>>> client.get_paginator('list_vpc_association_authorizations')
<botocore.client.Route53.Paginator.ListVPCAssociationAuthorizations object at 0x1022d8750>
```
> Adding ListVPCAssociationAuthorizations pagination (#1416)

- botocore/data/events/2015-10-07/paginators-1.json
There are currently no pagination definitions for CloudWatch Events APIs.
I've created them from the API Reference for this PR. The list of definitions now matches the API reference and also the list missing in #1462.
```python
client = boto3.client('events', region_name='eu-west-1')
paginator = client.get_paginator('list_rules')
page_iterator = paginator.paginate(NamePrefix='RDS', PaginationConfig={'PageSize': 2})
for page in page_iterator:
print(page)
```
> Add missing pagination definitions for CloudWatch Events

- botocore/data/appstream/2016-12-01/paginators-1.json
All but [describe_image_permissions](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/appstream.html#AppStream.Client.describe_image_permissions) were added because it returns both a `Name` and a `SharedImagePermissionsList` in the top-level. Not sure how to handle that.
> Add paginators for appstream

- botocore/exceptions.py
- botocore/handlers.py
- botocore/model.py
- tests/unit/test_handlers.py
- tests/unit/test_model.py
This gives a better error when the service id is missing from a
model. For example, if you called from the CLI you would currently
see an error like this:
```
$ aws secretsmanager help
'NoneType' object has no attribute 'replace'
```
Now you would see something like this:
```
$ aws secretsmanager help
The model being used for the service secretsmanager is missing the
serviceId metadata property, which is required.
```
> More specific service id error

- botocore/response.py
- tests/unit/test_response.py
The current code produces empty strings sometimes if the input file follows this unconventional and bizarre "\r\n" newline standard, that nonetheless is still found in some legacy systems. The proposed code tries to make sure whatever `splitlines()` understands as newline is supported.
This PR is the same as #1527, but rebasing after lots of changes upstream.
> Modified lines-from-chunks generator to ensure support for "\r\n"

- .changes/next-release/bugfix-Credentials-65605.json
- botocore/session.py
- tests/unit/test_session.py
Fixes #1472 
Fixes awslabs/awsprocesscreds#16
> Don't fetch creds for unsigned clients

- botocore/data/rds/2014-10-31/paginators-1.json
Looks like someone added a paginator for `DescribeDBClusters` but didn't add paginators for any of the other Cluster actions.
> Add missing RDS paginators

- tests/functional/test_paginator_config.py
Error messages now look like:
```
$ nosetests tests/functional/test_paginator_config.py -x
.............................................................................................................................................................F
======================================================================
FAIL: tests.functional.test_paginator_config.test_lint_pagination_configs(u'DescribeVolumes', OrderedDict([(u'input_token', u'NextToken'), (u'output_token', u'NextToken'), (u'limit_key', u'MaxResultsFoo'), (u'result_key', u'Volumes')]), ServiceModel(ec2))
----------------------------------------------------------------------
File ".virtualenvs/aws-cli/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File …
```
> Add better error message for unknown limit key

- botocore/data/ssm/2014-11-06/paginators-1.json
Adds paginator data for [DescribeAssociationExecutions](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ssm.html#SSM.Client.describe_association_executions) and [DescribeAssociationExecutionTargets](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ssm.html#SSM.Client.describe_association_execution_targets)
> Add paginator support for SSM Client Executions and ExecutionTargets

- tests/functional/test_paginator_config.py
Add test to ensure output shapes do not have any keys are un-referenced by a corresponding paginator.
> Add test for unreferenced output keys in a paginator

- botocore/response.py
- tests/unit/test_response.py
If a body is empty, `splitlines` will return an empty list. This
the remaining content before trying to split it.
Fixes #1661
> Check for empty body before splitting lines

- setup.py
Solves python3 bdist_wheel upload issue:
```
running upload
File "setup.py", line 82, in <module>
'Programming Language :: Python :: 3.7',
File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 131, in setup
return distutils.core.setup(**attrs)
File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
dist.run_commands()
File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
self.run_command(cmd)
File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
cmd_obj.run()
File "/usr/local/lib/python3.6/distutils/command/upload.py", line 64, in run
self.upload_file(command, pyversion, filename)
File "/usr/local/lib/python3.6/distutils/command/upload.py", line 162, in upload_file …
```
> classifiers needs to be an array

- botocore/config.py
While `int`s work fine here, it's not the native or most precise numeric type available for these. The requests and urllib3 libraries expect `float`.
> Adjust documentation to use floats for timeouts instead of ints

- tests/integration/test_s3.py
If assume role is used as the credential source for the integration tests this test will fail as the call to STS was also being picked up on. This updates the register to target `S3` after the `auth_path` has been set more specifically, which are the requests we're actually interested in.
For reference it would fail like this:
```
======================================================================
FAIL: test_thread_safe_auth (tests.integration.test_s3.TestS3Objects)
----------------------------------------------------------------------
File "/Users/.../python-sdks/botocore/tests/integration/test_s3.py", line 459, in test_thread_safe_auth
(self.auth_paths))
AssertionError: 11 != 10 : Expected 10 unique auth paths, instead received: …
```
> Fix s3 integ test when assume role is used

- tests/integration/test_s3.py
This copies over the logic to wait for an object's existence from the CLI and adds it to one of the base S3 integ test classes to make the integration tests a little more resilient to eventual consistency.
> Improve s3 integ test robustness

- botocore/model.py
- tests/unit/test_model.py
This came up when I was writing a test for an AWS CLI PR and needed min/max to be part of the models it was building.
> Check for all known metadata when building models

- botocore/credentials.py
- tests/unit/test_credentials.py
This PR fixes #1680.
From my comment on that issue:
> We deploy applications to Kubernetes using Terraform. For testing, we deploy on Minikube locally, which requires us to set the auth variables in Terraform. HCL still doesn't have conditionals, so they're always set - even when we use the same module to deploy to a k8s cluster in AWS which is intending to use IAM. As a result auth fails in the real deployment (since the env vars are set but are empty).
This happens even though IAM is configured properly.  I wrote this fix to deploy in our environment to mitigate this issue.
**This PR is dependent on #1680 being accepted to be fixed.**  As @joguSD says in that issue:
> I think this sounds reasonable but it's also arguably a breaking change / not a forwards compatible change. It might be …
> #1680 - Treat an empty auth environment variable as if it is unset

- LICENSE.txt
- NOTICE
Updated the license/notice format to match the typical usage. The license now contains the full license text and the copyright year is in the notice.
> Updating license/notice format

- botocore/data/_retry.json
- botocore/handlers.py
- tests/unit/test_handlers.py
The retry handlers that hook up to service-data-loaded
were added before botocore clients were added.  This results
in the client level retry handlers being a no-op if they were
already loaded (they use the same unique_id).
This means you can have subtly different behavior
depending on if you (or something else) calls
`session.get_service_data()`.
I also changed kinesis per-op to be per-service
The LimitExceededException doesn't apply to just
DescribeStream and the client-based retry handler
doesn't support per-operation retries.
This also ensures we continue to retry this
exception in kinesis for DescribeStream without
requiring per-operation retry functionality.
Fixes https://github.com/boto/botocore/issues/1698
> Remove duplicate retry handler registration

- setup.cfg
This change was already done in 3a6bd282 and related PR: https://github.com/boto/botocore/pull/1735
In previous PR, version of urlib3 has been modified in :
- `setup.py`
- `requirements.txt`
But not in `setup.cfg`, thus being not effective in some situations (cf details in https://github.com/boto/botocore/pull/1735#issuecomment-495153843).
This PR is trying to fix that.
> allow the use of urllib3 1.25.x (fix)

- botocore/httpsession.py
- tests/unit/test_http_session.py
Before if the Transfer-Encoding header was set, it would have no effect
on the request since chunked was still set to False in the urlopen
call. This change uses the value of the Transfer-Encoding header to set
the chunked parameter to urlopen.
> Support transfer-encoding chunked in urllib3

- requirements.txt
The requirements files are now only used for dependencies
needed for testing/dev.  All of the runtime dependencies of
botocore are specified via the setup files.
This also reduces the number of files we have to modify when
we bump our dependencies.
> Remove duplicate dependencies in requirements.txt

- botocore/vendored/requests/api.py
This adds a warning filter that ensures that the requests
deprecation warning is printed unless a user manually disables it.
> Show requests deprecation warning by default

- botocore/docs/paginator.py
- tests/unit/docs/test_paginator.py
Remove the PageSize param from the documentation when there is no limit_key in the api. This results in an exception if used.
> Remove paginator PageSize config when no limit_key

- tests/__init__.py
- tests/integration/test_client.py
- tests/integration/test_s3.py
This also adds a simple waiter class for use in our tests to help in cases where we need to wait for API to reach eventual consistency.
> Move S3 bucket versioning test to test_s3.py

- .changes/next-release/bugfix-Paginator-26689.json
- botocore/paginate.py
- tests/functional/test_paginate.py
Botocore has support for its own starting token formats, the older
of which simply splits up necessary data with triple underscores.
This format has been deprecated for a while due to various
shortcomings, but there's still input support for it for backwards
compatibility. The last element in that token format should be an
integer, which indicates how far to slice into the response. The
problem is that some services have tokens which include triple
underscores, so we think it's that format but malformed. This fixes
the problem by passing the full starting token along if parsing
fails.
Fixes boto/boto3#1984
> Don't throw error for invalid old starting token

- botocore/data/_retry.json
Previously, we only retried the `ProvisionedThroughputExceededException` for DynamoDB. Now we will be retrying it for all services. The new services that this will encompass include TextTract, Rekognition, and Kinesis. In general, these services would throw this exception and the only way to get around it would be to retry or get your limits increased. So it made sense to retry it similar to what we do for DynamoDB. Furthermore, the other SDK's retry ProvisionedThroughputExceededException across all services already so we would be more consistent with the other SDK's as well.
> Generally retry provisioned throughput exceptions

- .changes/next-release/enhancement-CSM-70687.json
- botocore/configprovider.py
- botocore/session.py
- tests/unit/test_session.py
This adds support for a configurable host when using client side metrics.
> Support CSM host configuration

- tests/__init__.py
- tests/integration/test_s3.py
This adds two fixes:
* Use a new client (and new connection) each time we poll.
* Add an initial delay where we can optionally wait a fixed amount
of time before we start polling.
> Fix flaky s3 botocore tests

- botocore/credentials.py
- tests/functional/test_credentials.py
- tests/unit/test_credentials.py
This is a continuation of #1770.
This updates the previous to PR to move away from partials to a more proper object to construct credential providers that can vary based on the profile. This new object allows us to share the building logic between how the default credential chain is created and the source profile chain is created within the `AssumeRoleProvider`.
> Refactor how assume role pulls credential from source_profile

- botocore/utils.py
Already a condition exists for checking bucket name length<3 so this is not necessary to add another condition for checking length=1.
Fixes: #1785
> Removed code for checking bucket name length=1 in check_dns_name

- .changes/next-release/bugfix-S3-605.json
- botocore/handlers.py
- tests/integration/test_s3.py
This applies the same automatic encoding and decoding on ListObjects
to avoid parsing errors when there are problematic characters for our
XML parser.
> Fix list object versions encoding

- .changes/next-release/enhancement-Credentials-6656.json
- botocore/credentials.py
- botocore/data/_retry.json
- botocore/utils.py
- tests/__init__.py
- tests/functional/test_credentials.py
- tests/functional/test_utils.py
- tests/unit/test_credentials.py
The web identity provider uses the full config off of the session
instead of relying on the session's get_config. While the new config
system in session is nice it has two major probles that make it
unsuitable for this use case:
1) If a profile is statically configured we need to ignore the
environment variables for that configuration. While it is possible to
use the methods kwarg, it's extremely inefficient.
2) The larger blocker is that this provider needs to support loading
configuration from a profile that is not the currently configured
profile for a session (e.g. when used as a source_profile in an assume
role chain). This is not trivial to add to the session's get_config and
doesn't really fit into the way it is designed.
Using the full config is what the other profile based …
> Add AssumeRoleWithWebIdentity credential provider

- requirements-docs.txt
- requirements.txt
- setup.cfg
- setup.py
Docutils have release version 0.15.2 creating conflicts.
This PR bumps docutils from < 0.15 to 0.16.
#1789
> i#1789: Bump docutils to <0.16 due to conflict

- tests/functional/test_waiter_config.py
Assert something is Falsy is not specific enough. If the waiter is doing a ``length`` check, it is possible for ``False`` to be returned back. Really what we want to be checking here is that ``None`` is not returned back as that indicates the JMESPath expression did not find anything that matched.
> Update waiter test to assert for None

- tests/integration/test_ec2.py
The EC2 API was returning us empty result lists with next tokens
> Assert page size return less than or equal to amt

- tests/integration/test_smoke.py
The minimum length of this id is 10. If that is every enforced on the
client side it would cause this test to start failing.
> Increase length of fake directory identifier

- .changes/next-release/enhancement-sts-29751.json
- botocore/args.py
- botocore/client.py
- botocore/configprovider.py
- botocore/credentials.py
- botocore/data/endpoints.json
- botocore/data/sts/2011-06-15/service-2.json
- botocore/exceptions.py
- botocore/session.py
- tests/__init__.py
- tests/functional/test_credentials.py
- tests/functional/test_sts.py
- tests/unit/test_args.py
To override the use of the global endpoint, set the `sts_regional_endpoints` config file variable or the `AWS_STS_REGIONAL_ENDPOINTS` environment variable to `regional`.
> Add sts regional endpoint configuration support

- tests/integration/test_client_http.py
These tests can fail if credentials are sourced from assume role, as the clients may try to make unexpected API calls.
> Make HTTP Client integ tests more resilient

- tests/functional/test_endpoints.py
This service has released in other SDKs but requires HTTP/2 support. This whitelists this service as known despite not being supported in our SDK.
> Allow transcribe streaming endpoint

- setup.cfg
- setup.py
Version 2.8.1 and higher require a new version of setuptools,
due to moving all the setup() metadata into a setup.cfg file.
If you try and use the bundled installer for the AWS CLI, it won't
build the wheel file properly:
```
running bdist_wheel
running build
installing to build/bdist.macosx-10.12-x86_64/wheel
running install
running install_egg_info
running egg_info
writing UNKNOWN.egg-info/PKG-INFO
writing top-level names to UNKNOWN.egg-info/top_level.txt
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.py[co]' found anywhere in …
```
> Cap upper version of python-dateutil to 2.8.0

- botocore/credentials.py
- botocore/exceptions.py
- botocore/utils.py
- tests/__init__.py
- tests/functional/test_credentials.py
- tests/unit/test_credentials.py
- tests/unit/test_utils.py
Initial support for SSO credentials
This implements an SSO token fetcher class that will retrieve an access token from SSO using the device authorization flow. This token can then be cached and used to fetch AWS credentials.
> Initial support for SSO credentials in botocore v2

- tests/integration/test_smoke.py
In the case of a throttle error we want to slow down our
request sending rate moreso than exponential backoff.  This
commit adds a fixed 10 second minimum delay along with exponential
backoff of 2 ^ retry_attempt seconds.
Verified I could see log messages and expected delays when running these tests in a loop:
```
tests.integration.test_smoke: DEBUG: Using custom retry delay of: 11
```
> Use slower delays for smoke test throttle errors

- botocore/utils.py
- tests/unit/test_utils.py
The client IDs are currently cached globally but need to be cached
on a per region basis. This updates the caching scheme to include
the region name.
This also cleans up some leftover constants / comments.
> Regionalize cached SSO OIDC client IDs

- botocore/data/resource-groups/2017-11-27/paginators-1.json
This API has added a new list to the result that needs to be paginated. This paginator was added in https://github.com/boto/botocore/pull/1345 as part of a mass auto-generated import and only exists within botocore.
> Add GroupIdentifiers to ListGroups result_key list

- botocore/utils.py
- tests/unit/test_utils.py
https://github.com/aws/aws-cli/issues/4682
https://github.com/boto/botocore/issues/1892
> Revert IMDS changes

- botocore/args.py
- botocore/config.py
- botocore/configprovider.py
- botocore/exceptions.py
- botocore/signers.py
- tests/functional/test_s3.py
- tests/functional/test_stub.py
- tests/integration/test_s3.py
- tests/unit/test_s3_addressing.py
- tests/unit/test_signers.py
This removes the legacy S3 endpoint regional configuration and defaults to always use the regional endpoint.
> Remove legacy S3 regional endpoint configuration

- botocore/client.py
- tests/functional/test_regions.py
- tests/integration/test_s3.py
- tests/unit/test_client.py
We originally introduced this to work around a py26 bug
where it couldn't read subjectAltNames for certs over a certain
size.  We now no longer need this due to py26 being dropped,
and v2 is a natural place to change these endpoints over.
As part of this change I had to update the functional test
for regions.  The main test generator was being shadowed by another
test name so as a result these tests were never actually running.
I had to update these tests to handle other endpoint related changes
we made (regional STS, S3 us-east-1, `s3.region` instead of
`s3-region`).
> Do not use sslCommonName from endpoint data

- setup.cfg
- setup.py
urllib3 dropped support for python 3.4 in version 1.25.8:
https://github.com/urllib3/urllib3/blob/master/CHANGES.rst#1258-2020-01-20
> Add branching requirement for urllib3

- botocore/configprovider.py
- tests/functional/test_session.py
- tests/unit/test_session_legacy.py
* Add support for `AWS_REGION`, which is supported in all SDKs
except python/cli.
* Change precedence to prefer `AWS_<VAR>` before `AWS_DEFAULT_<VAR>`.
> [v2] Standardize profile and region env vars

- botocore/client.py
- botocore/exceptions.py
- botocore/retries/adaptive.py
- botocore/retries/bucket.py
- botocore/retries/throttling.py
- tests/functional/retries/test_bucket.py
- tests/functional/retries/test_quota.py
- tests/unit/retries/test_adaptive.py
- tests/unit/retries/test_bucket.py
- tests/unit/retries/test_throttling.py
This adds a new experimental retry mode, `adaptive`, that adds
support for client side rate limiting based on receiving
throttling responses.  `adaptive` mode includes all the behavior
on `standard` mode.
> [v2] Add support for adaptive mode retries

- .changes/next-release/enhancement-timezones-38018.json
- botocore/compat.py
- botocore/utils.py
- tests/unit/test_compat.py
- tests/unit/test_utils.py
Issue #1939 draws attention to an `OSError` that is raised on Windows in some timezones when `botocore.utils.parse_timestamp` relies on `tzlocal()` instead of using `tzwinlocal()` during this operation:
```python
datetime.datetime.fromtimestamp(value, tzlocal())
```
The **dateutil** maintainers are aware of this interoperability issue and have created issue [#848](https://github.com/dateutil/dateutil/issues/848) against **dateutil** to propose a change to make `tz.gettz()` conditionally return `tzwinlocal()` on Windows.
@pganssle discusses this motivation in [this comment](https://github.com/dateutil/dateutil/issues/197#issuecomment-448681838):
> I think my preferred solution to the very real UX challenge you have identified, @h-vetinari, is to make tz.gettz() return tz.tzwinlocal instead …
> Prefer tzwinlocal over tzlocal in parse_timestamp to handle negative timestamps

- botocore/handlers.py
- botocore/parsers.py
- tests/functional/test_s3.py
There are some operations where S3 streams data to us to keep a connection alive while waiting for a long running operation to complete. In cases where the client drops the connection or has other intermittent network connection issues, we need to be more resilient.
This patch will attempt to retry these cases where they're recoverable, and prompt the client application to retry the operation again if we're unable to recover. This will also avoid leaking exceptions from the underlying xml library which we'd been doing before in these rare cases.
> Handling S3 connection drops

- .changes/next-release/enchancement-Endpoints-29513.json
- botocore/client.py
- botocore/regions.py
- tests/functional/test_client_metadata.py
- tests/functional/test_regions.py
- tests/functional/test_route53.py
- tests/functional/test_s3.py
- tests/functional/test_sts.py
When a client is handed an unresolvable region, we create an assumed regionalized endpoint and send a request hoping it will work. In many cases, it won't and results in extra wait time for the connection, followed by an exception. 
This patch will change the behavior to instead validate if the service being called is regionalized. If not, we can fall back to the global endpoint and continue with the call. This should prevent unnecessary failures in cases where the region isn't relevant to the service request.
> fix endpoint resolution with unknown regions

- botocore/exceptions.py
Fix the typo `invaild` -> `invalid` in some exception messages.
> Fix typos on messages

- botocore/signers.py
- tests/unit/test_signers.py
Fixes https://github.com/boto/boto3/issues/1103
> Don't modify original condition for s3 generate_presigned_post

- botocore/session.py
The docstring of `Session.user_agent()` says the `user_agent_name` attribute is "Boto" by default, however `__init__` is actually setting it to "Botocore". Fix the docstring to reflect the real default value.
> Fix Session.user_agent docstring

- botocore/handlers.py
- botocore/model.py
- botocore/serialize.py
- botocore/utils.py
- tests/functional/test_s3.py
- tests/unit/test_handlers.py
Converting our historic hardcoded handlers for s3 operations that require a checksum to using new modeled trait. This will allow dynamically updating which calls calculate and include this metadata, avoiding manual code updates.
Note: We'll be leaving the handlers for PutObject and UploadPart. These are optional in some SDKs but we'll be maintaining them as required for backwards compatibility.
> use httpChecksumRequired trait for S3 MD5 checksums

- tests/functional/retries/test_bucket.py
This test fails on travis occasionally, this loosens the assertion to make the test a little more robust.
> Loosen retry bucket functional test checks

- botocore/eventstream.py
- tests/unit/test_eventstream.py
This updates the low level event stream binary parser to correctly parse single byte integer header values as a signed integer instead of unsigned. All integer header values in event streams are signed integers. Thankfully no service currently sends single byte header values so this bug wouldn't have surfaced in any public interfaces.
> Properly parse event stream byte header values

- botocore/data/s3/2006-03-01/service-2.sdk-extras.json
- tests/functional/test_s3.py
This is a temporary workaround for a bug fix upstream in AWS CLI V2's cp functionality.
> Support RequestPayer for Get/PutObjectTagging

- botocore/exceptions.py
- botocore/session.py
- botocore/utils.py
- tests/unit/test_s3_addressing.py
- tests/unit/test_session.py
This PR will add some basic validation to the region_name parameter used to create new Session and BaseClient objects. The goal is to avoid accidentally setting up clients that will either never route, or lead to unexpected request routing. The change here will bubble up to boto3 in clients and resources, as well as the AWS CLI.
> Add basic region_name validation

- tests/functional/test_client.py
- tests/integration/test_client.py
This PR is moving a test class out of our integration tests and putting it in the functional directory where it belongs. We have a handful of tests in the code base that are getting missed on PRs and don't surface until after merge because they're misclassified as integration. This is the first step to get a common set moved over and will have follow up to migrate some of the other offenders.
> Move client creation integ tests to functional

- botocore/client.py
- botocore/configprovider.py
- botocore/discovery.py
- botocore/exceptions.py
- botocore/model.py
- tests/functional/__init__.py
- tests/functional/models/test-discovery-endpoint/2020-08-20/service-2.json
- tests/functional/test_discovery.py
- tests/functional/test_model_backcompat.py
- tests/unit/test_model.py
When using services with endpoint discovery as a requirement, botocore currently throws an exception by default. This was originally intended to prompt users to opt in for this feature. As more services start to use this, we're switching the default to use endpoint_discovery automatically when required and opt-out when it's optional. This will maintain backwards compatibility, but allow users to not have to worry about configuration in the common case.
You can still explicitly disable this behavior with `endpoint_discovery_enabled=False` in your Config object, or with the `AWS_ENDPOINT_DISCOVERY_ENABLED` environment variable. Similarly, it can be used in all requests where endpoint discovery is available (optional or required) when explicitly set to `True`.
> Update Endpoint Discovery to enable for required operations

- docs/source/index.rst
Current Botocore docs don't reflect the versions that are supported. Bringing things up to date.
> Update supported Python versions in docs

- botocore/response.py
- tests/unit/test_response.py
Reverts boto/botocore#2149. Some of the underlying s3 infrastructure isn't compatible with this change.
> Revert "implemented IOBase functions and included unit tests"

- botocore/discovery.py
- tests/functional/models/test-discovery-endpoint/2020-08-20/service-2.json
When performing setup on our `EndpointDiscoveryHandler`, we traverse our model to determine if any identifiers are required for performing endpoint discovery. This had previously only been done on operations where all members were required. In new releases, these members may become optional, requiring us to ignore them during setup.
This PR will properly scope model traversal in this case and avoid considering information that isn't relevant to the operation.
> Avoid traversing unused model during endpoint discovery setup

- .travis.yml
- setup.py
This branch is really only used for the CLI v2 which already only supports Python3.7+ so this will allow us to pull in more
dependencies that do not support those previous Python versions and also make our Travis builds faster.
> [v2-branch only] Only support Python3.7+

- .changes/next-release/feature-imds-87700.json
- botocore/configprovider.py
- botocore/credentials.py
- botocore/exceptions.py
- botocore/utils.py
- setup.cfg
- setup.py
- tests/unit/test_credentials.py
- tests/unit/test_utils.py
Enable user to set InstanceMetaDataFetcher endpoint to a custom IPv6 endpoint via environment variable or config file. Included additional functions to perform IPv6 URI validation.
> Add logic to configure IPv6 env var

- setup.cfg
- setup.py
- awscrt now accepts duck typed streams (rather than requiring inheritance from IOBase).
- fixes signing bug involving "X-Amz-Security-Token"
> update awscrt to fix bugs

- README.rst
As announced in today's blog post, Botocore will be deprecating support for Python 3.4 and 3.5 on 02/01/2021. Users are encouraged to migrate to Python 3.6 or later. This PR will update the README to alert users about the news.
Most users will not need to take action about botocore directly, and can follow steps directly for AWS CLI v1 or Boto3. For customers building directly on top of botocore, you may want to pin to a specific version prior to the deprecation date.
Full details can be found at: https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-python-3-4-and-3-5-in-the-aws-sdk-for-python-and-aws-cli-v1/
> Update deprecation notice to 3.4/3.5

- botocore/response.py
- tests/unit/test_response.py
Updated fix for https://github.com/boto/botocore/issues/879. Previous PR broke S3 integration tests. Object with underlying raw_stream was being destructed via GC. Overriding destructor to keep underlying stream.
> implemented IOBase functions and included unit tests

- setup.py
urllib3 released 1.26.0 today. This will raise our pin to avoid pip conflicts for users installing the latest version.
> Update pin for urllib3 1.26.0 release

- botocore/handlers.py
- botocore/utils.py
- tests/functional/test_s3.py
- tests/unit/test_handlers.py
This is a continuation of #1985 to resolve #1979. We're adding two additional tests to prevent future regression with empty bodies, and adding some more info on the underlying issue.
While the initial PR was addressing a lack of `Content-MD5` headers being added for empty files going to s3, the bug is little more subtle. Currently, using the low level API for `PutBucket` will ensure all input, regardless of length, is transformed into a file-like object. When this is passed to our MD5 checksum function, it will always be `True` and get the header added correctly. These always evaluate to `True` because `bool` resolves "truthiness" to be if the file-object exists or not.
The bug enters when the higher level s3 APIs are being invoked like `s3 sync` in the AWS CLI. This replaces our standard …
> Fix Content-MD5 header for s3transfer

- botocore/exceptions.py
Correct the spelling of `endoints` to `endpoint` when raising an Invalid IDMS Endpoint Error
> Correct the spelling of endpoints for the Invalid IDMS Endpoint Error

- .changes/next-release/bugfix-Retry-72000.json
- botocore/retries/standard.py
- tests/unit/retries/test_standard.py
The `standard` retry mode will attempt to introspect any parsed response
for a top level `"Error"` key. If present the standard retry strategy
assumes that the response is an error response and that there will be a
nested dictionary under the `"Code"` key. This assumption is not
generally safe as standard responses can also contain a top level
`"Error"` key.
Fixes https://github.com/aws/aws-cli/issues/5644
> Handle top level Error key for non-error responses

- botocore/args.py
- botocore/config.py
- botocore/endpoint.py
- botocore/httpsession.py
- tests/unit/test_args.py
- tests/unit/test_http_session.py
Starting with 1.26 urllib3 now supports HTTPS proxies. To enable the support two changes are needed:
* An additional ``proxy_kwargs`` argument that can be passed from client config. This dictionary will be used to pass any arguments needed to the underlying httpsession.
* The ``use_forwarding_for_https`` mode requires us to send the absolute URI when enabled.
> Add support for HTTPS proxies

- botocore/response.py
- tests/unit/test_response.py
This PR aims to add an optional `keepends` parameter to the `iter_lines` in `StreamingResponse`
From the python documentation `readline` and `readlines` should keep new line characters at the end of the string:
> f.readline() reads a single line from the file; a newline character (\n) is left at the end of the string, and is only omitted on the last line of the file if the file doesn’t end in a newline.
See https://docs.python.org/3/tutorial/inputoutput.html#methods-of-file-objects
Adding this option would make it easier to get this behavior for classes relying on `StreamingResponse`.
To not break the current implementation, this parameter is set to `False` by default.
> feat: Adds keepends option to iter_lines in StreamingResponse

- .changes/next-release/bugfix-SSO-69789.json
- botocore/credentials.py
- tests/unit/test_credentials.py
The timestamp format for SSO credentials was originally intended to be an [RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.6) style timestamp in UTC. Due to a typo in the original AssumeRole implementation, the timezone is being converted to `UTC` instead of a literal `Z`. We're going to correct the SSO implementation since the current timestamp is incompatible with the other AWS SDKs. The AssumeRole timestamp will be left unchanged for now to preserve as much backwards compatibility as possible.
Customers that are upgrading should have their timestamp format updated on their next login or credential refresh with SSO.
> Fix timestamp format for SSOCredentialFetcher

- botocore/credentials.py
- tests/unit/test_credentials.py
Adding in optional serialization function for `json.dumps` to allow modifications to ambiguous data types like `datetime`.
> Add JSON dumps callback to JSONFileCache

- botocore/awsrequest.py
- tests/unit/test_utils.py
Fall back to Transfer-Encoding 'chunked' if AWSRequest body is not seekable stream
> Fall back to Transfer-Encoding 'chunked' 

- .changes/next-release/feature-Python-10095.json
- .github/workflows/run-tests.yml
- CONTRIBUTING.rst
- README.rst
- setup.cfg
- setup.py
- tox.ini
This is a draft PR with the list of possible cleanup changes we can make with the deprecation of Python 3.4 and 3.5 on Feb 1, 2021. This should cover the full scope of 3.4/3.5 specific code but not all of these are strictly required. Looking for feedback before we merge.
> Add changes for Python 3.4/3.5 removal

- .changes/next-release/enhancement-s3-38374.json
- botocore/utils.py
- tests/functional/test_s3.py
- tests/functional/test_s3_control_redirects.py
- tests/unit/test_utils.py
This allows the S3 and S3 control clients to provide custom endpoints when providing arn based resources.
> S3 arn custom endpoint support

- .changes/next-release/bugfix-S3-86777.json
- botocore/handlers.py
- tests/functional/test_s3.py
This adds a customization for the S3 DeleteObjects operation to include some additional escaping of newlines to avoid XML normalization of newlines on the server side modifying the keys to be deleted. This is an issue with our XML serialization in general but currently only negatively impacts S3 DeleteObjects. Unfortunately, the stdlib XML serializer doesn't have a way to configure or opt into these escape sequences for the element text nor can we escape these prior to serialization as the escape sequences include characters that will be double escaped by the serializer. It might be worthwhile to implement our own version of `ElementTree.tostring` to give us finer control over the generated XML so we can properly implement this for our XML serializer in general.
> Escape line endings in S3 DeleteObjects requests

- botocore/utils.py
- tests/unit/test_utils.py
This adds support for the shape type `double` in argument generation. This ensures things like `--generate-cli-skeleton output` work as otherwise the stubbed response fails validation due to these values being generated as `None` instead of `0.0`.
> Add support for doubles in argument generation

- botocore/httpsession.py
- tests/unit/test_http_session.py
Updating usage of urllib3's SSLContext generation method when passed to our ProxyManager. This will now force the check_hostname functionality of the ssl module to be used in this case. This will fully mitigate this [urllib3 vulnerability](https://github.com/urllib3/urllib3/security/advisories/GHSA-5phf-pp7p-vc2r), regardless of urllib3 version used.
> Update check_hostname setting for proxy

- .github/workflows/run-crt-test.yml
- requirements.txt
- scripts/ci/install
- scripts/ci/run-crt-tests
- setup.cfg
- setup.py
**Note: This is a beta feature that will be seeing iteration in the near future and should not be considered "stable". We _strongly_ recommend not installing with "botocore[crt]" in a production environment. The current `extras_require` will not affect existing installations but will be used to enable features in future builds.**
This change will add basic setup for us to start adding opt-in features based on the [AWS CRT](https://github.com/awslabs/aws-crt-python). The extra currently has no effects on our infrastructure but allows us to start testing changes as we merge future PRs integrating with the CRT. Installation with this extra will be an "opt-in" to start replacing portions of SDK functionality with the unified C runtime for AWS SDKs.
More information on changes will be provided …
> Add extras_require for CRT

- .changes/next-release/bugfix-S3-62876.json
- botocore/handlers.py
- tests/functional/test_s3.py
See previous PR for background: https://github.com/boto/botocore/pull/2309
This applies the same customization to PutBucketLifecycleConfiguration
> Escape line endings in S3 PutBucketLifecycleConfiguration requests

- setup.py
Removing unnecessary pin cap for Python 3.4.
> Remove Python 3.4 urllib3 specifier

- requirements-docs.txt
Jinja2 3.0 drops support for python 3.5 and Sphinx doens't have a pin.
Markupsafe was also unbounded by jinja2, which means an incompatible
version is now pulled in and we need to put a ceiling pin on that as
well.
markupsafe>=1.1,<2.0
jinja2>=2.3,<3.0
> Pin jinja2 to <3.0

- botocore/httpsession.py
**Is your feature request related to a problem? Please describe.**
I am debugging an issue where S3 closes the connection during a download. To gather exact timing information, it would be useful to capture a network dump (e.g. tcpdump) and be able to inspect *inside* the TLS layer.
**Describe the solution you'd like**
A lot of applications (Firefox, Chrome) support the SSLKEYLOGFILE environment variable that will dump the needed key material in a standardized format to the given file. Since Python 3.8, Python supports this as well when using `ssl.create_default_context()`. Botocore, however, creates its own `SSLContext()` object, so this feature is not activated.
Would this be an acceptable feature to include in botocore?
References:
* https://pypi.org/project/sslkeylog/
* …
> Add support for SSLKEYLOGFILE environment variable

- botocore/docs/shape.py
- botocore/model.py
- botocore/parsers.py
- botocore/serialize.py
- botocore/validate.py
- docs/source/topics/document_type.rst
- docs/source/topics/index.rst
- tests/unit/protocols/input/json.json
- tests/unit/protocols/input/rest-json.json
- tests/unit/protocols/output/json.json
- tests/unit/protocols/output/rest-json.json
- tests/unit/test_validate.py
Introducing changes to handle document types. Enabling potential use of arbitrary JSON documents in request/response objects. Additional protocol testing included.
> Handling document types and adding C2J protocol tests

- setup.cfg
Removing the upgrade from today's release while CRT works out some issues.
> Revert "Bump CRT to 0.11.23"

- setup.cfg
Moving the version requirement for [AWSCRT](https://pypi.org/project/awscrt/) to 0.11.24
> Bump CRT to 0.11.24

- .changes/next-release/feature-Python-84589.json
- .github/workflows/run-tests.yml
- CONTRIBUTING.rst
- README.rst
- botocore/utils.py
- docs/source/index.rst
- setup.cfg
- setup.py
- tox.ini
As announced in our [blog post](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/) in January, and in warning messages since Botocore 1.20.0, we will be formally dropping support for Python 2.7 on July 15, 2021. This PR will make final changes required to remove references to Python 2.7, update testing infrastructure, and wheel generation settings.
For those looking to continue receiving updates after the deprecation date, we recommend following the instructions in our [blog post](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/) to upgrade to Python 3.6 or later.
> Drop support for Python 2.7

- botocore/configprovider.py
- botocore/credentials.py
- botocore/exceptions.py
- botocore/utils.py
- tests/unit/test_utils.py
Adding additional envvar `AWS_EC2_METADATA_SERVICE_ENDPOINT_MODE` to configure IMDS between IPv4 and IPv6. Remapping to `AWS_IMDS_USE_IPV6` to use the new envvar. Furthermore, updating IMDS IPv6 default address from link local to unique local address
> Updating IMDS with new IPv6 specs

- CONTRIBUTING.rst
Changes to paginators, waiters, and the service model should be made upstream. Changed guidance to open an issue to raise the problem instead of submit a change or PR.
> Update contributing guide for files under data directory.

- botocore/session.py
Fix the typo `sesssion -> session`.
> Fix typo: sesssion -> session

- .github/workflows/stale_issue.yml
Changes:
- Bumps the version to v4
- removes PRs from automatically closing
- Minor wording changes and formatting to messages
- Adjust labels in use: standardizing on `automation-exempt` instead of `auto-label-exempt`, add `needs-review` and `bug` to exemption list.
- Bump up minimum votes to 2
> revamp the stale issue bot.

- tests/integration/test_client_http.py
Disabling proxy test due to platform issues with CONNECT tunneling. Will revisit with alternative testing options for all platforms as this works outside of container based environments.
> Temporarily skip proxy test due to CodeBuild issues

- .changes/next-release/enhancement-TaggedUnions-30097.json
- botocore/docs/params.py
- botocore/model.py
- botocore/parsers.py
- botocore/validate.py
- tests/functional/test_tagged_unions_unknown.py
- tests/unit/protocols/output/rest-json.json
- tests/unit/protocols/output/rest-xml.json
- tests/unit/test_parsers.py
- tests/unit/test_validate.py
Introducing support of the `union` trait on structures. Following additions made:
- Input validation that checks that only one member is set on a Tagged Union structure.
- If a client receives an unknown member it will set `SDK_UNKNOWN_MEMBER` as the top level key, which maps to the name or tag of the unknown member.
> Tagged Union Support

- .github/workflows/run-tests.yml
- scripts/ci/run-crt-tests
- scripts/ci/run-integ-tests
- scripts/ci/run-tests
This is part of a series of PRs to standardize our test runner scripts for CI across the boto repos. This will work as a stepping block to getting us migrated to arbitrary test runners such as `pytest` that can be used on a per project basis.
> Rework test runners to centralized workflow

- scripts/ci/run-integ-tests
- scripts/ci/run-tests
- tests/__init__.py
Both nose and py.test will add the first parent directory it encounters that does not have a `__init__.py` to the `sys.path`. In our case, this is the root of the repository. This means that Python will import the `botocore` package from source instead of the installed wheel distribution. So the new environment variable provides
the option to remove the repository root from `sys.path` to be able to rely on the installed distribution when running the tests.
It is also worth noting that nose has `--no-path-adjustment` to fix this, but py.test does not have an option available without large refactorings of the tests.
> Remove repo root from path when running tests

- .github/workflows/run-tests.yml
- setup.py
- tox.ini
This PR will start testing us on what is hopefully the final release candidate for Python 3.10. Release is currently scheduled for October 4th, so we'll start regularly testing now to make sure things remaining functioning smoothly.
This PR does not update the run-crt-tests workflow due to wheel unavailability for CRT currently. We've opened awslabs/aws-crt-python#312 to track that request, and hopefully it will help create abi3 wheels which will avoid this issue in the future.
> Add support for Python 3.9 & 3.10

- tests/functional/test_s3.py
Adding simple test to codify we support this behavior with outpost arns in presigned URLs and to prevent any future regressions.
> Add Outpost Presigned Url Test

- botocore/parsers.py
From some recent feedback, we're making this message more explicit when receiving responses from external services. Tagged Union members MUST provide one and only one member in the response. Values such as `null`, `{}`, or multiple keys are not valid for the `union` trait.
> Update tagged union message with clearer description

- botocore/session.py
When CRT was first integrated into botocore, it didn't provide a way to easily access its version infromation. This resulted in using pkg_resources to introspect the information which is non-trivially expensive performing during client creation (it accounts for ~6% of the client creation time 😬).
I had introduced a patch to fix the issue in awslabs/aws-crt-python#268 which finally made it into CRT 0.11.14. We never revisited the issue though, so let's start using the `__version__` now.
> Start using __version__ instead of pkg_resources for awscrt

- .pre-commit-config.yaml
We're automatically adding an extra newline at the end of CHANGELOG.rst during each release. This is causing failures in our linter, so we'll ignore the file for now until that can be fixed.
> Remove CHANGELOG from linting check

- setup.cfg
- setup.py
This PR updates the botocore v2 branch to use awscrt 0.12.4, which supports the `HTTPS_PROXY` environment variable for S3 transfers when the `preferred_transfer_client` is set to `crt`
> Update awscrt version to 0.12.4

- .changes/next-release/enchancement-AWSCRT-92804.json
- .github/workflows/run-crt-test.yml
- setup.cfg
This patch will move us to use awscrt 0.12.5 which provides wheel support for Python 3.10.
> Upgrade to awcrt 0.12.5

- .github/workflows/run-crt-test.yml
- .github/workflows/run-tests.yml
- requirements-dev-lock.txt
- requirements-dev.txt
- scripts/ci/install
- scripts/ci/run-crt-tests
- scripts/ci/run-tests
- tests/functional/retries/test_bucket.py
- tests/functional/test_endpoints.py
- tests/functional/test_mturk.py
- tests/functional/test_rds.py
- tests/unit/auth/test_sigv4.py
- tests/unit/response_parsing/test_response_parsing.py
- tests/unit/test_credentials.py
- tests/unit/test_session.py
- tests/unit/test_session_legacy.py
This patch will fix some broken tests that were previously preventing running Windows in our CI tests for new PRs. This also adds support for parallelization with pytest-xdist to help compensate for the added time with new testing platforms.
> Add Windows support in CI

- botocore/docs/client.py
- tests/functional/docs/test_s3.py
- tests/functional/docs/test_secretsmanager.py
The generate_presigned_url is generically added to all clients but not all
services properly support presigned URLs. This adds a filtering mechanism to
generating client documentation and filters out documenting the method for all
clients but S3. The method is still present on all clients but will not be
documented unless we have confirmation that the service supports it.
> Hide generate_presigned_url for all clients but S3

- .changes/next-release/feature-six-62143.json
- botocore/vendored/six.py
Updating our vendored version of `six` with latest changes (1.16.0).  This should resolve any warnings for the time being with code that's still using these imports. This should address #2548.
> Update six from 1.10.0 to 1.16.0

- botocore/httpsession.py
This will update our vendored copy of urllib3's `create_urllib3_context` function. This updates our use of deprecated aliases for Python 3.10 and provides some security improvements in TLS 1.3 for Python versions 3.7.4+.
> Update create_urllib3_context to latest version

- .changes/next-release/bugfix-urllib3-31882.json
- botocore/httpsession.py
Fix for #2562, adding fallback for OP_NO_TICKET import for older versions of urllib3.
> Add fallback for OP_NO_TICKET import on older versions of urllib3

- botocore/parsers.py
- botocore/serialize.py
- tests/unit/protocols/input/rest-json.json
- tests/unit/protocols/input/rest-xml.json
- tests/unit/protocols/output/rest-json.json
- tests/unit/protocols/output/rest-xml.json
This updates the `rest-xml` and `rest-json` protocol serializers/parsers to support lists mapped to a header.
> Add protocol support for lists in headers

- botocore/exceptions.py
- botocore/response.py
- tests/unit/test_response.py
This PR should address boto/boto3#2902 by properly encapsulating deferred ProtocolError's raised by urllib3 when streaming responses. The new error `ResponseStreamingError` inherits from `HTTPClientError` since it's still fundamentally a networking issue that's been masked until read time.
> Properly catch ProtocolError on streamed responses

- botocore/endpoint.py
- botocore/utils.py
- tests/unit/test_endpoint.py
This patch should expand our support for endpoint URLs to include both ipv4 and ipv6 addresses. This should address boto/boto3#3086.
> Support IPv6 endpoint urls

- botocore/client.py
- botocore/exceptions.py
- botocore/response.py
- tests/unit/test_response.py
Fixing use of deprecated `warn` function on logger. This should clean up some of the warning clutter logged when running pytest.
> Fix deprecated warn usage

- .changes/next-release/enhancement-JSONFileCache-35511.json
- botocore/credentials.py
- tests/unit/test_credentials.py
This PR should address #2255 by adding the ability to programatically remove keys (and files) from the [JSONFileCache](https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L278).
> Add __delitem__ functionality to JSONFileCache

- botocore/args.py
- botocore/config.py
- botocore/configprovider.py
- botocore/data/sdk-default-configuration.json
- botocore/exceptions.py
- botocore/session.py
- botocore/utils.py
- tests/functional/test_config_provider.py
- tests/unit/test_args.py
- tests/unit/test_config_provider.py
- tests/unit/test_session.py
- tests/unit/test_utils.py
Adding support for `defaults_mode` client configuration option. The `defaults_mode` will be used to determine how certain default configuration options are resolved in the SDK. Configurations values impacted include: `retry_mode`, `sts_regional_endpoints` , s3 `us_east_1_regional_endpoint` and `connect_timeout`.
> Adding smart default support

- botocore/serialize.py
- tests/unit/protocols/input/rest-json.json
- tests/unit/protocols/input/rest-xml.json
Right now we end up serializing a list parameter into the headers as an empty string when we shouldn't be adding the header at all.
> Skip serializing empty lists in headers

- docs/source/topics/paginators.rst
Don't mind me, I spotted while working on an Sphinx linter.
For context, simple backticks in Sphinx are [default roles](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html), the Sphinx doc explicitly allows using default role for whatever you want, so I'm fixing nothing here.
But as it's the only default role in botocore whole doc it feels a small inconsistency that can be fixed.
> Dox fix: default role used.

- botocore/auth.py
- tests/unit/test_auth_sigv4.py
This commit adds brackets to IPv6 addresses in auth.py. Otherwise the signature is not calculated properly.
> Fix IPv6 endpoints with non-default port

- botocore/utils.py
- tests/unit/test_utils.py
When using `AWS_EC2_METADATA_SERVICE_ENDPOINT` or `ec2_metadata_service_endpoint`, we use the url as-is without checking how it's formatted. This leads to issues with appending an IMDS path for URLs that don't end in a trailing slash. Most users aren't going to think to add that when using the override and this causes unnecessary failures.
This fix will maintain the backwards compatibility of `get_base_url` while ensuring paths are constructed correctly.
> Tolerate custom IMDS endpoints without trailing slash

- .changes/next-release/enhancement-Requestheaders-37145.json
- botocore/endpoint.py
- botocore/handlers.py
- botocore/retries/standard.py
- botocore/retryhandler.py
- tests/functional/test_retry.py
- tests/unit/retries/test_standard.py
- tests/unit/test_endpoint.py
- tests/unit/test_handlers.py
- tests/unit/test_retryhandler.py
Adding the following request headers:
- `amz-invocation-id`: A uuid unique to each SDK request invocation.
- `amz-sdk-request`: Includes the following retry information for each SDK request: TTL, request attempt number, max number of retry attempts
> Adding retry information headers

- botocore/configloader.py
This will address the issue posed in aws/awscli#6696. Rather than modifying the existing exception flow, we'll use the `from None` syntax to swallow the underlying stacktrace for config parsing exceptions. This will prevent unnecessary information from being logged by default. Users who want this for debugging purposes will find it's still available under `.kwargs['error']`.
> Swallow underlying exception for config parsing

- README.rst
This PR will update badges, links, and the notice section with the most recent information.
Notable changes:
* Removal of links to Gitter due to lack of engagement and more widely adopted platforms
* Updated badges with Python support and licensing information.
* Added notice on end of support for Python 3.6 in May 2022.
> Update links and notices in README

- botocore/response.py
Hello,
I was rummaging through botocore to investigate how `StreamingBody`'s `iter_lines` worked, and noticed that this took `1024` as a default instead of the provided constant, so I thought I would make a PR. This is my first time making a PR here; I'm glad it's small.
Anyway, I ran the pre-commit and it worked out nicely:
```
pre-commit run --all-files
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
flake8...................................................................Passed
```
What do you think?
Regards,
SamV
> One-liner: Eliminate Magic Number as Default Argument to iter_lines method of StreamingBody

- botocore/args.py
Found while vendoring botocore for an internal dev tool.
> Fix: Add missing botocore.parsers import to botocore.args

- botocore/regions.py
- tests/unit/test_regions.py
Merging in additional endpoint data beyond `hostname`, `dnsSuffix` and `tags` for modeled endpoint variants
> Including additional endpoint data for modeled variants

- .changes/next-release/enhancement-Stubber-23740.json
- botocore/stub.py
- tests/functional/test_stub.py
- tests/unit/test_stub.py
This adds support for supplying any additional fields that may be present on a modeled exception's `response` field. The extra fields provided to `modeled_fields` will be validated against the shape if the particular error code is recognized, else the extra fields will be rejected as the error will be parsed as a generic `ClientError`.
Fixes: https://github.com/boto/boto3/issues/3178
> Support stubbing modeled exception fields

- .changes/next-release/enhancement-AWSCRT-43547.json
- setup.cfg
Update to the latest version of `awscrt`. This should resolve rare occurrences of `SignatureMismatchError` for SigV4a requests on Windows.
> Update awscrt to 0.13.7

- botocore/compat.py
- botocore/utils.py
When working with urllib3's vendored regexes for IP parsing, they're impossible to import directly into httpsession due to a circular reference between modules. The purpose of vendoring is to support older versions of urllib3 prior to their release. This falls more under compatibility and storing them in compat avoids the unnecessary import conflicts.
This should address the issue seen in #2652.
> Move IP regexes into compat to avoid circular imports

- .changes/next-release/feature-IMDS-63815.json
- botocore/credentials.py
- botocore/utils.py
- tests/unit/test_utils.py
Adding support for server side credential validation during IMDS outage scenarios. This patch will defer validation of credential expiry to the service for cases where IMDS may not be capable of receiving new metadata updates.
> Add support for IMDS credential extension

- botocore/compat.py
This removes our legacy compat shims for Python 2.7 since this code path is no longer reachable in supported Python versions.
> Remove unused compat shims

- botocore/response.py
- tests/unit/test_response.py
This is addressing a feature request originally made in https://github.com/boto/botocore/issues/1197. It allows the `StreamingBody` class to be instantiated as a context manager (i.e. able to use in a `with` statement). It's implemented in the standard way by adding `__enter__` and `__exit__` magic methods.
> allow StreamingBody class to be used as a context manager

- .changes/next-release/enhancement-StreamingBody-89.json
Adding missing changelog for https://github.com/boto/botocore/pull/2677
> StreamingBody context manager changelog

- .changes/next-release/enhancement-AWSRequest-24612.json
- botocore/auth.py
- botocore/awsrequest.py
- tests/unit/test_awsrequest.py
Addresses https://github.com/boto/botocore/issues/2667. Allows request parameters to be passed to the low level interface `AWSRequest` as a list of tuples (`params` attribute). Currently it can only accept dictionaries. This will also allow the user to send duplicate queries should they wish to do so.
> add list of tuples functionality to AWSRequest params attribute

- .changes/next-release/feature-Python-85983.json
- .github/workflows/run-crt-test.yml
- .github/workflows/run-tests.yml
- README.rst
- docs/source/index.rst
- setup.cfg
- setup.py
- tox.ini
**DO NOT MERGE PRIOR TO 5/30**
This PR will end support for Python 3.6 in Botocore as [announced](https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/#:~:text=Overview,deprecations%20which%20started%20in%202021) earlier this year. This PR will remove the testing scaffolding, update documentation, and remove any Python 3.6 specific code paths. This will need to be merged in conjunction with the other PRs in awscli, boto3, and s3transfer.
> Drop Python 3.6 support

- botocore/paginate.py
Addressing https://github.com/boto/botocore/issues/2396
While ideally we would add `next` functionality to `PageIterator` or simply update the name of the class to prevent confusion, both would cause breaking changes. As a result all we really can do is add a doc string with additional info. Perhaps using a warning here would be warranted, but decided against it.
Let me know if there's anything that should be added to the doc string.
> Add doc string to `PageIterator`

- botocore/config.py
- botocore/exceptions.py
Adding the variables corresponding to the options in the Retry config and the modes options.
Issue: [https://github.com/boto/boto3/issues/3300](url)
> Issue #3300: Adding variables for retry and modes options

- botocore/docs/method.py
Porting the fix from #2673 forward to account for customizations in resources where `self` may still be included in the function signature.
> Replace deprecated inspect.formatargspec() with inspect.signature()

- botocore/__init__.py
- botocore/session.py
- tests/unit/test_session.py
This adds an initialization hook to customize any botocore sessions.
Botocore sessions provide context for creating one or more clients.
It allows you to provide configuration, components, hooks, etc. that
can be shared across all clients created within that session.
There is no similar concept for sessions.  Specifically, there is no way
to provide a common set of configuration, components, hooks, etc. that
can shared across all sessions created within botocore.
This PR adds this initialization hook.  You can now register an initialization
callback that's invoked whenever a session is created:
```python
import botocore
def my_initializer(session: botocore.session.Session) -> None:
session.register_component('data_loader', MyNewCrazyLoader())
botocore.register_initializer(my_initializer) …
```
> Add initialization hook to customize botocore sessions

- .github/workflows/run-crt-test.yml
- .github/workflows/run-tests.yml
- requirements-dev-lock.txt
- requirements-dev.txt
- setup.py
This PR is the start of getting us prepared for Python 3.11's release in October. The codebase _should_ currently run without issue, but our tests are broken due to deprecations in inspect.signature(). There is an existing PR (#2673) that should unblock this and is now mergable now that the 3.6 deprecation is done.
We'll leave this as a draft until that's merged and then follow up on final testing at that time.
> Add formal suport for Python 3.11

- botocore/handlers.py
- tests/unit/test_handlers.py
This PR addresses https://github.com/boto/boto3/discussions/3268. Discussion about supporting SSE for all s3 ops was discussed, but the service only supports it for 11 out of its 97 APIs/ops.
A manual integration test was performed before and after registering the handler for `SelectObjectContent`. Before the same exception `botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the SelectObjectContent operation: Access Denied` was raised that the user in the original issue highlighted. After, the call succeeded.
> sse for SelectObjectCount s3 op

- .changes/next-release/enhancement-Endpoints-55727.json
Adding missing change log for #2704.
> Add change log entry for #2704

- NOTICE
This brings the NOTICE file up to date with our current vendored data. This was missed when Requests was removed from the library.
* Copy of Requests exception classes for backwards compatibility
* Copy of urllib3 exception classes for backwards compatibility
* Derivative copies of urllib3's rfc3986 URI regexes
* Copy of certifi certificate bundle from certifi 2018.01.18
> Update NOTICE file with current information

- .changes/next-release/bugfix-Config-29558.json
- botocore/handlers.py
- tests/unit/test_handlers.py
There was a typo in expected env var. It should be `_X_AMZN_TRACE_ID` and not `_X_AMZ_TRACE_ID`.
> Fix Trace ID environment variable

- .changes/next-release/bugfix-TraceId-89700.json
- botocore/handlers.py
- tests/unit/test_handlers.py
Reverts boto/botocore#2727
Redshift Data users running in Lambda get 500's not that the environment variable is being respected:
```
$ AWS_LAMBDA_FUNCTION_NAME=foo _X_AMZN_TRACE_ID=samcheck aws redshift-data list-statements --region us-east-1
An error occurred (InternalFailure) when calling the ListStatements operation (reached max retries: 4): 
```
> Revert "Fix Trace ID environment variable"

- README.rst
Updates the README.rst file to replace obsolete links to the old credentials and
shared settings guide to the new SDKs and Tools Reference Guide.
> Replace out of date credref URLs

- .changes/next-release/enhancement-Lambda-61491.json
- botocore/handlers.py
- tests/unit/test_handlers.py
This is a follow up to #2727 to fix the encoding scheme for our trace IDs. The change omits characters that cannot be encoded to preserve content semantics with services parsing the header.
> Fix encoding scheme for trace ids

- botocore/handlers.py
- tests/unit/test_handlers.py
Refactors the `set_operation_specific_signer` event handler to work independently of other S3-specific event handlers. This is in preparation for future changes to S3-specific logic. 
After this change, when the function is called with `signing_name == 's3'` and `auth_type='v4a'`, it will now return `s3v4a` instead of previously `v4a`. This does not change any current behavior because the function is never called with this combination of values (see below for why).
Context: The function `set_operation_specific_signer` usually gets called when a `choose-signer.*` event is emitted. However, it currently does _not_ get called for the `choose-signer.s3.GetObjectAttributes` event when a global access point is used because the handler `S3EndpointSetter.set_signer` [is subscribed to the same …
> Generalize set_operation_specific_signer to recognize "s3v4a" case

- botocore/tokens.py
Moving our new FrozenAuthToken class to a NamedTuple to provide temporary compatibility to some of our downstream users. This won't have any material change for users as the FrozenAuthToken is a private interface that's not intended for external consumption.
> Convert dataclass to NamedTuple for backwards compatibility

- botocore/client.py
There are some SSL common names that are identical to the hostname, which was raised in https://github.com/boto/botocore/issues/2705#issuecomment-1236390963. This will suppress warnings where this is true.
> Don't raise warning if common name and hostname are the same

- botocore/loaders.py
- botocore/regions.py
- botocore/session.py
- tests/functional/test_regions.py
- tests/unit/test_loaders.py
Adds utilities to the `Loader` class to determine whether a file originates from within botocore's builtin data directory or not:
* `load_data()` now accepts an optional argument `return_path`. If set to true, the path where the data is loaded from is returned as second return value
* a new `is_builtin_path()` method that checks whether a given path is within the builtin data directory or not
Adds a new property `uses_builtin_data` to the `EndpointResolver` class. This property is set during component initialization using the helper methods from the `Loader` described above.
> Loader utilities for determining source of loaded data

- botocore/loaders.py
- tests/unit/test_loaders.py
Followup to https://github.com/boto/botocore/pull/2751: This removes the call to `os.path.realpath()` and the corresponding test coverage related to symlinks.
Reasoning for this reversal at the last minute before releasing the #2751 PR:
Because the `Loader` class never sees the _filesystem_ path of the data file, only the _data_ path (which excludes the file extension), the call to `os.path.realpath()` in #2751 would have never resolved a symlink. Even if working correctly, this symlink resolution would only have taken effect for users who have a symlink in their data directory (`~/.aws/models`) pointing back to the botocore package's builtin file. After considering the benefit of covering this unlikely edge case and the effort involved in making the _filesystem_ path available to the …
> Remove symlink resolution in Loader.is_builtin_path

- tests/functional/test_mturk.py
- tests/functional/test_sagemaker.py
- tests/unit/auth/test_signers.py
- tests/unit/test_configloader.py
Addresses https://github.com/boto/botocore/issues/2752
The reported issue is a test failure of the new test `tests.unit.test_client.TestAutoGeneratedClient testMethod=test_BOTO_DISABLE_COMMONNAME`. This test failure is reproducible on all platforms by running the tests in `tests/functional/` before the failing test. Root cause was a test class in `tests/functional/test_mturk.py` that called `super().setUp()` instead of `super().tearDown()`. All tests run later in the same session ended up with a modified `os.environ`. 
This PR fixes the problematic test mentioned above. In addition, it adds a call to `super().tearDown()` to all `tearDown()` methods of test classes that have base class other than `unittest.TestCase` where this is not already in place.
> Add missing `super().tearDown()` for test classes with custom base classes

- .pre-commit-config.yaml
- botocore/endpoint_provider.py
- tests/unit/data/endpoints/test-cases/is-virtual-hostable-s3-bucket.json
- tests/unit/data/endpoints/valid-rules/is-virtual-hostable-s3-bucket.json
- tests/unit/test_endpoints_v2.py
Implements the `aws.isVirtualHostableS3Bucket` standard library function for endpoint provider rulesets. This is a small addition to #2737.
The spec for the function is:
> Evaluates whether a string is a DNS compatible bucket name and can be used with virtual hosted style addressing. In addition to the restrictions defined in [RFC 1123](https://www.ietf.org/rfc/rfc1123.txt) and `isValidHostLabel`, the `isVirtualHostableS3Bucket` function must also validate that the bucket name is between [3,63] characters, does not contain upper case characters, and is not formatted as an IP address.
> aws_is_virtual_hostable_bucket endpoint provider standard library function

- botocore/model.py
- tests/unit/test_model.py
Service model files (`/botocore/data/*/*/service-2.json`) will soon contain information about three types of "context params": 
1. static context parameters, optional for each operation
2. (dynamic) context parameters, optional for each operation
3. client context parameters, optional for each service
This PR adds properties for accessing context parameters information in the `ServiceModel` class.
> Support for context params in service models

- botocore/args.py
- botocore/regions.py
- tests/unit/test_args.py
This PR is part of the ongoing endpoint resolution v2 work, together with #2737, #2740, #2751, #2747. It contains the code that assigns values to a list of "builtin parameters" that may be referenced by endpoint rulesets. It's glue code between the existing `ClientCreator` and `ClientArgsCreator` and the future `EndpointProvider` (see #2737).
Q: By itself, this PR adds only unused code. Why is it a separate PR? — A: I decided to break this out of a larger PR with all the middleware for calling `EndpointProvider` to keep this a separate review/discussion. Even though the code is pretty simple, there could be a complex discussion hiding behind each parameter assignment and how it is tested. Let's get these debates out of the way first :)
> Endpoint resolution v2: builtin parameter values

- botocore/credentials.py
Having used other providers in the past, I was looking for a "Credential found" log message from boto3 when verifying usage of the InstanceMetadataProvider.
I lost a little bit of time today wondering why I couldn't see the same verification while testing a boto3 client using the InstanceMetadataProvider, then was surprised to find that _just this_ provider logs the Credential confirmation at debug level.
This PR logs the "Credential found" message for the InstanceMetadataProvider at info to match the other providers with the same such message.
> Log InstanceMetadataProvider message at info level

- botocore/httpsession.py
This addresses https://github.com/boto/botocore/issues/2744. It does so by suppressing all warnings of type `DeprecationWarning` when attempting to import from `pyOpenSSL`
> suppress pyopenssl deprecation warning with catch_warnings

- botocore/args.py
- botocore/config.py
- tests/unit/test_args.py
This PR partially addresses https://github.com/boto/botocore/issues/2249. We have chosen not to incorporate `duration_seconds` as it is a pretty niche, rarely used argument that also relies on others to be set in the same config object.  Because `tcp_keepalive` is a setting that originates from an operating system, it can only ever be enabled not disabled. This means if set in a scoped config, but not the client config object, it will still be enabled.
> add `tcp_keepalive` to Config object

- botocore/args.py
The `tcp_keepalive` parameter was added to the Config object in #2766 When inspecting the return value of an instantiated Client's `meta` with the config, it is always `None`.
Does not handle resolving whether the value has been set in `scoped_config`.
> add tcp_keepalive to config_kwargs

- MANIFEST.in
This PR adds any service model file stored as a compressed GZIP JSON to be included in the wheel file that is pushed to PYPI as part of botocore's daily release cycle.
> gzip rule set files for wheel

- .github/workflows/lint.yml
- .github/workflows/run-crt-test.yml
- .github/workflows/run-tests.yml
Github Actions has been displaying instances of these warnings under each workflow run:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-python, actions/setup-python, actions/checkout
and
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: pre-commit/action
This PR does exactly what the warnings suggests: Update the version of the `action/checkout`, `actions/setup-python`, and …
> Address Github Actions warning by updating actions versions

- tests/functional/models/custom-acm/2015-12-08/endpoint-rule-set-1.json
- tests/functional/test_model_backcompat.py
This data file was formerly part of https://github.com/boto/botocore/pull/2785/. Moved to separate PR because it can be released separately and later, and to make #2785 easier to review.
The folder `tests/functional/model/custom-acm` contains a snapshot of the folder `botocore/data/acm/2015-12-08`. The comments in https://github.com/boto/botocore/blob/develop/tests/functional/test_model_backcompat.py explain why this snapshot exists.
Once the new ruleset based endpoints resolver (introduced in #2785) gets enabled for all services, or in the unlikely event that we decide to specifically for `custom-acm`, the snapshot folder must include the `endpoint-rule-set-1.json` file. This PR adds this file.
In addition, this PR updates an outdated inline comment in `test_model_backcompat.py`.
> Endpoints ruleset file for snapshot of service folder in tests/functional/models

- botocore/client.py
#2785 (released in version 1.28.0) introduced a backwards-incompatible change to the signature of the constructor of `botocore.client.BaseClient`. This change modifies the signature to be backwards-compatible.
> Make Baseclient constructor signature backwards compatible with <1.28.0

- botocore/args.py
- tests/functional/test_context_params.py
Context: #2740 introduced support for context params into Botocore. #2785 introduced a new way of resolving endpoints that utilizes context parameters. 
There are three types of context params: Static, dynamic, and client context params. Botocore currently intends to support _client_ context params only for the S3 services. The code in #2785 limits the use of client context params to `s3` only. This PR expands this to additionally include `s3control`. 
This PR also introduces functional test coverage that uses minimal fake models and rulesets to assert that all three types of context param are passed into the endpoint provider when expected, and not otherwise.
> Support client context params for s3control

- botocore/handlers.py
- tests/functional/test_s3.py
Addresses https://github.com/boto/botocore/issues/2798.
Version 1.28.0 erroneously introduced a change in behavior for S3 pre-signed URLs with bucket names that aren't valid host labels as defined in [RFC 1123](https://datatracker.ietf.org/doc/html/rfc1123#section-2). After the change, the resulting URLs no longer used the regional endpoint. 
This PR fixes the specific issue reported in https://github.com/boto/botocore/issues/2798 and adds test coverage for it. In addition, it reverts to pre-1.28.0 logic for whether to use a regional or global endpoint for certain S3 requests where either option is valid.
> Fix for S3 pre-signed URLs with bucket names that contain dots

- botocore/client.py
- botocore/endpoint_provider.py
- botocore/regions.py
- tests/functional/test_eventbridge.py
This PR is a small change stacked on top of https://github.com/boto/botocore/pull/2785. To see the diff between those two branches [click here](https://github.com/jonemo/botocore/compare/endpointsresolverv2-squash...jonemo:botocore:endpointsresolverv2-events).
https://github.com/boto/botocore/pull/2785 enables Endpoint resolution v2 for the `s3` and `s3control` clients. This PR adds the `events` (Eventbridge) client to the list. The PR bundles the relevant endpoint ruleset and endpoint tests data files. It also removes the code path for registering Eventbridge customizations which are completely replaced by the new endpoint ruleset.
After the code changes described above, seven test failures in the file `tests/functional/test_eventbridge.py` happened. These could be addressed by:
1. …
> Endpoint resolution v2 for Eventbridge

- botocore/args.py
Fall back to the legacy resolver as source of a default region name when a region name cannot be sourced from elsewhere.
> Endpoint resolver 2.0: Use legacy resolver as source of default region name

- tests/functional/test_paginator_config.py
Minor cleanup: This output to a temporary file in a functional test seems vestigial.
> Remove unused file output in test_paginator_config.py

- botocore/client.py
Reverts the signatures of "private" functions `_register_s3_events` and `_register_s3_control_events` to what they were before botocore 1.28.0.
> Revert signatures of _register_s3_events and _register_s3_control_events

- tests/unit/test_awsrequest.py
As a [part of urllib3 v2.0](https://github.com/urllib3/urllib3/pull/2768) we changed how `HTTPConnectionPools` interact with inner `HTTPConnection` objects, mostly to remove manipulation of inner state like the socket. Instead now the `HTTPConnection` calls `settimeout()` on it's own socket.
We also run botocore in our integration tests, and this change caused a failure where `FakeSocket` didn't have the `settimeout` method. This PR is upstreaming the [patch we have committed to our repository](https://github.com/urllib3/urllib3/blob/main/ci/0005-botocore-fakesocket-settimeout.patch).
> Add a settimeout() method to FakeSocket

- .changes/next-release/bugfix-s3-62528.json
- botocore/handlers.py
- tests/functional/test_s3.py
Addresses an issue where requests for some S3 API operations that should include the `x-amz-content-sha256` header do not have this header for S3 on Outpost. This issue was introduced in version 1.28.0 of botocore.
> Fix: S3 on Outpost requests miss x-amz-content-sha256 headers

- .changes/next-release/enhancement-sso-60997.json
- botocore/credentials.py
- botocore/tokens.py
- botocore/utils.py
- tests/functional/test_credentials.py
This PR will add support for loading credentials via a configured `sso-session` in your AWS config file.
> Add support for sso-session credentials

- botocore/docs/bcdoc/docstringparser.py
- botocore/docs/bcdoc/style.py
- tests/unit/docs/bcdoc/test_docstringparser.py
When auto-generating botocore documentation, an additional whitespace is hardcoded after every hyperlink is created. This may have been done under the assumption that a hyperlink would always be followed by a word but fails to consider cases where a space wouldn't be needed such as before the following characters `['.', ',', '?', '!', ':', ';']`.
**Examples:**
* https://docs.aws.amazon.com/cli/latest/reference/ec2/create-traffic-mirror-target.html
* https://docs.aws.amazon.com/cli/latest/reference/kms/generate-random.html
This PR addresses this issue by providing a look-ahead (`next`) when possible, and if either of these characters is detected, a space is omitted. 
These changes were validated by generating the documentation files before and after the change and comparing using 
```
diff …
```
> Removed additional whitespace after hyperlinks for special cases in our docs

- botocore/compat.py
This fixes a miss from #2806 where six was incorrectly removed from the compat module. This is required for external test frameworks and is needed for backwards compatibility.
> Readd missing six import in compat

- botocore/utils.py
- tests/unit/test_utils.py
On Python 3.11, as soon as `botocore.utils` is imported there are [deprecation warnings](https://github.com/python/cpython/blob/v3.11.0/Lib/cgi.py#L57) due to the `import cgi`, a module which [is slated to be removed](https://github.com/python/cpython/issues/91217) from stdlib. [PEP 594](https://peps.python.org/pep-0594/#cgi) recommends replacing the `cgi.parse_header` with this `email.message` substitute.
> remove cgi module usage, which causes deprecation warnings on Python 3.11

- .changes/next-release/bugfix-s3-26698.json
- botocore/handlers.py
- tests/functional/test_s3.py
Addresses https://github.com/aws/aws-cli/issues/7456: Requests for some S3 API operations that should include the x-amz-content-sha256 header do not have this header for S3 Object Lambdas. This issue was introduced in version 1.28.0 of botocore.
> Fix: S3 Object Lambda requests miss x-amz-content-sha256 headers

- .changes/next-release/bugfix-Endpoints-16572.json
- botocore/endpoint_provider.py
- tests/functional/conftest.py
- tests/functional/test_sts.py
- tests/unit/test_endpoint_provider.py
Addresses https://github.com/aws/aws-cli/issues/7455.
Changes endpoint resolution to resolve the endpoint for the default AWS partition when no region is given.
> Resolve endpoint with default partition when no region is set

- setup.cfg
awscrt is a conditional dependency of botocore (used when installing with `pip install botocore[crt]`. 
awscrt added wheels for Python 3.11 in https://github.com/awslabs/aws-crt-python/tree/v0.15.1 (and dropped wheels for Python 3.6 at the same time). botocore formally added support for Python 3.11 in #2693. As of last weekend, Github Actions CI runs fail for Windows + Python 3.11 + with CRT variant at the step where awscrt gets built from source.
Updating the dependency version ensures that an awscrt wheel is used for all botocore installs, including under Python 3.11. This indirectly also fixes the failing CI builds.
awscrt changelog: https://github.com/awslabs/aws-crt-python/releases
The change in this PR is by @davidlm, I am only creating the PR. The most recent awscrt version bump PR …
> Update to awscrt dependency from 0.14.0 0.15.3

- tests/unit/test_endpoint_provider.py
This PR adds a unit test for endpoint resolution caching, which the test suite did not previously include.
> add unit test for endpoint resolution caching

- botocore/docs/bcdoc/docstringparser.py
- botocore/docs/bcdoc/restdoc.py
- botocore/docs/bcdoc/style.py
- tests/unit/docs/bcdoc/test_docstringparser.py
This PR addresses issues with botocore docs which include:
* Missing or necessary white space which causes links to render incorrectly
* [Nested formatting](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#:~:text=No%20nested%20inline%20markup%3A%20Something%20like%20*see%20%3Afunc%3A%60foo%60*%20is%20not%20possible.) not being supported by Sphinx.
Examples:
* https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/kms.html#:~:text=https%3A//docs.aws.amazon.com/kms/latest/developerguide/%60.
* https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#:~:text=parameter%20in%20the-,%60%60%20GetOrganizationsAccessReport%20%60%60,-operation%20to%20check
> Fixed doc issues around links and nested formatting

- .changes/next-release/bugfix-Endpointprovider-32427.json
- botocore/endpoint_provider.py
- tests/unit/test_endpoint_provider.py
This addresses a bug for `aws_parse_arn` in `endpoint_provider.RuleSetStandardLibrary`. Currently the `resourceId` portion of a parsed ARN was only thought to either have a `/` or `:` as a delimiter. However, in services such as `kinesis`, they can have both.
Current Behavior
`arn:aws:kinesis:1234567890:us-east-1:thing/foo:bar`  -> `{...'resourceId': ['thing/foo', 'bar']}`
New Behavior
`arn:aws:kinesis:1234567890:us-east-1:thing/foo:bar`  -> `{...'resourceId': ['thing', 'foo', 'bar']}`
> Update ARN delimiter parsing in endpoint provider

- botocore/endpoint_provider.py
This is a follow-up to https://github.com/boto/botocore/pull/2831. While there was nothing wrong with it, splitting a string using a compiled regular expression object is significantly slower (roughly 3x) than using plain Python string manipulation methods.
> arn resource delimiter regex to string methods

- botocore/docs/bcdoc/restdoc.py
- botocore/docs/method.py
Services such as `quicksight` have recently become very large and contain several layers of nested shapes that result in doc pages which are basically unusable in some cases such as [this one](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/quicksight.html).
The temporary solution to get these pages usable again is to ignore response/request sections that are too large, specifically here are the limits:
* **`Request/Response Syntax Examples:`** Limited to 1500 lines. If larger, the section will be replaced with a "too large" message and be provided a link to AWS API Documentation for the corresponding service/section.
* **`Descriptions/Params:`** Limited to 5000 lines. If larger, the section will be replaced with a "too large" message and be provided a link to …
> Ignore response/request sections in docs if they're too large.

- botocore/parsers.py
`type(response['body'])` is `bytes`. Formatting it as `%s` results in a `BytesWarning` on Python 3.
> Avoid BytesWarning on logging responses

- docs/README.md
- requirements-docs.txt
Recent version of alabaster (0.7.13) requires `sphinx>=1.6`.
> Pin version of alabaster

- tests/functional/test_s3.py
Minor updates to private s3 client constructor in `tests/functional/test_s3.py` to make the process more streamlined for future tests.
> Add sensible defaults to default s3 client creator in tests

- .changes/next-release/bugfix-s3-10151.json
- .changes/next-release/bugfix-s3contentencoding-88564.json
- botocore/httpchecksum.py
- tests/functional/test_s3.py
- tests/unit/test_httpchecksum.py
Primarily in various S3 operations, users may provide a `ContentEncoding` parameter. This tells the service how the content that is being sent/requested is encoded. An example of this would be `gzip`. However, for streaming AWS operations (i.e. ones that have trailers) where a `ChecksumAlgorithm` parameter is provided, the SDK is currently overriding any user input to `aws-chunked`. Instead this special content encoding should be appended to the user input.
> Append `aws-chunked` to `Content-Encoding` header if present

- .changes/next-release/bugfix-SSO-37144.json
- botocore/credentials.py
- botocore/tokens.py
- tests/functional/test_credentials.py
- tests/unit/test_tokens.py
Fixes https://github.com/aws/aws-cli/issues/7496
When resolving credentials, `profile_name` should be plumbed into `SSOTokenProvider` so that if they need to be resolved recursively, the newly set `profile_name` gets used to load the SSO config rather than using the profile name defined in the session.
Example of a valid config that is currently failing to resolve:
```
[profile test]
role_arn = arn:aws:iam:XXXXXXXXXXXX:role/testrole-1
source_profile = AdministratorAccess-XXXXXXXXXXXX
region = us-west-2
[profile AdministratorAccess-XXXXXXXXXXXX]
sso_session = dev
sso_account_id = XXXXXXXXXXXX
sso_role_name = AdministratorAccess
region = us-west-2
output = json
[sso-session dev]
sso_start_url = https://d-XXXXXXXXX.awsapps.com/start
sso_region = us-west-2
sso_registration_scopes = …
```
> Plumb profile_name into SSOTokenProvider

- tests/functional/test_credentials.py
This affects the test: `tests/functional/test_credentials.py::SSOSessionTest::test_token_chosen_from_provider` which was previously throwing a RuntimeError ("Credentials were refreshed, but the refreshed credentials are still expired.") due to incorrect interpretation of the TIME_IN_ONE_HOUR timestamp. The timestamp() call in `test_credentials.py::SSOSessionTest::add_credential_response` assumes that the datetime object is in local time, which may be different from UTC time depending on the system's local timezone. This was causing the test to fail as the token expiry time was set to an invalid time before the current time.
Specifying the timezone as UTC ensures that the timestamp stored is the correct Unix timestamp to be used as the token expiry.
> Add timezone info to the datetime instances used in test_token_chosen_from_provider

- docs/source/_static/js/custom.js
The current process for redirecting includes a validation that compares part of the fragment that represents the client's class name with the service's doc page name (also the`serviceId`). This works for most services but there are also cases where these don't actually map to each other directly (`elb` --> `ElasticLoadBalancing`). We will instead compare the client's class name to the title of the current doc page.
> Support doc page redirects for ALL services

- botocore/docs/example.py
Currently, when running `make html` in the `docs` folder to build the docs website, the logs contain ten-thousands of lines like this one:
```
/path/to/repo/botocore/docs/source/reference/services/waf/client/put_logging_configuration.rst:203: WARNING: Literal block ends without a blank line; unexpected unindent.
```
This PR addresses the warning by inserting the necessary empty line after every code example block and request and response example block. See for example this randomly chosen example from a paginator documentation page. Before, missing the necessary blank line:
```
:rtype: dict
:returns: 
**Response Syntax** 
::
{
'Tags': [
{
'Key': 'string',
'Value': 'string'
},
],
}
**Response Structure** 
```
... and after, including the blank line:
```
:rtype: dict
:returns: 
**Response …
```
> docs: Address ten thousands of warnings about a missing blank line in Sphinx log output

- botocore/docs/client.py
- botocore/docs/method.py
- tests/functional/docs/__init__.py
- tests/unit/docs/test_client.py
- tests/unit/docs/test_service.py
We previously had all class and method documentation on the same service page, however, we implemented nested docs to decrease page size. In doing so, we broke the way sphinx handles cross-references since methods on individual pages (not in the `py:class` body) should have the full class name attached as explained [here](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#:~:text=Methods%20and%20attributes%20belonging%20to%20the%20class%20should%20be%20placed%20in%20this%20directive%E2%80%99s%20body.%20If%20they%20are%20placed%20outside%2C%20the%20supplied%20name%20should%20contain%20the%20class%20name%20so%20that%20cross%2Dreferences%20still%20work.).
Before Nested Docs:
```
.. py:class:: Foo
.. py:method:: bar()
```
Current:
```
.. py:class:: Foo.Client
.. …
```
> Sphinx domain fix

- docs/Makefile
When working on documentation updates, it's recommended to change [`session.get_available_services()`](https://github.com/boto/botocore/blob/develop/botocore/docs/__init__.py#:~:text=in-,session,(),-%3A) (which generates all 340+ service docs) to a list of specific serviceIds such as `['dynamodb', 'kms', 's3']` or a small number of services like `session.get_available_services[:5]` in order to speed things up. These source files get stored in `docs/source/reference/services` and are never cleared, so when you change which files you want to test, old ones from previous runs will be included. 
This PR adds a command to `make clean` that clears out the source file directory.
> Clear out source directory when running 'make clean'

- botocore/docs/bcdoc/docstringparser.py
- botocore/docs/bcdoc/style.py
- tests/unit/docs/bcdoc/test_docstringparser.py
Fixes two classes of errors that were introduced in https://github.com/boto/botocore/pull/2855:
* When link text starts with a space, the link no longer gets rendered correctly. This one was discovered by @nateprewitt 
* Preformatted and code snippets that contain stylized quotation marks (`“`) instead of plain `"`.
As part of investigating this, I found that the special treatment for trailing whitespace in data nodes (where one whitespace is always left behind) is another special case whitespace treatment longer needed and removed it.
Before
After
Before
After
Before
After
Spot checked HTML of ~200 pages with diffs from the changes in this PR. All of them are either fixes of the issues described above, or further removals of unnecessary whitespace.
> Fix links and code edge cases in docs generation

- botocore/data/autoscaling/2011-01-01/examples-1.json
This PR adds examples for the following operations in the `autoscaling` service:
- `AttachTrafficSources`
- `DescribeTrafficSources`
- `DetachTrafficSources`
Example generated for `DescribeTrafficSources`.
> Add examples for autoscaling

- botocore/httpchecksum.py
- tests/unit/test_httpchecksum.py
Adds a custom error message for customers trying to use `CRC32C` checksum algorithm, but don't have `awscrt` installed.
> add custom error message for using crc32c without crt

- .github/workflows/run-tests.yml
Codecov has removed their package from PyPi ([see message](https://about.codecov.io/blog/message-regarding-the-pypi-package/)) which has caused our HitHub workflows to fail since we `pip install codecov`. This PR uses their GitHub Action ([codecov-action](https://github.com/codecov/codecov-action)) instead.
> Use codecov-action instead of pip installing.

- botocore/client.py
- botocore/serialize.py
- tests/functional/test_s3.py
Updating host prefix input validation.
> Host prefix bug

- botocore/httpchecksum.py
- tests/unit/test_httpchecksum.py
Follow up to https://github.com/boto/botocore/pull/2905. Use `MissingDependencyException` and check against extendible list of CRT checksums rather than single strings. Added test to validate CRT checksum list is in sync with checksum class dictionary keys.
> change error for missing crt. use list of crt checksums instead

- botocore/httpsession.py
Starting in urllib3 2.0, the hardcoded `DEFAULT_CIPHERS` for the ssl_context have been removed. This is a migration in a safer direction to allow user systems to define preferred cipher suites and enable modification without new releases of urllib3. This will expedite any security patching and give users finer grained control over what is chosen.
Please note that botocore **does not** support urllib3 2.0 yet, but users are starting to see this interaction when testing for a future upgrade. To help enable that, we'll start deferring to urllib3 for this selection when an appropriate urllib3 version is installed ([ref](https://github.com/urllib3/urllib3/blob/6446fef0cf432ca035169602a1447a0d8ef53e80/src/urllib3/util/ssl_.py#L236-L238)).
> Defer to system defaults for cipher suites with urllib3 2.0+

- .changes/next-release/bugfix-sqs-16349.json
- botocore/data/sqs/2012-11-05/endpoint-rule-set-1.json
- botocore/data/sqs/2012-11-05/service-2.json
- tests/functional/endpoint-rules/sqs/endpoint-tests-1.json
> Revert SQS protocol changes

- .changes/next-release/bugfix-EndpointProvider-38157.json
- botocore/endpoint_provider.py
- tests/functional/test_s3.py
- tests/unit/test_endpoint_provider.py
This addresses https://github.com/boto/botocore/issues/2938. Currently `RuleSetStandardLibrary.aws_is_virtual_hostable_s3_bucket` is performing the exact same validations on the entire input value as it does with individual subdomains within the input value. This is incorrect because only the entire value needs to be at least 3 characters, not each individual component. As described in the issue, this caused a bug when enabling virtual style addressing and providing an `endpoint_url` to an S3 client that is insecure (http not https). For bucket names that look like URLs containing short subdomain fragments, path style is being used instead which is incorrect. 
Additionally, we only need to perform validation that the input value is not an IPV4 address, None and all lowercase at the top …
> Address virtual host style addressing bugs for short subdomains provided in ``endpoint_url``

- .changes/next-release/bugfix-configprovider-46546.json
- botocore/configprovider.py
- tests/unit/test_config_provider.py
Config providers were updated for smart default support to be deep copy-able. This PR fixes a bug when deep copying the config value store. Previously, override values were not preserved. The fix adds the override values to the new copy of the value store.
A test was added to confirm that the overrides are preserved in the copy.
> Keep overrides when deep copying config value store

- .changes/next-release/bugfix-generatepresignedurl-96454.json
- botocore/handlers.py
- botocore/signers.py
- tests/unit/test_signers.py
This addresses a bug in URL presigning. For certain operations, like Polly's `SynthesizeSpeech`, the URL used for presigning does not match what is modeled for the request. Typically it is sent as a `POST` with API parameters attached to a body, but through presigning, it is a `GET` with parameters attached in the URL query. 
This issue arises in the `RestJson` serializers where the input params are still treated as a body, so a `Content-Type` header is injected, causing a signature mismatch in the presigned URL that is returned.
This PR generally removes this header for presigning from requests using methods where bodies should not be present or should have no meaning.
UPDATE: After some issues were discovered when running presigning for the JSON-RPC protocol, we've decided to scale back …
> Presigning content type bug

- .changes/next-release/enhancement-configprovider-27540.json
- botocore/configprovider.py
- botocore/session.py
- tests/functional/models/sdk-default-configuration.json
- tests/functional/test_config_provider.py
- tests/unit/test_config_provider.py
- tests/unit/test_session.py
Instead of deep copying, use a shallow copy of the config value store when using it for creating a new client from a session.
Update behavior of the smart defaults update functions to use a copy of the existing config providers in all cases. Update the logic for determining which new provider to create.
Add a `__copy__` method to all config providers that need it, or for uniformity.
Move unit tests for config provider smart defaults to functional tests and rework them to better test behavior. A mocked defaults  data file is used to confirm that the correct values are loaded to protect against changes to the live data file.
> Shallow copy config value store and providers

- .changes/next-release/feature-configuration-3829.json
- botocore/args.py
- botocore/config.py
- botocore/configloader.py
- botocore/configprovider.py
- botocore/handlers.py
- botocore/session.py
- botocore/utils.py
- tests/functional/test_endpoints.py
- tests/unit/cfg/aws_services_config
- tests/unit/test_config_provider.py
- tests/unit/test_configloader.py
Adds a config provider to resolve the endpoint URL provided in an environment variable or shared configuration file. It resolves the endpoint in the following manner:
1. The value provided through the `endpoint_url` parameter provided to the client constructor.
2. The value provided by a service-specific environment variable.
3. The value provided by the global endpoint environment variable (`AWS_ENDPOINT_URL`).
4. The value provided by a service-specific parameter from a services definition section in the shared configuration file.
5. The value provided by the global parameter from a services definition section in the shared configuration file.
6. The value resolved when no configured endpoint URL is provided.
> Implement configured endpoint url resolver

- tests/functional/configured_endpoint_urls/__init__.py
- tests/functional/configured_endpoint_urls/profile-tests.json
- tests/functional/configured_endpoint_urls/test_configured_endpoint_url.py
Add functional testing for use of a configured endpoint url through the shared config file and environment variables.
First, the tests use a data file to load tests that enumerate the combinatorial ways that the endpoint URL can be defined (shared configuration file and environment variable for individual service and global/all services), and asserts that the correct endpoint is returned.
The tests also assert that the correct config section name and environment variable name are used to configure and override the endpoint URL for all services.
Lastly, the tests check that a operations for a subset of services use the endpoint override in a request.
> Configured endpoint url resolver functional tests

- tests/functional/configured_endpoint_urls/profile-tests.json
- tests/functional/configured_endpoint_urls/test_configured_endpoint_url.py
Add tests to check that setting the client creation parameter to ignore the configured endpoint URLs is respected.
> Add client config ignore endpoint tests

- .github/workflows/stale_issue.yml
Update ancient issue time so that we are not automatically closing old GitHub issues.
> chore: update ancient issue bot

- .changes/next-release/bugfix-Parsers-42740.json
- botocore/utils.py
- tests/unit/test_utils.py
This addresses various issues where calling `datetime.datetime.fromtimestamp()` fails with `OverflowError` or `OSError`. These behaviors are platform-dependent and currently seem to affect mainly Windows. [The Python documentation mentions the existence of these failure mode](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp).
This PR adds a fallback for when parsing a numeric timestamp fails that uses `timedelta` to create a datetime that is offset from the epoch (Jan 1, 1970) by the given number of seconds. This has the same effect as calling `fromtimestamp()` without calling the C `localtime()` function.
Some related issues:
* #2564
* #2355
* #1783
* #1939
* boto/boto3#2069
* boto/boto3#3642
The general theme of these issues is that a service returns a …
> Fallback for situations where Python's fromtimestamp() raises OSError or OverflowError

- botocore/utils.py
Removes a `print()` statement that snuck through in https://github.com/boto/botocore/pull/2972
> Remove leftover print statement

- .changes/next-release/bugfix-configprovider-46546.json
- .changes/next-release/enhancement-configprovider-27540.json
- .changes/next-release/feature-configuration-3829.json
- botocore/args.py
- botocore/config.py
- botocore/configloader.py
- botocore/configprovider.py
- botocore/handlers.py
- botocore/session.py
- botocore/utils.py
- tests/functional/configured_endpoint_urls/__init__.py
- tests/functional/configured_endpoint_urls/profile-tests.json
- tests/functional/configured_endpoint_urls/test_configured_endpoint_url.py
- tests/functional/models/sdk-default-configuration.json
- tests/functional/test_config_provider.py
- tests/functional/test_endpoints.py
- tests/unit/cfg/aws_services_config
- tests/unit/test_config_provider.py
- tests/unit/test_configloader.py
- tests/unit/test_session.py
This PR implements the proposal for configuring endpoints per service:
https://github.com/aws/aws-sdk/pull/230
Adds a config provider to resolve the endpoint URL provided in an environment variable or shared configuration file. It resolves the endpoint in the following manner:
1. The value provided through the `endpoint_url` parameter provided to the client constructor.
2. The value provided by a service-specific environment variable.
3. The value provided by the global endpoint environment variable (`AWS_ENDPOINT_URL`).
4. The value provided by a service-specific parameter from a services definition section in the shared configuration file.
5. The value provided by the global parameter from a services definition section in the shared configuration file.
6. The value resolved when no …
> Configured endpoint URL resolution

- .changes/next-release/bugfix-s3-68869.json
- botocore/handlers.py
- tests/unit/test_handlers.py
Addresses https://github.com/boto/botocore/issues/2962
Fixes a bug where, for certain S3 operations and when using the default signer, the URL used in the signature string was invalid. This resulted in invalid presigned URLs.
**Context**
Botocore uses a JSON file that defines the [S3 service model](https://github.com/boto/botocore/blob/develop/botocore/data/s3/2006-03-01/service-2.json) for constructing request URLs for S3 API requests. For example, the `GetObjectAcl` operation is modeled with request URI `/{Bucket}/{Key+}?acl`. Since the introduction of [virtual-hosted-style addressing](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html), botocore has dropped the leading `/{Bucket}` from the service model's request URIs. Separate S3-specific logic then …
> Fix generate_presigned_url for S3 operations where the modeled request URI contains a query component 

- tests/__init__.py
- tests/functional/test_context_params.py
- tests/functional/test_response_shadowing.py
https://github.com/boto/botocore/pull/2959 makes use of a couple of helper methods for tests that were defined in individual test files. This PR moves them to the base of the package so they can be easily imported across the entirety of it.
> move test helper functions to tests/__init__.py

- .github/codeql.yml
- .github/workflows/codeql.yml
- .github/workflows/fail-master-prs.yml
- .github/workflows/lint.yml
- .github/workflows/run-tests.yml
- .github/workflows/stale_issue.yml
This PR adds:
* Explicit scoping for token usage in our existing workflows.
* Updates close-stale-issues to only run once a day to save worker resources.
* Adds CodeQL to run static analysis over code base.
> Update GHA configurations

- .changes/next-release/enhancement-HTTP-88756.json
- .github/workflows/run-tests.yml
- botocore/awsrequest.py
Starting in urllib3 2.0, the HTTPConnection behavior was reorganized to incorporate request chunking under the same top-level `request` method. This removed the underlying call to `_send_request` that's utilized by CPython's HTTPConnection which is the parent class of the urllib3 implementation. This change effectively short circuited botocore's provisional HTTP 100-continue support.
To provide a path forward for supporting urllib3 2.0, we're moving to us urllib3's `request` interface. Fortunately, this also exists in CPython as a [thin wrapper around `_send_request`](https://github.com/python/cpython/blob/main/Lib/http/client.py#L1316-L1319). This will reenable _most_ of our internal patches to the class to support 100-continue.
The only significant pain point this will introduce is …
> Move 100-continue behavior to use high-level request interface

- botocore/session.py
The symptom is e.g. `KeyError: 'credential_provider'`, detailed in e.g. https://github.com/boto/botocore/issues/1246#issuecomment-632444392
As detailed in the comment, even if the component factory gets called twice, cleaning the deferred up should not cause a KeyError.
> Avoid a KeyError when a ComponentLocator is being called concurrently

- botocore/credentials.py
os.path.sep and os.sep are supposed to do the same but os.path.sep can lead to random crashes in newer python versions with the following error
_AttributeError: module 'posixpath' has no attribute 'sep'_
This is also known to other projects and is caused by some broken python versions
https://github.com/pytest-dev/pytest/issues/10547
https://github.com/Toblerity/Fiona/issues/1143
https://github.com/pallets/jinja/issues/1697
The small proposed fix will avoid the issue altogether, even with broken python versions
> fix: random crashes in credentials.py

- .github/dependabot.yml
This PR will add a base dependabot config to check our github actions for updates once a week. This will ignore patch updates to minimize noise for the time being.
> Add base dependabot config

- .github/workflows/closed-issue-message.yml
- .github/workflows/lint.yml
- .github/workflows/run-crt-test.yml
- .github/workflows/run-tests.yml
- .github/workflows/stale_issue.yml
This PR will formalize the pins for all GHAs and fix remaining permissions in the aws-actions now that we've verified they'll work as expected.
Current scorecard for reference: https://securityscorecards.dev/viewer/?uri=github.com/boto/botocore
Note the "Token Permissions" and "Pinned-Dependencies" sections.
> Update pins and permissions for GHA

- requirements-dev-lock.txt
- requirements-dev.txt
This PR will upgrade pytest to the latest release (7.4.0) to support Python 3.12.
> Update pytest to 7.4.0

- botocore/config.py
This fixes a couple of minor issues in the `Config`[ reference in our docs](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html). Subsequent lines of parameter definitions in the object's doc strings must be indented to render correctly. This also adds another set of backticks to `requiresLength` so it renders as highlighted rather than italicized.
Current
With Changes in this PR
> Config doc bug fix

- botocore/config.py
Follow up to https://github.com/boto/botocore/pull/3015. The param name is incorrect. Fixing this also fixes the type rendering in html as well.
Current:
With PR:
> fix param name for `request_min_compression_size_bytes`

- botocore/handlers.py
We'll need to start properly encoding our SSE parameters for CompleteMultipartUpload. This was previously broken when passing bytes to this operation unlike our other *MultipartUpload operations. This patch will ensure all bytes input is properly base64 encoded before being sent to S3.
> Add sse_md5 hook for CompleteMultipartUpload

- botocore/credentials.py
Adds missing doc string for `expiry_time` param in `RefreshableCredentials`
> add doc string for RefreshableCredentials expiry_time

- botocore/parsers.py
- tests/unit/test_parsers.py
Some AWS services will return the __type metadata in a response alongside a tagged union.  Since this isn't modeled as a response member, it's never shown to SDK users, but needs to be ignored in the response parser to allow prevent an error from being thrown.
> Sanitize __type metadata out of response parsing for tagged unions

- botocore/httpsession.py
- tests/unit/test_http_session.py
This PR will stop passing the no-longer required `strict` argument to the urllib3 ConnectionPool class. This argument was originally needed in `Python<3.5` (specifically Python 2) to specify support for older HTTP status lines before http/1.0. The functionality went away in HTTPConnection in Python 3.4 ([ref](https://docs.python.org/3/library/http.client.html#http.client.HTTPConnection)).
Starting in urllib3 2.1, this parameter will be removed from the APIs we're using. Given it has no effect on version of Python we support, this should be a no-op for users on _all_ versions of urllib3 we support. You can find a [similar PR](https://github.com/psf/requests/pull/6434) where we've done this in Requests which has been in place for ~6 months without issue.
> Remove strict kwarg that was deprecated in Python 3.4

- .changes/next-release/enhancement-Configuration-49047.json
- botocore/args.py
- botocore/config.py
- botocore/docs/client.py
- botocore/docs/service.py
- tests/functional/docs/test_s3.py
- tests/functional/test_context_params.py
- tests/unit/docs/test_client.py
- tests/unit/docs/test_service.py
Adds client context parameters generically across all AWS services and adds them to docs. This PR can be reviewed in two parts. Should be merged in tandem with https://github.com/boto/boto3/pull/3894.
Adds `client_context_params` config option. If the service is s3 or s3control, still use the s3 config param over client context params if it is set. Params are modeled as capital case but are expected in snake case by the endpoint resolver. This commit also includes some code cleanup for the existing client context params test.
Adds client context params docs to each service client's homepage if any are modeled. Existing s3/s3control params are excluded because overlapping behavior already exists in the s3 config. There are no other modeled client context params today, but when one is added …
> Add generic support for client context params

- tests/functional/test_s3.py
A couple of s3 presigned URL tests have `addressing_style` misspelled meaning the config setting is ignored.
> fix presign test cases

- botocore/signers.py
- tests/functional/test_s3.py
This addresses a bug introduced with the endpoints refactor from last year. Previously, if a customer had explicitly set `addressing_style` to `virtual` in their s3 config, the SDK [ignored the `use_global_endpoint` setting on the request context](https://github.com/boto/botocore/blob/febc9ea08510c8b90c67b456f85a9faa64a69c69/botocore/utils.py#L2600-L2602). Instead, it would use the [endpoint URL from the legacy endpoint resolver](https://github.com/boto/botocore/blob/baf3fd32ee93017903f24e8946cd6c11b506962c/botocore/signers.py#L667) which was always regionalized except in the cases of `aws-global` and `us-east-1`. This has caused some issues where a regional endpoint is expected when using signature version 4 to sign URLs.
It was likely missed during the refactor because it followed a …
> explicit virtual addressing presigning bug

- botocore/utils.py
The library has targeted 3.7+ since #2684; no need to retain compatibility code that is never called.
> Remove Python 3.6 compatibility code from datetime2timestamp()

- botocore/client.py
See: https://github.com/boto/boto3/issues/3787#issuecomment-1647308630
Currently looks like:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/get_paginator.html
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/get_waiter.html
After changes:
> Show paginator/waiter return types in markdown

- .github/workflows/stale_issue.yml
We're adding bugs to the stale issue workflow.  This was disabled at some point because we didn't want ancient bugs to be closed.  That workflow no longer exists, so this should be fine.
> Added bugs to stale issue workflow

- botocore/compat.py
Removes non-existing parameters from a docstring for a method; these parameters existed as a part of development of the function, but were removed in subsequent reviews of the original PR that introduced the method.  The docstring was not updated with the code.
> Remove non-existing arguments from docstring

- tests/functional/test_s3_control_redirects.py
Fix linting miss of customization with 880bfe8ba3e602db892e2909a029beb5b96967d1.
> Linting cleanup for s3 redirects tests

- .changes/next-release/enhancement-README-37611.json
- README.rst
This PR updates the botocore README to point to https://github.com/boto/botocore/issues/new/choose which allows users to create a new issue using custom templates instead of the basic https://github.com/boto/botocore/issues/new
> Update issue creation link in README

- tests/unit/test_session.py
- tests/unit/test_session_legacy.py
Remove two incorrect `pytest.warns()` invocations
for `.get_component('internal')`, in order to fix test failures with pytest 8.0.0.  This version of pytest fixes `pytest.warns()` to work inside `pytest.raises()`, and therefore causes the tests to fail because the warning is not emitted when `get_component()` raises `ValueError`.
> Fix pytest-8.0.0 test failures due to incorrect `pytest.warns()`

- .changes/next-release/bugfix-ContainerProvider-22191.json
- botocore/credentials.py
- tests/unit/test_credentials.py
This PR fixes a bug with EKS credentials not properly fetching the token from the token file if the file contents have been updated
> Fix EKS credentials refresh bug

- botocore/handlers.py
- tests/functional/test_s3.py
Adds the header `BOTO_EXPERIMENTAL__NO_EMPTY_CONTINUE`; when enabled, we will make a best effort to inspect the size of the body and only add the 100 continue header if the body is non-empty.  
Note: this feature is marked as experimental and the functionality and may be altered or removed in a minor patch without warning.  Users relying on this feature should strictly pin their botocore version.
> Add experimental environment variable to opt out of 100 continue with empty body

- .changes/next-release/enhancement-urllib3-72501.json
- setup.cfg
- setup.py
This PR will move our pin for Python 3.10+ to allow the full range of releases for urllib3 2.x. This should unblock further upgrades and unblock other projects from moving pins for these version ranges. This should resolve #3138 in the next release of Botocore once merged.
> Move urllib3 2.x pin for Python 3.10+

- botocore/client.py
- botocore/utils.py
- tests/functional/test_s3.py
Abstracts the s3 Express bucket name from the context to be generically usable as well as adding additional keys to be stored
> Make bucket name injection for S3Express more generic

- botocore/data/sqs/2012-11-05/service-2.json
- tests/functional/test_sqs.py
This reverts commit 79c92132e266b15f62bc743ae0816c27d598c36e. This will reenable the JSON-1.0 protocol for SQS requests as originally released in 1.31.81.
> Move SQS protocol to JSON, again

- .github/workflows/run-crt-test.yml
- .github/workflows/run-tests.yml
This PR addresses a recent change in GHA infrastructure to move macos-latest to macos 14 on m1 hardware. This platform doesn't have supported Python 3.8 or Python 3.9 runners, so we'll need to pin those back to macos-13.
> Move 3.8 and 3.9 builds back to macos-13

- .changes/1.34.90.json
- CHANGELOG.rst
The changelog snippet was missing from the previous SQS change. This adds it and amends the entry in the changelog.
> Add missing changelog entry

- .changes/next-release/bugfix-retries-19921.json
- botocore/retries/standard.py
- tests/unit/retries/test_standard.py
The intent of the jitter in the exponential backoff calculation is to create a uniform random distribution.  However, the current calculation applies the truncation after the randomization.  This results in clamped/truncated distribution which is not what we want.
This only affects cases where the calculated backoff exceeds the `MAX_BACKOFF`, and is more pronounced the more you exceed `MAX_BACKOFF`. The current default of 3 max attempts is well below this value so this change has no effect on the default behavior.  A user would have to have a max attempts of at least 6 before this started to affect backoff times.
As an example, this is a distribution based on 10,000 events with `attempt=10` (x-axis is backoff time in seconds):
And here's the distribution with 10,000 events with …
> Fix calculation of truncated binary exponential backoff

- tests/functional/test_h2_required.py
Add custom marker for running model validation tests
> Add custom marker for checking validation

- scripts/ci/install-dev-deps
Our CI for Python >= 3.12 has started failing since [setuptools-71.0.0](https://github.com/pypa/setuptools/blob/main/NEWS.rst#v7100) was released on 7/17:
> Now setuptools declares its own dependencies in the core extra. Dependencies are still vendored for bootstrapping purposes, but setuptools will prefer installed dependencies if present. The core extra is used for informational purposes and should not be declared in package metadata (e.g. build-requires). Downstream packagers can de-vendor by simply removing the setuptools/_vendor directory. Since Setuptools now prefers installed dependencies, those installing to an environment with old, incompatible dependencies will not work. In that case, either uninstall the incompatible dependencies or upgrade them to satisfy those declared in …
> Fix CI for Python >= 3.12

- tests/functional/test_s3.py
This PR adds s3 specific tests to ensures the following:
* Leading dot segments in the key value are preserved in the URL path.
* Example: `../key.txt`
* Embedded dot segments in the key value are preserved in the URL path.
* * Example: `foo/../key.txt`
> Add S3 tests to ensure dot segments are preserved

- botocore/eventstream.py
- tests/unit/test_eventstream.py
This fixes a pair of event stream tests. Implementations of `application/vnd.amazon.eventstream` are expected to check the CRC before attempting to semantically parse the prelude. The tests meant to enforce that were present, but the wrong error was being asserted.
This change fixes the ordering of checks, fixes the tests, and adds two new test cases to make assertions about the error types that were previously being applied to the old tests.
> Update event stream tests

- .changes/next-release/enhancement-Python-365.json
- .github/workflows/run-crt-test.yml
- .github/workflows/run-tests.yml
- setup.py
- tox.ini
This PR will start provisional testing on the recently released beta for Python 3.13. This will be used to catch any issues early before the official release in October.
> Add support for Python 3.13

- botocore/args.py
- botocore/config.py
- botocore/configprovider.py
- botocore/exceptions.py
- botocore/httpchecksum.py
- tests/unit/test_args.py
This PR adds the ``request_checksum_calculation`` and ``response_checksum_validation`` config options. 
> [!NOTE]  
> This PR only implements the functionality to configure the new options and doesn't actually use them for anything yet.
A new configuration option will be introduced that allows users to configure request checksum calculation behavior. The following configuration methods will be supported:
* Environment Variable - ``AWS_REQUEST_CHECKSUM_CALCULATION``
* Profile Config - ``request_checksum_calculation``
* Client Config - ``request_checksum_calculation``
Supported values:
* ``WHEN_SUPPORTED`` (Default) - If operations are modeled with  ``"requestChecksumRequired":true`` OR a ``requestAlgorithmMember``, then a checksum will be calculated for all request payloads.
* …
> Add Flexible Checksum v2 Config Options

- botocore/httpchecksum.py
- tests/unit/test_httpchecksum.py
This PR adds support for the CRC64NVME checksum algorithm made available in `awscrt-0.22.0`. Similar to the existing CRC32C checskum algorithm, CRC64NVME will only be available when users have installed the optional CRT dependency. If CRT isn't installed and users try to this algorithm, a `MissingDependencyException` will be thrown.
> [!IMPORTANT]
> ~~Tests are currently expected to fail until https://github.com/boto/botocore/pull/3274 is merged.~~ https://github.com/boto/botocore/pull/3274 is merged and tests are passing.
> Add support for CRC64NVME when the CRT is available.

- .changes/next-release/bugfix-Config-98372.json
- botocore/args.py
- tests/functional/test_auth_config.py
Fixes a bug where the sigv4a_signing_region_set configuration in the config file and the corresponding environment variable would be ignored
> Sigv4a signing region set config bugfix

- tests/unit/test_parsers.py
The test we wrote for TaggedUnions is unnecessarily opinionated that there were only ever be a single warning raised during code execution. This PR makes it more lenient by only checking that the ~error was raised~ warning was logged, and ignoring the other captured records.
> Fix flakey test by allowing arbitrary warnings during capture

- .changes/next-release/bugfix-s3-44124.json
- botocore/handlers.py
This PR addresses a regression in the `SelectObjectContent` functionality that was introduced in Botocore `1.35.45`. This issue was identified in issue #3284.
> Fix event stream regression

- .changes/next-release/bugfix-s3-1405.json
- botocore/handlers.py
This PR updates the S3 200 Errors implementation (https://github.com/boto/botocore/pull/3276) to address bugs introduced in payload operations.
> Fix S3 200 Error handling

- botocore/config.py
- botocore/signers.py
- docs/source/client_upgrades.rst
- docs/source/topics/paginators.rst
This PR updates the bucket names to meet the policy which requires that special reserved bucket names be used for all examples and documentation content.
> Bucket name doc updates

- .changes/next-release/enhancement-QueryCompatibilityModeHeader-5257.json
- botocore/handlers.py
- botocore/model.py
- tests/functional/test_sqs.py
- tests/unit/test_handlers.py
This PR adds a custom header to inform a service that the SDK is running in query compatibility mode. This change enables support for services migrating away from the AWS Query protocol.
> Query compatibility mode header

- botocore/endpoint_provider.py
The current base class for EndpointResolutionError takes variable-length arguments; kwarg, and passing a positional argument to it returns a TypeError. This fix solves it by passing an argument in a proper format.
> Fixes the issue in EndpointExceptionError by changing the format of the error message.

- .github/workflows/run-crt-test.yml
- .github/workflows/run-tests.yml
Now that the original underlying issue appears to have been solved in setup-python in August. We can remove these special cased runners on the older hardware.
> Remove macOS fallback for setup-python issue

- botocore/data/polly/2016-06-10/examples-1.json
Fixes [Boto3 #4920](https://github.com/boto/boto3/issues/4290)
The examples in Polly's docs is misleading; the current suggested input is for content is `file://example.pls`, but that will cause the literal string of `file://example.pls` to be uploaded as the content, resulting in the following error:
```
InvalidLexiconException: An error occurred (InvalidLexiconException) when calling the PutLexicon operation: Invalid PLS Lexicon
```
Polly expects this input to be a lexicon as defined by the [PLS specificiation](https://www.w3.org/TR/pronunciation-lexicon/#S4.1).  This PR is to make it clearer that we will not open and retrieve the file contents on behalf of the customer, and that they must provide the contents of the pls directly.
> Update broken Polly example

- botocore/endpoint_provider.py
- tests/unit/test_endpoint_provider.py
The get_attr function is intended to be able to support an input with a path such as `[0]` and a value of `['foo']`and parse out the fist index of the value to get `foo` as the result.  
Without the change in this PR, the such an input will not match the indexing regex, and instead it will reach the else statement and reach the code intended to access dictionary indexes.  This will fail with a type error, so this PR updates the regex to properly reach the part of the code that handles indexes without a word string before them.  
That code still fails for the same input; it assumes that it is getting the index of a list from a dictionary, so it attempts to call `.get()` on the base input.  This will not work if the input value is not a dictionary, so we need to add the conditional to only …
> Add support for tuples in get_attr

- botocore/utils.py
- tests/unit/test_utils.py
When accessing an S3 bucket from the wrong region for opt-in regions, a 400 `IllegalLocationConstraintException` error is thrown. Botocore already has a functionality to automatically redirect requests to the correct region. This fix adds an additional condition to ensure that redirection happens whenever a request is made to the wrong region from opt-in regions.
> This change fixes region redirect issues for opt-in regions

- botocore/credentials.py
This PR introduces a new optional field, `account_id`, to the `Credentials` object. The `account_id` will default to `None` if not supplied. This addition enables the retrieval of an AWS account ID during credential resolution, which will then be used in the endpoint resolution process to construct endpoints that require an account ID.
The field will be added to the following classes:
* `Credentials`
* `RefreshableCredentials`
* `DeferredRefreshableCredentials`
* `ReadOnlyCredentials`
Testing for this change will be included in upcoming related PRs.
> Add account_id to credentials object

- botocore/credentials.py
- tests/unit/test_credentials.py
This PR introduces `account_id` to the environment variable credential provider. With this update, users can now provide an `AWS_ACCOUNT_ID` environment variable, which will be associated with the credentials when they are loaded.
Functional testing to ensure the `account_id` gets propagated and resolved to the correct endpoint for each credential provider will be added in an upcoming PR.
> Add account ID to the environment variable credential provider

- .changes/next-release/bugfix-Signing-82847.json
- botocore/auth.py
- tests/unit/auth/test_signers.py
This PR will exclude `Transfer-Encoding` from the headers considered for signing with SigV4. This prevents unintentional SignatureMismatch errors in the event a network intermediary drops the `Transfer-Encoding` header to replace it with a computed `Content-Length`.
> Remove Transfer-Encoding from signed headers

- .changes/next-release/enhancement-AWSCRT-25567.json
- setup.cfg
- setup.py
Updates botocore's dependency on the AWS Common Runtime (CRT) to use the latest version `awscrt-0.23.8`.
> Update awscrt version to 0.23.8

- botocore/compat.py
- botocore/httpchecksum.py
Some platforms automatically include a copy of the CRT in the environment, unbeknownst to the end user. In these cases, when the default checksum CRC64NVME is added to object uploaded through the console, boto3 will fail trying to validate the returned checksum.
This patch moves CRC64NVME out of the hot path for validation and will only attempt to process the received checksum when it's supported by the AWS CRT version on the machine.
> Restrict CRC64NVME support based on CRT version

- .changes/next-release/enhancement-Eventsteam-78927.json
- botocore/eventstream.py
- tests/unit/test_eventstream.py
In initial implementations of Event Streams, there was a 16MB payload limit for Event Stream payloads. Anything exceeding that was considered malformed. In more modern implementations, that limit has been raised with some services using 24MB. We'll be removing this client-side check going forward as it doesn't serve a practical purpose. The checksum will be used to validate the payload and size limitations will be left to the service to determine going forward.
> Remove payload length cap from Event Stream messages

- botocore/httpchecksum.py
This PR moves the log level for this message to debug to avoid spamming logs during normal operation. The current issues are legacy objects uploaded prior to January 15th or through the console. Once there is wider adoption of checksums, we'll move this log back to a more visible place.
> Drop log level for skipped validation

- botocore/credentials.py
- tests/unit/test_credentials.py
This PR adds support to source an account ID from `ContainerProvider`. We attempt to parse the `AccountId` field from the container credential endpoint response and store it to be associated with the credentials object.
> Add account id to container provider

- botocore/credentials.py
- tests/unit/test_credentials.py
This PR adds support to source an account ID from `ProcessProvider`. We attempt to parse account ID from the external process JSON output using the key `AccountId` or resolve the value of the profile property `aws_account_id` and store it to be associated with the credentials object.
> Add account id to process credentials provider

- .changes/next-release/enhancement-Protocols-98789.json
- botocore/args.py
- botocore/exceptions.py
- botocore/model.py
- tests/functional/test_supported_protocols.py
- tests/unit/test_args.py
This PR adds support for the new `protocols` trait, which allows a service to list a number of protocols it supports; botocore will automatically choose the highest priority supported protocol and use that to make requests to the service.
> Protocols trait support

- botocore/credentials.py
- botocore/session.py
- tests/integration/test_credentials.py
- tests/unit/test_credentials.py
- tests/unit/test_session.py
This PR introduces account ID to `SharedCredentialProvider` and `ConfigProvider`. The update allows users to specify an `aws_account_id` variable either in the shared credentials file, config file, or during client creation. The account ID will then be associated with the credentials when they are loaded.
> Add account ID to static credentials providers

- botocore/httpchecksum.py
Reverting a small portion of 590103bde8c18174afb9d17970c7e3d2520ca25a to fix some edge cases for DeleteObjects requests.
> Re-add handling for conditional-md5

- README.rst
Modernize the commands to use the same python interpreter. This will avoid mismatched links that may lead to confusion about what's being used/installed.
> Update setup and install commands

- botocore/args.py
- botocore/config.py
- botocore/configprovider.py
- botocore/credentials.py
- botocore/regions.py
- tests/functional/test_account_id_endpoints.py
- tests/unit/data/endpoints/test-cases/account-id.json
- tests/unit/data/endpoints/valid-rules/account-id.json
- tests/unit/test_args.py
- tests/unit/test_credentials.py
- tests/unit/test_endpoint_provider.py
This PR introduces the `account_id_endpoint_mode` configuration setting, which determines the client’s behavior for account ID based endpoint routing. When enabled and configured in a service’s ruleset, the endpoint resolver will attempt to resolve the account ID as an input parameter to the endpoint provider. The valid values for this setting are:
* `preferred`: The endpoint should include the account ID if available.
* `disabled`: The endpoint will not include the account ID, even if available.
* `required`: The endpoint must include the account ID. An exception will be raised if the account ID is unavailable.
If no value is provided, the default behavior will be `preferred`.
This PR also adds support for consuming the account ID in the ruleset during endpoint resolution. Specifically, …
> Add account_id_endpoint_mode and consume account_id in ruleset

- botocore/credentials.py
- tests/functional/test_credentials.py
- tests/unit/test_credentials.py
This PR adds support to source an account ID from `AssumeRoleProvider`, `AssumeRoleWithWebIdentityProvider`, and `SSOProvider`. The account ID will be resolved after receiving  a successful response from a given provider and then be associated with the credentials object.
> Add account id to STS and SSO providers

- .changes/next-release/feature-Endpoints-14344.json
- botocore/args.py
- botocore/config.py
- botocore/configprovider.py
- botocore/credentials.py
- botocore/regions.py
- botocore/session.py
- tests/functional/test_account_id_endpoints.py
- tests/functional/test_credentials.py
- tests/integration/test_credentials.py
- tests/unit/data/endpoints/test-cases/account-id.json
- tests/unit/data/endpoints/valid-rules/account-id.json
- tests/unit/test_args.py
- tests/unit/test_credentials.py
- tests/unit/test_endpoint_provider.py
- tests/unit/test_session.py
This PR adds support for account id-based endpoint routing which improves performance and scalability by using your AWS account ID to streamline request routing for services that support this feature. When using the SDK with a compatible credential provider and service, it will automatically construct an account ID-based endpoint instead of a regional endpoint that follows this format:
```
https://<account-id>.service.<region>.amazonaws.com
```
The following credential providers are supported:
* Environment variables
* Assume role provider
* Assume role with web identity provider
* AWS IAM Identity Center credential provider
* Static credentials providers
* Client creation `session.create_client()`
* Shared credential file (`~/.aws/credentials`)
* AWS config file (`~/.aws/config`)
* …
> Account ID Based Endpoint Routing

- .changes/next-release/enhancement-Protocol-13828.json
- botocore/parsers.py
- botocore/serialize.py
- tests/unit/cbor/test_cbor_decoding.py
Changes included:
- Bugfix on string serialization, 
- minor PR feedback on the parsers file 
- fixing a broken import
- adds a changelog
- no longer relies on the default byte order for int.to_bytes that was introduced in 3.11
- runs pre-commit on the cbor decoding tests.
> Note, this is still into the merge PR branch.  I'll open a final PR to develop after this is merged, but at that point everything will have been approved
> Preparing merge PR for RPCv2 CBOR

- botocore/args.py
Quick fix of a miss on the CBOR protocol before this support gets merged today.
> Move CBOR to be the highest supported protocol 

- .changes/next-release/enhancement-useragent-89566.json
- .changes/next-release/feature-useragent-5816.json
- botocore/args.py
- botocore/client.py
- botocore/context.py
- botocore/crt/auth.py
- botocore/paginate.py
- botocore/session.py
- botocore/useragent.py
- botocore/waiter.py
- tests/functional/test_useragent.py
- tests/unit/conftest.py
- tests/unit/test_context.py
- tests/unit/test_useragent.py
This PR implements scaffolding for tracking client feature usage in the user agent header. Features that we track are defined in `botocore.useragent._USERAGENT_FEATURE_MAPPINGS`. Whenever a trackable feature is used, its associated metric id is stored. When the user agent string is built, it retrieves all registered features and creates a comma-separated string with the `m/` prefix. For example, if a request is made using SigV4A signing, the user agent string may look like the following:
```
Boto3/1.36.13 md/Botocore#1.36.13 md/awscrt#0.23.8 ua/2.0 os/macos#24.2.0 md/arch#arm64 lang/python#3.11.10 md/pyimpl#CPython m/S cfg/retry-mode#legacy Botocore/1.36.13
```
Note the `m/S` component.
I prioritized an approach that tries to minimize invasiveness to the current codebase. Specifically, I …
> User agent 2.1: Track client features

- tests/unit/test_useragent.py
The test currently mocks the implementation with the wrong casing so it doesn't match `platform.python_implementation()`. Adjusting the mock to represent what we actually expect in real world use.
> Fix naming for python impl in user-agent

- .github/workflows/lint.yml
Full support for `ubuntu-20.04` was dropped on . See https://github.com/actions/runner-images/issues/11101 for more information.
This is resulting in the `lint` workflow failing with the following errors:
```
This is a scheduled Ubuntu 20.04 brownout. Ubuntu 20.04 LTS runner will be removed on 2025-04-01. For more details, see https://github.com/actions/runner-images/issues/11101
```
```
GitHub Actions has encountered an internal error when running your job.
```
This PR updates our lint workflow to use `ubuntu-latest`, similar to our other workflows.
> Update lint workflow to use ubuntu-latest

- .github/workflows/run-crt-test.yml
- .github/workflows/run-tests.yml
This PR adds concurrency control to the `run-tests` and `run-crt-test` GitHub Actions workflows.
Problem Description
Currently, when multiple commits are pushed to the same branch in succession, the `run-tests` and `run-crt-test` workflows are triggered for each push. This results in excessive use of GitHub Actions minutes as it's only necessary to run the workflows for the most recent push within a pull request.
Solution in This PR
This PR adds concurrency control to the `run-tests` and `run-crt-test` runners to cancel in-progress jobs when new commits are pushed to the same branch. Only the latest push will now trigger the workflows. However, this behavior does not apply to the `develop` and `master` branches, where all pushed commits should continue triggering `run-tests` and …
> Add concurrency control to run-tests and run-crt-test workflows

- botocore/compat.py
Some third-party vendors providing FIPS compliant versions of CPython have decided to entirely remove the `md5` function from hashlib instead of the using the existing convention of raising a `ValueError`. This patch will tolerate the removal more gracefully.
> Handle md5 being removed by third party CPython implementations

- docs/source/_static/404.html
- docs/source/_static/css/custom.css
- docs/source/_templates/domainindex.html
- docs/source/_templates/genindex.html
This update removes inline styles from some docs pages and transfers them to a separate CSS file. Additionally, I added genindex.html file because it uses inline scripts, and the only way to customize it is by copying it to our directory and editing it. This change has been tested in the dev environment.
> Updates the docs file so that the pages related to index and error are compliant of the security policy.

- README.rst
This PR adds a notice with target date for end of support of Python 3.8 across Boto3, Botocore and the AWS CLI v1. This follows the originally announced deprecation timeline in [our blog post](https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/).
> Add 3.8 deprecation date

- docs/source/_static/404.html
- docs/source/_static/css/custom.css
- docs/source/_templates/genindex.html
- docs/source/_templates/page.html
- docs/source/_templates/partials/icons.html
- requirements-docs-lock.txt
- requirements-docs.txt
Description
This PR upgrades Sphinx and Furo dependencies used for documentation generation.
Changes:
- Upgrades Sphinx to 7.1.2 for Python 3.8 and 7.4.7 for Python 3.9 and above
- Upgrades Furo to version 2024.08.06
- Updates `page.html` template to address changes from Furo version bump
- Adds CSS to fix alignment and spacing of theme and menu toggles
- Adds `skip-to-content` accessibility feature
> Upgrade Sphinx and Furo dependencies

- tests/functional/test_useragent.py
We don't want to do inline typing in botocore because it creates issues with external packages and when there are incomplete types it causes Mypy/Pyright to come to weird conclusions. We want to stick to docstrings instead.
> Remove inline typing from user agent tests

- botocore/args.py
- botocore/serialize.py
- botocore/useragent.py
- tests/functional/test_rpc_v2_cbor.py
Description
This PR adds support for tracking usage of the `PROTOCOL_RPC_V2_CBOR` feature.
User agent strings can now include an 'M' in the `m/` metrics field when an operation is called using the Smithy RPC v2 CBOR protocol. 
User agent string example:
```
Boto3/1.37.9 md/Botocore#1.37.9 ua/2.1 os/macos#24.3.0 md/arch#arm64 lang/python#3.12.8 md/pyimpl#CPython m/M cfg/retry-mode#legacy Botocore/1.37.9
```
See #3389 for more details on client feature tracking.
> Track RPC v2 CBOR feature

- botocore/__init__.py
- botocore/handlers.py
- tests/functional/test_socialmessaging.py
- tests/unit/test_utils.py
During a previous manual customization to rename this method, there was a human error which caused the command to be named incorrectly.  This PR allows both the old name and the new name to be used in botocore and boto3.  This must be released on the same day as [the associated CLI v1 PR](https://github.com/aws/aws-cli/pull/9450).
Generating the docs shows that this now has the correctly documented name and does not show the old name:
> Alias command for socialmessaging

- botocore/args.py
After discovery of a bug with regards to protocol selection, we are reverting this pending a fix.  More details to come in follow up PR
> Revert protocol priority change

- botocore/httpchecksum.py
- botocore/response.py
- tests/unit/test_httpchecksum.py
- tests/unit/test_response.py
This adds a readinto implementation to StreamingBody, following the
contract outlined in the Python io package.
The primary motivation for this is that it allows consumers to wrap the
StreamingBody in an io.BufferedReader. This provides a nice performance
boost for parsing streaming binary data formats, where you want to be
able to read small numbers of bytes in your parsing algorithm, but
benefit from reading large chunks of data from upstream.
> Add readinto to StreamingBody

- botocore/httpsession.py
This PR is an attempt to minimize noise from end-users installing broken copies of PyOpenSSL on their system. If the module can't be imported, we can have confidence that the patching isn't being done to the base SSLContext. This should address unnecessary impact like what's seen in boto/boto3#3585.
> Catch AttributeError when broken version of PyOpenSSL installed

- botocore/endpoint.py
Fixes the typing information on `convert_to_response_dict` from prior to us dropping Requests as the default HTTP client.
> Remove legacy reference to Requests

- pyproject.toml
Missed in #3495, this is no longer needed.
> Remove unused isort configuration

- tests/functional/test_s3.py
This commit adds a test to ensure that request checksums are only calculated and applied once, even in the event of retries.
> Add test to ensure retries reuse request checksum

- tests/integration/test_smoke.py
Temporarily disable Elastic Beanstalk smoke tests
> Disable elastic beanstalk smoketests

- botocore/configprovider.py
This PR moves the abstracted STS settings back to the centralized config provider.
> Consolidate STS settings back to centralized location

- botocore/client.py
- botocore/handlers.py
- tests/functional/test_query_compatibility.py
There's a fundamental problem with our query compatibility mode, rooted in how SQS implemented protocol migration and how error handling has evolved in AWS SDKs.
The Query protocol is unique because it can model error code information within errors themselves. Other protocols (JSON, CBOR) cannot include "error" fields in exception shapes.
Error codes help map exceptions to specific error classes (e.g., cloudwatch.exceptions.ResourceNotFound).  Each modeled error has a "code" associated with it which will map to the specific class.  This code comes straight from the "code" key from the "error" fields in the json model.  If the error does not have a code, the shape name is used as a fallback.
-  SQS migrated protocols before services were able to model support for multiple protocols
- …
> Query compatibility bugfix

- .changes/next-release/enhancement-Python-78496.json
- setup.py
- tests/functional/leak/test_resource_leaks.py
The first release candidate for Python 3.14 is tentatively scheduled for July 22nd ([ref](https://peps.python.org/pep-0745/)). We've been stable through the beta process and since we're entering feature lock, we should be good to start advertising support to enable other tools to onboard early.
This PR raises our memory threshold to 13MB (ideally temporarily) due to the mac client specifically having a larger memory footprint than before. We saw similar issues in Python 3.13 that were corrected prior to the final release. We should revisit this test once we get to that point.
> Add official Python 3.14 support with first release candidate

- .changes/next-release/bugfix-bedrock-37870.json
- botocore/handlers.py
- tests/unit/test_handlers.py
This PR updates the bearer authentication logic to align with the intended behavior: bearer auth should only be applied to services that:
1. Use the SigV4 signing name `bedrock`, and
2. Have the `smithy.api#httpBearerAuth` trait in their model
Previously, bearer auth was applied to all services with the `bedrock` signing name if a token was present, including unsupported services like `bedrock-agent`, which resulted in runtime failures. This update narrows the logic to match expectations and prevents invalid auth headers from being sent.
* Updated `_should_prefer_bearer_auth` to check both signing name and presence of `httpBearerAuth` in `auth_options`
* Added a test case to ensure unsupported `bedrock` services no longer receive bearer auth
> Restrict bedrock bearer auth by trait

- .changes/next-release/enhancement-sso-48422.json
- botocore/credentials.py
- tests/functional/test_credentials.py
- tests/unit/test_credentials.py
This is a port of https://github.com/aws/aws-cli/pull/9356
- Updated `SSOCredentialFetcher` to check if the cached legacy token is expired according to the local clock. If expired, it will raise an `UnauthorizedSSOTokenError` instead of sending an expired token to Identity Center's `GetRoleCredentials` API.
- Added a unit test to verify when an expired token is cached, that GetRoleCredentials is not called and `UnauthorizedSSOTokenError` is raised.
- Ran all test suites (unit, functional, integration, etc.) and CI.
- The following script was used in boto3 to test the code.
```python
import logging
import boto3
from boto3 import client, set_stream_logger
boto3.setup_default_session(profile_name='SSO-PROFILE-NAME')
client = client('s3')
set_stream_logger('', logging.DEBUG)
response = …
```
> SSOTokenLoader expiration check

- botocore/auth.py
- botocore/crt/auth.py
- botocore/endpoint.py
- botocore/signers.py
- botocore/utils.py
- tests/__init__.py
- tests/functional/test_ec2.py
- tests/functional/test_lex.py
- tests/functional/test_retry.py
- tests/functional/test_s3express.py
- tests/functional/test_sts.py
- tests/unit/auth/test_signers.py
- tests/unit/test_credentials.py
- tests/unit/test_signers.py
- tests/unit/test_utils.py
This PR resolves the Python 3.12 `DeprecationWarning` thrown when botocore calls `datetime.datetime.utcnow()`.
@nateprewitt, this PR differs from other attempts posted to this repo by _ensuring `datetime` instances are still timezone-unaware_:
```python
import datetime
datetime.datetime.utcnow()
datetime.datetime.now(datetime.timezone.utc)
datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)
```
I ran this through CI in my own repo and [it passes cleanly](https://github.com/kurtmckee/pr-botocore/actions).
Fixes boto/boto3#3889.
> Resolve Python 3.12 `.utcnow()` `DeprecationWarning`

- botocore/args.py
- botocore/auth.py
- botocore/client.py
- botocore/credentials.py
- botocore/discovery.py
- botocore/handlers.py
- botocore/hooks.py
- botocore/httpchecksum.py
- botocore/httpsession.py
- botocore/paginate.py
- botocore/parsers.py
- botocore/regions.py
- botocore/response.py
- botocore/session.py
- botocore/tokens.py
- botocore/useragent.py
- botocore/utils.py
- pyproject.toml
- tests/unit/response_parsing/test_response_parsing.py
Many logging calls within Botocore were eagerly formatting messages, which is a performance (cycles, memory) issue, and could in rare cases cause the code calling logging to fail (think an unformattable object).
This PR enables the Ruff [G (`flake8-logging-format`) group](https://docs.astral.sh/ruff/rules/#flake8-logging-format-g) and fixes the found issues.
> Fix logging calls to defer formatting messages until needed

- botocore/utils.py
If a command like `aws s3 cp` is spawned simultaneously (and for the first time), different processes might try to create this directory simultaneously, resulting in an unnecessary exception.
Fixes aws/aws-cli#6489
> Avoid a race condition on directory creation

- .gitignore
- botocore/regions.py
- tests/unit/test_endpoint_provider.py
Fixes a bug where setting `use_ssl=False` with a custom HTTPS endpoint incorrectly downgrades the connection to HTTP. According to the [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html), when `endpoint_url` is provided, the `use_ssl` parameter should be ignored. The fix adds a check to ensure this downgrade only happens when no custom endpoint is specified, preserving the HTTPS protocol when customers explicitly provide an HTTPS URL.
**Links:**
- GitHub Issue: https://github.com/boto/boto3/issues/4252
- Code location: https://github.com/boto/botocore/blob/develop/botocore/regions.py#L524
- Documentation: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html
Fixes boto/boto3#4252
> Fix use_ssl parameter ignored when custom HTTPS endpoint_url provided

- botocore/awsrequest.py
- tests/unit/test_awsrequest.py
Fixes HTTP 100 Continue parsing to accept responses without reason phrases, as allowed by RFC9110. The `_is_100_continue_status()` method currently requires exactly 3 parts (`HTTP/1.1 100 Continue`), which prevents botocore from recognizing valid HTTP 100 responses, causing the client to never see "100 Continue response seen". This breaks compatibility with legitimate HTTP servers that follow the current HTTP specification. The fix changes `len(parts) >= 3` to `len(parts) >= 2` to accept both formats (`HTTP/1.1 100 Continue` or `HTTP/1.1 100`) while maintaining backward compatibility with existing servers.
**Links:**
- GitHub Issue: https://github.com/boto/botocore/issues/3455
- Code location: https://github.com/boto/botocore/blob/develop/botocore/awsrequest.py
- RFC9110 specification: …
> Fix HTTP 100 Continue parsing to accept optional reason phrase

- botocore/credentials.py
- botocore/signers.py
- tests/functional/test_credentials.py
This PR modifies the registration timing of feature IDs for IMDS and HTTPS credentials by moving the registration logic from signers.py to credentials.py. This change ensures feature IDs are registered at the point of credential retrieval rather than during signing. [This](https://github.com/boto/botocore/pull/3539) is the initial PR that registered the two feature ids.
changes:
```
- Moved registration of CREDENTIALS_HTTP and CREDENTIALS_IMDS feature IDs from signers.py to credentials.py
- Modified the functional tests to reflect the changes and validated that the feature ids are registered each time the imds and http credentials are retreived.
Tests:
Validated the changes with functional tests.
```
> Refactor feature ID registration for IMDS and HTTP credential providers

- botocore/httpsession.py
- tests/unit/test_http_session.py
When using concurrent.futures to execute tasks asynchronously, if a task is canceled before it is able to be raised, an instance of `concurrent.futures.CanceledError` will be raised.  This can happen if they python interpreter is asked to shut down, for instance if a user presses Ctrl-C.
Any errors raised while the request is in transit will be caught and wrapped in a generic retryable `HTTPClientError` in httpsession.py.  Since the [CancelledError inherits from Python's `Exception` class](https://github.com/python/cpython/blob/af58a6f883108f02996c784de010df62e75f5e13/Lib/concurrent/futures/_base.py#L39-L45), when a cancel is initiated while a request is in-flight this winds up getting caught and the request is retried.  Each retry will also raise a CancelledError, and this will continue …
> Fix CancelledError retry loops to enable immediate S3 upload cancellation

- botocore/data/_retry.json
Adds a new retryable DynamDB error to the legacy retry config.
> Add ReplicatedWriteConflictException to legacy retry config

- botocore/args.py
- botocore/handlers.py
- botocore/serialize.py
- tests/unit/test_serialize.py
Currently, only the ISO8601 timestamp format supports sub-second precision (microseconds). However, the [Smithy standard](https://github.com/smithy-lang/smithy/blob/main/designs/defining-timestamps.md#protocol-limitations-rationale) specifies millisecond precision as the maximum supported granularity.
This mismatch is causing issues for bedrock-agentcore, which requires millisecond-precise timestamps to function correctly. This PR adds service-level millisecond precision support that complies with Smithy standards while maintaining backward compatibility.
Introduces a new `creating-serializer` event that allows services to override timestamp precision during serializer creation. We can customize services to allow them to opt into millisecond precision without requiring client-side …
> Support default millisecond timestamp precision for custom services
