- botocore/data/aws/kms/2014-11-01.normal.json
This updates the KMS docs to the publicly available docs.
> Update KMS docs

- botocore/data/aws/iam/2010-05-08.normal.json
This updates the documentation for IAM. Most of the changes look like the removal of doc strings on the top level request and response shapes, but we do not use those so that should be fine.
> Update docs for IAM

- setup.py
> Bump jmespath version to 0.6.1

- botocore/config.py
- tests/unit/test_config.py
- tests/unit/test_session.py
See https://github.com/boto/botocore/pull/461#issuecomment-77001875 for more info.
> Remove _path key when parsing INI config files

- tests/unit/auth/test_signers.py
In some of the sigv4 tests we were signing the request twice
to see what to ensure we're handling the resign case properly.
However, the sigv4 tests were not patching out the current time
which meant that it was possible to have test failures if the time
between add_auth calls crossed the seconds boundary.
cc @danielgtaylor @kyleknap
> Fix flaky unit test by fixing date

- botocore/model.py
- tests/unit/test_model.py
> Add documentation properties to service/op models

- botocore/model.py
- tests/unit/test_model.py
Continuation of https://github.com/boto/botocore/pull/496
> Add a wire_name property to op model

- botocore/operation.py
- botocore/service.py
- botocore/session.py
- tests/unit/test_deprecations.py
Bumped the pending deprecation warnings to straight up deprecation warnings.
> Switch pending deprecations to deprecation warings

- README.rst
> Update README to include plan for GA

- botocore/data/aws/opsworks/2013-02-18.normal.json
Fixes https://github.com/aws/aws-cli/issues/1244
> Update opsworks to latest model (docs only)

- setup.py
Contains bug fixes and two new functions.
cc @kyleknap
> Bump version of jmespath to 0.6.2

- setup.py
> Bump jmespath dep to 0.7.0

- botocore/data/aws/ec2/2015-03-01.normal.json
This updates the enumerated values for ``ImageState`` and the docs are updated such that "for Linux" is appended to whenever "EC2 User Guide" is used.
Fixes: https://github.com/boto/botocore/issues/514
cc @jamesls
> Update ec2 model for docs and enumerated values

- setup.py
This fixes a regression reported in the AWS CLI: https://github.com/aws/aws-cli/issues/1306
cc @kyleknap
> Bump jmespath dep to latest version 0.7.1

- README.rst
Also put the steps that are done with a bold prefix to make it easier to see.
cc @kyleknap
> Update README with date of first alpha release

- botocore/utils.py
- tests/unit/test_utils.py
> Simplify regex for endpoint validation

- requirements.txt
- requirements26.txt
- setup.py
> Add support for wheel files

- setup.py
> Bump dependency of bcdoc

- tests/integration/test_s3.py
Helps avoid integ test failures.  There's now 25 bytes of randomness in the bucket name.
Names now look like:
```
botocoretest4d551a678695bea63f172b1e23366fe0a225c90d0b1b6cd56a
botocoretestfe9cd6d11ef23539f290884ac8456957ff966a225a0e6df64e
botocoretestce08ec0ae1287a997203e8412ba3dbf410e2a585cf298d79ed
botocoretest46b4f00e529b60313ba8bf79c35030ed9792cecd94be6ad417
```
> Use more random bucket names in integ tests

- botocore/handlers.py
- tests/unit/test_handlers.py
Fixes #509 
Fix is in https://github.com/boto/botocore/commit/5e568c5fa53e9bb8ec9b8809e1b53de271485511, there's an additional commit that cleans up some of the flake8 issues.
> Only quote path component of url for copy source

- tests/functional/test_waiter_config.py
Makes it quicker to review contributions for waiter
configs.
> Add start of basic waiter model validation

- botocore/docs/service.py
- tests/unit/docs/test_service.py
This makes the same title changes as the boto3 doc update: https://github.com/boto/boto3/pull/149
> Use module names for service titles

- docs/source/topics/index.rst
- docs/source/topics/paginators.rst
> Adding paginator documentation

- botocore/data/iam/waiters-2.json
> Add waiters for IAM

- docs/source/development/designnotes.rst
- docs/source/development/index.rst
This is just a place to collect various design rationale for
botocore for those curious.
> Add start of design notes documentation

- botocore/loaders.py
- tests/unit/test_loaders.py
- tests/unit/test_waiters.py
> Added validation to ensure that service names passed in conform to those exposed by the service model

- setup.py
> Lock jmespath version to 0.7.1-1.0.0

- tests/cmd-runner
Verified via:
```
$ aws configure list
Name                    Value             Type    Location
----                    -----             ----    --------
profile                <not set>             None    None
...
region                <not set>             None    None
```
```
$ nosetests test_client_leaks.py >/tmp/foo 2>&1
```
> Use a default region of us-west-2 to run leak tests

- setup.cfg
Similar fix from: https://github.com/boto/boto3/pull/282
> Override python deps version in setup.cfg

- CONTRIBUTING.rst
> Update contributing guide with latest model format

- botocore/data/ec2/2015-10-01/paginators-1.json
- botocore/data/glacier/2012-06-01/paginators-1.json
- botocore/data/iam/2010-05-08/paginators-1.json
Adding some missing paginators for IAM, Glacier, and EC2.
> Add paginators

- botocore/awsrequest.py
Fix for a test regression from previous pull request.
> Don't use super() for old style class

- botocore/data/dynamodb/2012-08-10/paginators-1.json
This is based on PR #689, and fixes aws/aws-cli#1423
> Fix dynamodb paginator count

- botocore/data/apigateway/2015-07-09/paginators-1.json
- botocore/data/apigateway/2015-07-09/service-2.json
cc @jamesls @mtdowling @rayluo @JordonPhillips 
Fixes https://github.com/aws/aws-cli/issues/1595
> Fix issue with API Gateway model

- botocore/endpoint.py
- botocore/exceptions.py
- tests/unit/test_endpoint.py
New test case is added. Also simplify the existing test cases a little bit.
> Wrap the BadStatusLine with a clear description

- botocore/data/sqs/2012-11-05/examples-1.json
- botocore/docs/sharedexample.py
Also updated the formatting for a missing newline. Here is what it looks like:
> Add shared example for sqs

- botocore/credentials.py
- tests/unit/test_credentials.py
I think a better long term solution will involve allowing
a client to configure how timestamps are parsed, but that
will require a much larger change.  For now, I'd like to
fix the immediate bug.
Fixes #745 
Also manually confirmed this works in botocore/CLI.
> Account for datetime objects in assume role cred provider

- botocore/validate.py
Reverts boto/botocore#774
We cannot merge to master.
> Revert "Fix docstring typo"

- botocore/validate.py
Against the develop branch this time. 
@kyleknap
> Fix docstring typo

- .travis.yml
> Update travis config to fail pr's to master

- botocore/endpoint.py
Should address the remaining issues with #760.
cc @jamesls @kyleknap @rayluo
> Disable pyopenssl.

- botocore/data/opsworks/2013-02-18/waiters-2.json
> Add opsworks waiters

- tests/unit/protocols/input/rest-json.json
- tests/unit/protocols/input/rest-xml.json
- tests/unit/protocols/output/query.json
- tests/unit/protocols/output/rest-json.json
> Update protocol tests to latest versions

- botocore/stub.py
- docs/source/reference/stubber.rst
Closes boto/boto3#378
When I added the stubber, I forgot to add it to the generated docs.
> Add Stubber to the docs.

- botocore/config.py
> Fix doc string for Config

- NOTICE
When we updated requests, we forgot to update our NOTICE
> Charade -> Chardet in NOTICE

- tests/integration/test_smoke.py
> Update smoke tests with latest services

- botocore/data/ec2/2015-10-01/waiters-2.json
Should get test passing for https://github.com/boto/boto3/pull/532
> Sync ec2 waiters

- CHANGELOG.rst
> Backfill changelog for 1.4.6

- tests/integration/test_apigateway.py
> Skip API gateway test if we hit throttle limit

- botocore/docs/sharedexample.py
- tests/unit/docs/test_sharedexample.py
> Account for empty input shape missing

- botocore/data/codecommit/2015-04-13/paginators-1.json
> Add paginators for codecommit

- scripts/new-change
Same as the CLI version, with the default values being switched to `boto/botocore`.
> Add new-change script to botocore

- .changes/1.3.27.json
- .changes/1.3.28.json
- .changes/1.4.0.json
- .changes/1.4.1.json
- .changes/1.4.10.json
- .changes/1.4.11.json
- .changes/1.4.2.json
- .changes/1.4.3.json
- .changes/1.4.4.json
- .changes/1.4.5.json
- .changes/1.4.6.json
- .changes/1.4.7.json
- .changes/1.4.8.json
- .changes/1.4.9.json
> Backfill change json files

- tests/functional/test_iot_data.py
Warnings are not emitted after the first time, so this
test was dependent on the order in which the tests are run.
It relied on the fact that the test was triggering the warning
for the first time in the test suite.
On a machine that actually has an older version of TLS that would
normally trigger this warning, any previous call to ``.create_client()``
would trigger this warning.  As a result, this test would fail, assuming
it was run after a test that had created an ``iot-data`` client.
> Patch out warnings.warn call in iot-data tests

- .changes/next-release/feature-opsworks.json
- botocore/data/opsworks/2013-02-18/waiters-2.json
> Add InstanceRegistered opsworks waiter

- botocore/auth.py
- botocore/client.py
- botocore/compat.py
- botocore/credentials.py
- botocore/docs/bcdoc/textwriter.py
- botocore/docs/example.py
- botocore/docs/params.py
- botocore/exceptions.py
- botocore/handlers.py
- botocore/hooks.py
- botocore/paginate.py
- botocore/retryhandler.py
- botocore/session.py
- botocore/signers.py
- botocore/utils.py
- botocore/validate.py
We had some PEP8 issues built up, so I decided to go clean up the ones that could be cleaned.
> Address most of the PEP8 issues.

- .changes/next-release/feature-iam.json
- botocore/data/iam/2010-05-08/paginators-1.json
Adds four new paginators:
* GetAccountAuthorizationDetails
* ListSSHPublicKeys
* SimulateCustomPolicy
* SimulatePrincipalPolicy
Closes #919
> Update IAM paginators

- .changes/next-release/feature-s3.json
- botocore/data/s3/2006-03-01/paginators-1.json
> Add paginator for ListObjectsV2

- botocore/data/ec2/2015-10-01/paginators-1.json
See https://github.com/boto/boto3/issues/668; @kyleknap interest
> Add paginator for DescribeSpotFleetRequests

- botocore/handlers.py
- tests/unit/test_handlers.py
> Switch cache keys to snake case

- .coveragerc
- .travis.yml
- README.rst
Switch to codecov for coverage reports.
> Switch to codecov for coverage reports

- .changes/next-release/feature-codedeploy-60730.json
This is a changelog entry for #977
cc @kyleknap @jamesls @chrisradek
> Add changelog entry for DeploymentSuccessful watier

- botocore/session.py
- tests/integration/test_credentials.py
Fixes https://github.com/boto/boto3/issues/686
> Check if access_key_id is None in session.create_client

- .changes/next-release/bugfix-Serialization-71811.json
- botocore/serialize.py
- tests/unit/protocols/input/rest-xml.json
- tests/unit/test_serialize.py
Fixes https://github.com/aws/aws-cli/issues/2030
Read there for background. Also let me know if you think we need a test for this
cc: @JordonPhillips
> Properly handle boolean query string arguments

- botocore/signers.py
Fix misspellings + made documented argument capitalization consistent with actual code
> Fix typos in generate_presigned_post docstring

- botocore/data/ec2/2016-04-01/waiters-2.json
Simple enhancement to add waiter for NetworkACL creation.
> Add waiter NetworkAclExists to waiters.

- botocore/data/apigateway/2015-07-09/service-2.json
Adds some new enumeration values to API Gateway model.
> Update API Gateway model

- botocore/data/ecr/2015-09-21/paginators-1.json
> Update ECR paginators

- botocore/credentials.py
Closes #1065
cc @kyleknap @stealthycoin @jamesls
> Document possible credential race condition

- botocore/data/waf/2015-08-24/paginators-1.json
Add paginators for the [AWS WAF](http://docs.aws.amazon.com/waf/latest/APIReference/API_Operations.html) service:
* ListByteMatchSets
* ListIPSets
* ListRules
* ListSizeConstraintSets
* ListSqlInjectionMatchSets
* ListWebACLs
* ListXssMatchSets
> Add WAF paginators

- tests/integration/test_s3.py
> Delete created buckets

- tests/unit/test_loaders.py
> Use os path seps in loader tests

- botocore/credentials.py
> Properly log skipping environment credentials

- .changes/next-release/feature-parameter-5401.json
- botocore/docs/method.py
- botocore/docs/params.py
- botocore/handlers.py
- botocore/model.py
- tests/functional/docs/test_ec2.py
- tests/functional/test_ec2.py
- tests/functional/test_s3.py
- tests/unit/test_handlers.py
- tests/unit/test_idempotency.py
cc @kyleknap @JordonPhillips @jamesls
> Idempotent param

- .changes/next-release/feature-opsworkscm-53312.json
- botocore/data/opsworkscm/2016-11-01/waiters-2.json
> Add waiters for opsworks cm

- .changes/next-release/feature-health-85922.json
- botocore/data/health/2016-08-04/paginators-1.json
> Add paginators for health

- botocore/data/config/2014-11-12/paginators-1.json
...because paginators are nice things to have.
> Add paginators for configservice APIs

- .changes/next-release/bugfix-Python36-32655.json
- .changes/next-release/feature-useragent-23881.json
- .travis.yml
- botocore/awsrequest.py
First pass without considering using chunked_encoding for anything.
Fixes #1079 
cc @jamesls @JordonPhillips @kyleknap
> Python 3.6 HTTPConnection support

- tests/unit/cfg/aws_third_config
- tests/unit/test_configloader.py
Added a test for some uncovered paths.
cc @dstufft @kyleknap @JordonPhillips @jamesls
> Test multi config loading

- README.rst
cc @jamesls @JordonPhillips @stealthycoin @dstufft @ljrivers
> Added getting help section

- botocore/data/efs/2015-02-01/paginators-1.json
cc @jamesls @kyleknap @JordonPhillips @dstufft
> New paginator for efs

- tests/functional/test_endpoints.py
cc @jamesls @dstufft @JordonPhillips @kyleknap
> Test that endpoints can all be made into clients

- botocore/credentials.py
- botocore/utils.py
- tests/unit/test_credentials.py
- tests/unit/test_utils.py
You can now provide a full url in addition to a relative url to retrieve credentials.
I've added hostname validation to only allow the ECS IP and localhost.
Anything else results in an exception being raised.
cc @kyleknap @JordonPhillips @stealthycoin @dstufft 
cc @jasdel
> Generalize container credential provider

- botocore/paginate.py
- botocore/utils.py
We should only be using botocore.compat
Fixes #1106.
> Don't import from six directly

- tests/functional/test_six_imports.py
Should help prevent this issue from happening again.
Bare six
```
======================================================================
FAIL: tests.functional.test_six_imports.test_no_bare_six_imports('botocore/botocore/configloader.py',)
----------------------------------------------------------------------
File ".virtualenvs/aws-cli/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "botocore/tests/functional/test_six_imports.py", line 25, in _assert_no_bare_six_imports
checker = SixImportChecker(filename).visit(parsed)
File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 241, in visit
return visitor(node)
File …
```
> Add linting for bare six imports

- botocore/handlers.py
> Fix AttributeError in the glacier tree hash docs

- .travis.yml
See:
https://docs.travis-ci.com/user/caching/#pip-cache
> Enable pip cache in Travis CI builds

- .changes/next-release/enchancement-Organizations-12579.json
- botocore/data/organizations/2016-11-28/paginators-1.json
I added the pagination definitions for the organizations service.
> Added paginators for the Organizations service

- .changes/next-release/enhancement-SSM-97113.json
- botocore/data/ssm/2014-11-06/paginators-1.json
Adding a paginator for SSM describe_parameters.
> Add SSM describe_parameters paginator

- botocore/data/kinesis/2013-12-02/paginators-1.json
Related: #1237
cc @stealthycoin @dstufft
> Update kinesis non_aggregate_keys

- botocore/data/codebuild/2016-10-06/paginators-1.json
> Add paginators for codebuild

- botocore/client.py
- botocore/endpoint.py
- botocore/history.py
- botocore/utils.py
- tests/functional/test_history.py
- tests/unit/test_history.py
cc @dstufft @jamesls @kyleknap @joguSD @JordonPhillips
> Add history recorder

- .changes/next-release/bugfix-rekognition-90766.json
- botocore/data/rekognition/2016-06-27/paginators-1.json
This adds FaceModelVersions to the output tokens.
> Update rekognition list_collections paginator

- botocore/data/pricing/2017-10-15/paginators-1.json
> Adding pricing paginators

- botocore/data/ec2/2016-11-15/paginators-1.json
@kyleknap I added a paginator for `describe_spot_fleet_instances` based on your comments in https://github.com/boto/botocore/pull/943.
Let me know if this looks OK!
> add spot_fleet_request_instances paginator

- botocore/data/sagemaker/2017-07-24/waiters-2.json
> Add waiters for sagemaker

- .changes/next-release/enhancement-Paginator-98611.json
- botocore/data/lambda/2015-03-31/paginators-1.json
Resolves boto/boto3#1394
Tested pagination functions correctly manually.
> Add pagination support for lambda list aliases operation

- botocore/data/ssm/2014-11-06/paginators-1.json
Apologize in advance if you want tests for this.
> Add paginator for get_parameters_by_path

- requirements.txt
- tests/functional/test_waiter_config.py
This validates waiter files against a json schema to ensure that they
are at least structurally valid.
> Validate waiters against schema

- botocore/data/_retry.json
Add retry support for the `RequestThrottledException`.
> Add RequestThrottledException to the default retry policies

- tests/integration/test_credentials.py
This reduces transient failures in this test by requiring
the assume role call to work N times (default of 4).  In between
each success there's a sleep of success_delay seconds.
This adds ~12 seconds of additional time to these integration
tests, but largely reduces the transient failures.
I also had to fix a bug related to shared credential file loading.
> Require wait_for_assume_role to have N successes

- botocore/client.py
- tests/functional/test_s3.py
An unsigned request would default to the existing host of
's3.amazonaws.com' when attempting to switch to virtual
host addressing.  This is incorrect for regions outside of
the 'aws' partition.  The fix here is to use a default
endpoint url of `None` for `fix_s3_host`, which will result
in parsing out the hostname from the url when constructing
the virtual hosted address.
> Fix s3 addressing for unsigned requests in cn-north-1

- .changes/next-release/bugfix-s3-33836.json
- botocore/utils.py
- tests/unit/test_utils.py
> Revert "Make redirects for S3 head bucket and object more strict"

- requirements.txt
- setup.cfg
- setup.py
> Revert "Allow newer versions of dateutil"

- requirements.txt
- setup.cfg
- setup.py
> Revert "Revert "Allow newer versions of dateutil""

- botocore/eventstream.py
Update the S3 Select example to ensure that the end event was received.
> Update S3 Select example

- botocore/data/dynamodb/2012-08-10/paginators-1.json
This adds paginator for DynamoDB ListBackups method
> Adding missing paginator for ListBackups for DynamoDB

- botocore/model.py
- botocore/utils.py
- docs/source/topics/paginators.rst
Deduplicate 'the' in errors and docs
> Deduplicate 'the' in errors and docs

- .changes/next-release/enhancment-TimestampSerialization-34620.json
- botocore/model.py
- botocore/serialize.py
- tests/unit/protocols/input/ec2.json
- tests/unit/protocols/input/json.json
- tests/unit/protocols/input/query.json
- tests/unit/protocols/input/rest-json.json
- tests/unit/protocols/input/rest-xml.json
- tests/unit/protocols/output/ec2.json
- tests/unit/protocols/output/json.json
- tests/unit/protocols/output/query.json
- tests/unit/protocols/output/rest-json.json
- tests/unit/protocols/output/rest-xml.json
Add support for more timestamp formats.
> Timestamp format

- botocore/utils.py
- tests/unit/test_utils.py
We attempt to automatically redirect 400s for `Head*` operations to catch the case that a redirect was automatically followed by requests but fails authorization because it was signed with the wrong region. This can lead to infinite recursion in the case that we get a 400 but the redirection header is not present (e.g. the bucket doesn't exist). In this case we would fallback to attempting another `HeadBucket` to get the region header which leads to infinite recursion.
> Only auto-redirect 400s for s3 head operations if region header is present

- botocore/awsrequest.py
- tests/integration/test_s3.py
- tests/unit/test_awsrequest.py
> Don't attempt to reset a body of type bytearray

- .changes/next-release/bugfix-Serialization-93419.json
- botocore/awsrequest.py
- tests/unit/test_awsrequest.py
Fixes https://github.com/boto/botocore/issues/1557
> Ensure dict bodies are utf-8 encoded before being url encoded

- botocore/data/eks/2017-11-01/service-2.sdk-extras.json
This will mitigate aws/aws-cli#3602
> Inject EKS service id

- tests/unit/test_args.py
Specifically require a lot less boilerplate code to get client args and make assertions.
> Refactor test_args

- tests/functional/test_credentials.py
This was already existing behavior, but this test verifies that if you add a region via `session.set_config_variable` that the assume role provider will use the configured region.
> Add test to verify correct region in assume role provider

- botocore/monitoring.py
- tests/functional/csm/cases.json
- tests/functional/csm/test_monitoring.py
- tests/unit/test_monitoring.py
Specifically added support for ApiCall level `Region` and `MaxRetriesExceeded`
> Add support for additional csm fields

- .changes/next-release/enhancement-Exceptions-6452.json
- botocore/exceptions.py
- tests/unit/test_exceptions.py
There has been a few requests/PRs for this:
https://github.com/boto/botocore/issues/834
https://github.com/boto/botocore/pull/1191
https://github.com/boto/botocore/pull/835
> Add support for pickling exceptions

- botocore/data/ssm/2014-11-06/paginators-1.json
boto/boto3#1643 - This should add paginator support for `ssm get-inventory`
> boto/boto3#1643: Add paginator support for SSM.Client.get_inventory

- botocore/stub.py
> Fix UnstubbedResponseError message

- botocore/monitoring.py
- tests/functional/csm/cases.json
- tests/unit/test_monitoring.py
Specifically added the following fields to the ApiCall event:
* UserAgent
* FinalHttpStatusCode
* FinalAwsException
* FinalAwsExceptionMessage
* FinalSdkException
* FinalSdkExceptionMessage
> Add more fields to the ApiCall event 

- botocore/data/lambda/2015-03-31/waiters-2.json
> Add waiter for Lambda

- .changes/next-release/enhancement-EnvironmentVariables-90061.json
- botocore/credentials.py
- tests/unit/test_credentials.py
This pulls in https://github.com/boto/botocore/pull/1687 and simplifies the code and adds a changelog entry.
> Ignore empty strings for env var creds

- requirements.txt
- setup.py
Also fixes CVE-2019-11236
Fixes: https://github.com/boto/botocore/issues/1733
> allow the use of urllib3 1.25.x

- tests/integration/test_s3.py
This adds some retry logic in the case that our bucket cleanup function for the S3 integration tests fails to delete the bucket due to eventual consistency issues.
> Add retries and eventual consistency to bucket cleanup in integ tests

- .github/no-response.yml
Same as the AWS CLI and boto3 configuration.
> Add probot for no-response

- tests/integration/test_s3.py
There were some tests that still needed to be updated after the removal of the vendored version of requests. Specifically, we needed to fix the following:
* We were accessing the `content` property which does not exist on a urllib3 response object
* S3 requires the `file` field to be last in the POST request. However for Python 2 because the dictionary is not ordered, there is no guarantee that urllib3 will serialize it at the end of the request. The fix there was just too use an `OrderedDic`t.
> Fix s3 presign integration tests

- .changes/1.13.10.json
- .changes/1.13.11.json
- .changes/1.13.12.json
- .changes/1.13.13.json
- CHANGELOG.rst
- botocore/data/budgets/2016-10-20/service-2.json
- botocore/data/ce/2017-10-25/service-2.json
- botocore/data/codebuild/2016-10-06/service-2.json
- botocore/data/codestar-notifications/2019-10-15/paginators-1.json
- botocore/data/codestar-notifications/2019-10-15/service-2.json
- botocore/data/comprehend/2017-11-27/service-2.json
- botocore/data/efs/2015-02-01/service-2.json
- botocore/data/endpoints.json
- botocore/data/rds/2014-10-31/service-2.json
- botocore/data/savingsplans/2019-06-28/paginators-1.json
- botocore/data/savingsplans/2019-06-28/service-2.json
- botocore/data/signer/2017-08-25/service-2.json
- botocore/data/ssm/2014-11-06/service-2.json
- botocore/data/sso-oidc/2019-06-10/paginators-1.json
- botocore/data/sso-oidc/2019-06-10/service-2.json
- botocore/data/sso/2019-06-10/paginators-1.json
- botocore/data/sso/2019-06-10/service-2.json
> Merge 1.13.13 with v2

- tests/unit/test_credentials.py
- tests/unit/test_utils.py
This updates the sso tests on the v2 branch to work even if a region isn't configured.
> Fix travis on v2

- tests/integration/test_s3.py
This updates bucket and object creation to be more robust
and reduce transient failures.
* Use a consistency waiter to ensure the bucket exists immediately
after creating
* Add retries for put_object in the high level create_object method.
This will catch NoSuchBucket errors and retry them.  This happens
when we create a bucket and immediately try to upload an object
to it.
This adds about 20 seconds extra runtime overhead on my machine,
bringing these tests to about 3 minutes total execution time.
> Make s3 integ tests more robust

- tests/integration/test_s3.py
> Retry in case the deletion waiter fails

- botocore/parsers.py
> Fix simple typo: whenver -> whenever

- setup.cfg
- setup.py
See https://github.com/aws/aws-cli/pull/4756 (which will need to get merged first) for more info.
Closes https://github.com/boto/botocore/issues/1872
> Switch back to less restrictive dateutils range

- tests/integration/test_s3.py
There were some s3 integration tests we missed when we removed support for sigv2.
> Fix integration tests

- .github/no-response.yml
Update no-response.yml to consider new label name
> Update stale bot to consider new label name

- .changes/next-release/bugfix-Stubber-96340.json
- botocore/handlers.py
- tests/functional/test_stub.py
- tests/unit/test_handlers.py
> Fixing stubber to handle client error for GetBucketLocation command

- .github/stale_issue.yaml
Description of changes:
Adds a github actions workflow to drive monitoring and handling stale actions on the repo.
> Add stale-issue-cleanup workflow

- .changes/next-release/feature-SSO-95514.json
- botocore/credentials.py
- botocore/exceptions.py
- botocore/utils.py
- tests/__init__.py
- tests/functional/test_credentials.py
- tests/unit/test_credentials.py
- tests/unit/test_utils.py
This adds support for resolving temporary AWS Credentials from a profile configured to use an SSO profile.
> Add support for the SSO credential provider

- botocore/exceptions.py
Fix a few typos and inconsistencies in exception classes' docstrings and error message text.
> Minor cleanup in exception docstrings and text

- botocore/httpsession.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/boto/botocore/1811)
> Fix typo: Retrirves -> Retrieves.

- botocore/credentials.py
> Fix Typo in docstring

- botocore/data/docdb/2014-10-31/paginators-1.json
- botocore/data/docdb/2014-10-31/service-2.json
- botocore/data/docdb/2014-10-31/service-2.sdk-extras.json
- botocore/handlers.py
- tests/functional/test_docdb.py
This updates the DocDB model and injects the SourceRegion argument for
the CopyDBClusterSnapshot operation.
> Update DocDB models and inject SourceRegion

- botocore/response.py
- tests/unit/test_response.py
> implemented IOBase functions and included unit tests

- botocore/utils.py
Vendoring ipv6 validation regex patterns from urllib3. https://github.com/urllib3/urllib3/blob/7e856c0/src/urllib3/util/url.py
> Vendoring ipv6 regex patterns from urllib3

- botocore/data/dynamodb/2012-08-10/examples-1.json
Fixes https://github.com/boto/boto3/issues/1225
This example has already been fixed upstream. Every other SDK contains the correct example.
> Fixed scan example

- setup.cfg
Updates the urllib3 pin in our setup.cfg to the latest version.
> Update urllib3 pin in setup.cfg

- botocore/utils.py
- tests/functional/test_utils.py
Reordered exception handling for IMDS Fetcher
> Rearranged exception handling for IMDS

- botocore/handlers.py
- botocore/utils.py
- tests/unit/test_handlers.py
Closes https://github.com/boto/botocore/issues/1979
> Include Content-MD5 header when body is empty

- botocore/credentials.py
- botocore/session.py
- tests/functional/test_credentials.py
- tests/unit/test_session.py
Add ability to exclude extras from UserAgent
> Allow exclude extras from user agent

- README.rst
Update readme with information and link to the SDK and Tools maintenance policy.
> Add section on maintenance and support

- botocore/waiter.py
- tests/unit/test_waiters.py
Improving WaiterError exception message with failure state. Addressing https://github.com/aws/aws-cli/issues/2918
> Adding state to to WaiterError exception

- botocore/httpsession.py
Print out the certificate path when in debug mode.
> add debug logging statement to print certificate path

- setup.cfg
See: https://github.com/pypa/setuptools/pull/2588
> Update deprecated setup.cfg configuration

- .changes/next-release/bugfix-s3-27518.json
- botocore/utils.py
- tests/unit/test_utils.py
Updating new exception messages for S3 Object Lambda
> Update S3 Object Lambda references

- botocore/waiter.py
- tests/unit/test_waiters.py
Revise requirements for raising a WaiterError.
> Fix requirements for WaiterError

- README.rst
> Remove build status badge

- botocore/utils.py
Detect unsafe characters in is_valid_endpoint_url()
and is_valid_ipv6_endpoint_url() early, in order to fix rejecting
invalid URLs with Python 3.9.5+ and other versions carrying bpo-43882
fix.  In these versions, urlsplit() silently strips LF, CR and HT
characters while splitting the URL, effectively disarming the validator
in botocore.
The solution is based on a similar fix in Django.
Fixes #2377
> Fix rejecting URLs with unsafe characters in is_valid_endpoint_url()

- botocore/crt/auth.py
Fix issue #2401 by importing the exception in the file.
> Import NoCredentialsError in crt/auth.py

- botocore/loaders.py
Apologies in advance for the fact that I can't explain exactly _why_ this change should be merged. It comes about because we were seeing intermittent `OSError: [Errno 9] Bad file descriptor` errors being raised by `botocore` in our CI suite under Python 3, which runs tests in parallel using `multiprocessing`:
```
File "<censored>", line 71, in mock_s3
s3 = botocore.session.get_session().create_client('s3')
File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 828, in create_client
endpoint_resolver = self._get_internal_component('endpoint_resolver')
File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 695, in _get_internal_component
return self._internal_components.get_component(name)
File "/usr/local/lib/python3.6/site-packages/botocore/session.py", …
```
> JSONFileLoader: dedent unnecessary code inside context manager

- botocore/httpsession.py
- tests/integration/test_client_http.py
**This is currently an "experimental" feature which provides no guarantees of backwards compatibility. It may be subject to change or removal in any patch version. Anyone opting in to this feature should strictly pin botocore.**
Adding in a optional flag to start attaching a host header to HTTP CONNECT requests. This feature may have some technical limitations in parallelized environments and is currently under review in an experimental state. We welcome testing of the feature but would not encourage use in production without strictly pinning botocore, as the feature is subject to change or removal.
> Add experimental proxy host option

- .changes/next-release/enhancement-Signers-458.json
- .changes/next-release/enhancement-s3-26723.json
- botocore/configprovider.py
- botocore/crt/auth.py
- botocore/exceptions.py
- botocore/handlers.py
- botocore/regions.py
- botocore/utils.py
- tests/functional/test_s3.py
- tests/unit/crt/auth/test_crt_signers.py
- tests/unit/test_utils.py
This PR will add support for Botocore for S3 Mutli-Region Access Points and integrates support for the SigV4a signing algorithm.
> Add support for S3 Multi-Region Access Points

- botocore/auth.py
- botocore/configprovider.py
- botocore/crt/auth.py
- botocore/handlers.py
- botocore/regions.py
- botocore/utils.py
- tests/functional/test_s3.py
- tests/unit/test_utils.py
This also introduces sigv4a support in order to sign requests that go to MRAP endpoints.
> Add support for MRAP arns

- .changes/1.21.48.json
- .changes/1.21.49.json
- .changes/1.21.50.json
- CHANGELOG.rst
- botocore/data/appintegrations/2020-07-29/service-2.json
- botocore/data/connect/2017-08-08/service-2.json
- botocore/data/ec2/2016-11-15/service-2.json
- botocore/data/elbv2/2015-12-01/service-2.json
- botocore/data/endpoints.json
- botocore/data/imagebuilder/2019-12-02/service-2.json
- botocore/data/license-manager/2018-08-01/service-2.json
- botocore/data/pinpoint/2016-12-01/service-2.json
- botocore/data/transfer/2018-11-05/service-2.json
- botocore/data/voice-id/2021-09-27/paginators-1.json
- botocore/data/voice-id/2021-09-27/service-2.json
- botocore/data/wisdom/2020-10-19/paginators-1.json
- botocore/data/wisdom/2020-10-19/service-2.json
I reverted all of the commits related to moving to pytest and adding 3.9/3.10 support. We will do this in a subsequent PR.
> Merge develop branch to v2 branch

- tests/unit/test_parsers.py
Fixing small typo found in #2502.
> Fix test typo

- scripts/new-change
> Fix enhancement typo

- .changes/next-release/enhancement-Exceptions-94766.json
- botocore/httpsession.py
- tests/unit/test_http_session.py
Fix #2422
Could you kindly review this PR?
> Mask proxy url credentials

- .changes/next-release/enhancement-RequestHeader-82118.json
- botocore/handlers.py
- tests/unit/test_handlers.py
Adding request headers for lambda recursion detection.
> Adding recursion detection headers

- botocore/retries/standard.py
- botocore/retryhandler.py
- tests/unit/retries/test_standard.py
- tests/unit/test_handlers.py
- tests/unit/test_retryhandler.py
Loosening constraints on populating retries context with retry header information.
> Removing retries context constraint

- botocore/model.py
- tests/unit/test_model.py
Fixes https://github.com/boto/botocore/issues/2623
> Include pattern in Shape.METADATA_ATTRS

- .changes/next-release/enhancement-AWSCRT-36748.json
- setup.cfg
Bump current version of CRT to today's release (0.13.5).
> Update version of awscrt to 0.13.5

- .changes/next-release/enhancement-Dependency-64584.json
- setup.cfg
- setup.py
jmespath released 1.0 today. We'll add support since it's now being pulled into boto3.
> Add support for jmespath 1.0

- .changes/next-release/enhancement-AWSCRT-43547.json
- setup.cfg
Updating the awscrt to 0.13.8 to resolve issue with wheel size in 0.13.7.
> Update awscrt to 0.13.8

- tests/unit/test_awsrequest.py
Follow up to https://github.com/boto/botocore/pull/2679. Adhering to new linting rules established by black
> linting fix

- botocore/data/s3/2006-03-01/endpoint-rule-set-1.json
- tests/functional/endpoint-rules/s3/endpoint-tests-1.json
This PR will update our copies of S3's endpoint ruleset and tests to the latest version.
> Update S3 endpoint rules and tests

- .github/workflows/run-crt-test.yml
- .github/workflows/run-tests.yml
- tox.ini
> Move CI to release 3.11 build

- .pre-commit-config.yaml
Upgrade isort to resolve current action failures. See https://github.com/PyCQA/isort/issues/2083 for details
> upgrade isort

- .changes/next-release/enhancement-Documentation-89764.json
Added a changelog entry for #2866
> Added changelog for nested docs

- tests/integration/test_s3.py
Update public access settings for integration tests.
> Update block public access settings

- tests/integration/test_s3.py
Add in required API calls to change block public access settings.
Change signature version to use default (s3v4) instead of s3.
> Fix integration test for public access changes.

- tests/functional/test_endpoints.py
Fix test to handle empty endpoints for a partition.
> Fix test to handle empty endpoints for a partition

- botocore/data/endpoints.json
Sync `endpoints.json` with most recent models.
> Remove iot default credentialScope

- .changes/next-release/enhancement-AWSCRT-50323.json
- setup.cfg
Upgrade to latest release of the awscrt (0.16.26).
> Update awscrt to 0.16.26

- botocore/data/autoscaling/2011-01-01/examples-1.json
Minor correction for example name.
> Update autoscaling example name

- botocore/data/autoscaling/2011-01-01/examples-1.json
This PR updates the autoscaling examples to match the latest releases for the service.
> Add latest autoscaling examples

- .github/workflows/handle-stale-discussions.yml
Fix the pin and permissions for the handle-stale-discussions GHA.
> Fix pins and permissions for handle-stale-discussions

- tests/unit/retries/test_standard.py
https://github.com/boto/botocore/blob/49008e50529ef19076eb644aac32ae238b6e1a38/tests/unit/retries/test_standard.py#L28C1-L29C29
> Remove duplicate line

- .changes/next-release/enhancement-AWSCRT-91126.json
- setup.cfg
- setup.py
Update to the latest version of the awscrt.
> Update awcrt version to 0.19.10

- .changes/next-release/enhancement-AWSCRT-62276.json
- setup.cfg
- setup.py
Update to latest release of the awscrt to support new features for transfers.
> Update awcrt version to 0.19.17

- .changes/next-release/enhancement-AWSCRT-23378.json
- setup.cfg
- setup.py
Update to latest release of the awscrt to support new features for transfers.
> Update awcrt version to 0.19.19

- .changes/next-release/enhancement-AWSCRT-87258.json
- setup.cfg
- setup.py
Update to latest release of the awscrt to support new improvements for s3 data transfers.
> Update awcrt version to 0.20.9

- .changes/next-release/api-change-honeycode-76024.json
- botocore/data/endpoints.json
- botocore/data/honeycode/2020-03-01/endpoint-rule-set-1.json
- botocore/data/honeycode/2020-03-01/examples-1.json
- botocore/data/honeycode/2020-03-01/paginators-1.json
- botocore/data/honeycode/2020-03-01/paginators-1.sdk-extras.json
- botocore/data/honeycode/2020-03-01/service-2.json
- tests/functional/endpoint-rules/honeycode/endpoint-tests-1.json
> Revert "Remove honeycode client following the service deprecation"

- .changes/next-release/api-change-alexaforbusiness-18876.json
- botocore/data/alexaforbusiness/2017-11-09/endpoint-rule-set-1.json
- botocore/data/alexaforbusiness/2017-11-09/examples-1.json
- botocore/data/alexaforbusiness/2017-11-09/paginators-1.json
- botocore/data/alexaforbusiness/2017-11-09/service-2.json
- botocore/data/endpoints.json
- botocore/utils.py
- tests/functional/endpoint-rules/alexaforbusiness/endpoint-tests-1.json
- tests/functional/models/endpoints.json
- tests/functional/test_event_alias.py
- tests/functional/test_paginator_config.py
> Revert "Remove alexaforbusiness client following the service deprecation"

- .changes/next-release/enhancement-AWSCRT-67374.json
- setup.cfg
- setup.py
Update to latest release of the awscrt with recent bug fixes.
> Update awscrt version to 0.20.11

- .changes/next-release/enhancement-AWSCRT-49357.json
- setup.cfg
- setup.py
Update AWSCRT to the latest released version 0.21.2.
> Update awcrt version to 0.21.2

- .changes/next-release/enhancement-AWSCRT-51664.json
- setup.cfg
- setup.py
Update to latest release of the awscrt to support new improvements for query authorization in the CRT.
> Update awcrt version to 0.21.5

- botocore/regions.py
This PR fixes a formatting issue causing our `Lint code` GitHub workflow to fail.
> Fix formatting issue

- .changes/next-release/enhancement-AWSCRT-3875.json
- setup.cfg
- setup.py
Update to latest release of the awscrt (`awscrt-0.22.0`).
> Update awscrt version to 0.22.0

- botocore/configprovider.py
Remove erroneous spacing from tuple layout comment.
> Fix session variable comment

- .changes/next-release/feature-Endpoints-14344.json
This PR adds a changelog for account id based endpoints. This feature release will result in a minor version bump.
> Add changelog for Account ID Based Endpoints

- botocore/serialize.py
This PR adds support for serializing input to the RPCv2/CBOR protocol
> RPCv2 Serializer Support

- tests/functional/test_useragent.py
Refactors functional user agent string tests to use a utility function to get captured user agent strings from a stubber. The main reasons are:
* The captured requests (and therefore captured user agents) are already available in `ClientHTTPStubber`, which `UACapHTTPStubber` inherits from. Rather than creating another inheritance hierarchy, I’d prefer having a utility function that takes a client stubber as input and returns user agent strings.
* `UACapHTTPStubber` assumes and expects exactly 1 request. This may not hold for all features we want to register. It definitely won’t hold if we’re intentionally making 2 API calls on a client to test something specific (eg ensure features don’t bleed across requests).
Also add a utility function for parsing feature ids from a user agent string …
> Refactor user agent string tests

- tests/functional/test_endpoints.py
Add the @pytest.mark.validates_models flag to two new tests
> Add @pytest.mark.validates_models to test_endpoints.py

- .changes/next-release/api-change-privatenetworks-24583.json
- botocore/data/endpoints.json
- botocore/data/privatenetworks/2021-12-03/endpoint-rule-set-1.json
- botocore/data/privatenetworks/2021-12-03/paginators-1.json
- botocore/data/privatenetworks/2021-12-03/service-2.json
- tests/functional/endpoint-rules/privatenetworks/endpoint-tests-1.json
This reverts commit a4c8c09fed2c020265faa64bc9e9122c265e7cd4.
> Revert "Remove service client for privatenetworks (#3474)"
